### ISSUE TITLE
Pass firebaseuserid dynamically to the module's firestorePath

### ISSUE THREAD

**Issue by thokkane** [mesqueeb/vuex-easy-firestore#105]
In your documentation you have

```javascript
const userDataModule = {
  firestorePath: 'users/{userId}/data',
  firestoreRefType: 'collection', // or 'doc'
  moduleName: 'userData',
  statePropName: 'docs',
  // you can also add state/getters/mutations/actions
  // for other config like fillables see 'Extra features'
}
```

The firebaseuser.uid is only available after logging in. Is there a way to pass this id once available to the module's firesotrePath?

**Comment by mesqueeb** [comment]
Try passing `userId` as custom variable during openDBChannel. 
I didn’t try this yet but should work.

What situation do you need this?
You can always write `{uid}` in the path for the userId and pass the userId like that. Which may be better as it will never get confused with the firebase auth! 

Please tell me more on your use case and I can give better advice. Also make sure to read the documentation chapter on custom pathVariables. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by thokkane** [comment]
The use case is simply to pass the firebase userId into the firestorePath after successful login.

Currently the module definition sits

```javascript
const userModule = {
  firestorePath: 'users/{userId}',
  firestoreRefType: 'doc',
  moduleName: 'userData',
  statePropName: 'docs',
}


const easyFirestore = createEasyFirestore(userModule, {logging: true})

export const store = new Vuex.Store({
state : {...}
actions: {
 userSignIn ({commit}, payload) {
      commit('setLoading', true)
      firebase.auth().signInWithEmailAndPassword(payload.email, payload.password)
      .then(firebaseUser => {
        commit('setUser', {email: firebaseUser.user.email, uid: firebaseUser.user.uid})
        commit('setLoading', false)
        commit('setError', null)
        router.push('/planner')
      })
      .catch(error => {
        commit('setError', error.message)
        commit('setLoading', false)
      })
    }
},
  plugins: [easyFirestore]
})

```
The module is defined at the top and the firebaseUser uid is generated after successful login (userSignin method called upon signin button click). How can the userid be passed as a parameter to the module so that in the userSignin function above it can be provided to the module?

**Comment by mesqueeb** [comment]
Dear @thokkane 
Is should work just out of the box without passing any `userId` manually, because vuex-easy-firestore looks at `firebase.auth().currentUser.uid` when the dbchannel is opened. So I'm not sure why it's not working for you?

When I look at your code I see you are not opening the DB Channel after log in?

Can you try this for me?
```js
firebase.auth().signInWithEmailAndPassword(payload.email, payload.password)
      .then(firebaseUser => {
        // let's check if firebase.auth() has the correct user
        console.log('firebase.auth() user:', firebase.auth().currentUser.uid)
        // if this is logged properly there's no reason why it shouldn't work
        // So let's openDBChannel!
        dispatch('userData/openDBChannel').catch(console.error)
        // also, you can use the vuex-easy-firestore actions for setting the user:
        // instead of:
        commit('setUser', {email: firebaseUser.user.email, uid: firebaseUser.user.uid})
        // use:
        dispatch('userData/set', {email: firebaseUser.user.email, uid: firebaseUser.user.uid})
      })
```
Do you understand what I'm doing here above?
Try that and let me know.

(PS: if your `userData` module is a single doc, I would call the `statePropName` 'doc' instead of 'docs'. 
Because you'll only ever have one doc there... But that's personal preference. : D)

**Comment by thokkane** [comment]
Sorry, maybe i wasn't maybe clear. So in the above module configuration there is this:
firestorePath: 'users/{userId}'

When channel is opened it says in the console like this
"openDBChannel for Firestore PATH: users/{userid} [users/{userid}]"

Instead i would liek the channel should open like this
"openDBChannel for Firestore PATH: users/js7ZbtLSkHiOslLJRN0KpUPk132 [users/js7ZbtLSkHiOslLJRN0KpUPk132]"

**Comment by mesqueeb** [comment]
Yes i understand. What is happening is that you do openDBChannel before your user signs in. 

You need to dispatch openDBChannel after the user is found like in my example. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by c0h1b4** [comment]
I have the same problem here. The {userId} is not converted to 'js7ZbtLSkHiOslLJRN0KpUPk132'and I get the following on the log messages:

openDBChannel for Firestore PATH: users/{userId} [users/{userId}]

when the correct would be

openDBChannel for Firestore PATH: users/js7ZbtLSkHiOslLJRN0KpUPk132 [users/{userId}]

**Comment by c0h1b4** [comment]
I was checking my code, if I do a refresh the {userId} is converted to the `js7ZbtLSkHiOslLJRN0KpUPk132`.  So it looks like it takes some time for the module to receive the userId from the Firestore. 
Is there a way to make the module wait for Firestore to propagate the userId?

**Comment by mesqueeb** [comment]
@c0h1b4 and @thokkane 
I have no idea what is causing this issue. I never had it and have not been able to replicate this. 

Do you know the steps to replicate the issue? Or can you share your repository with me?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mesqueeb** [comment]
I think I fixed it on version > 1.22.6 ?
Can you please check it for me and let me know?
Since I can't replicate the issue I can't test.

**Comment by thokkane** [comment]
@mesqueeb updating the package worked for me. Thank you!

Now firesttorepath is as such firestorePath: 'users/{userId}', and works correctly.

**Comment by c0h1b4** [comment]
I made a workaround connecting directly because it was just for 1 doc. But I will try it later.
I believe that there was some delay between the auth() module and the propagation of the userId value.

Thanks.

**Comment by mesqueeb** [comment]
Ok that's great! So just be sure you only `openDBChannel` or `fetchAndAdd` **after** the authentication promise has resolved. (so inside `then`)

If you still have problems feel free to open another issue! o(^_-)O
