### ISSUE TITLE
{userId} not properly resolved when signing in with different user

### ISSUE THREAD

**Issue by usu** [mesqueeb/vuex-easy-firestore#110]
Module defined as following:
```
const userSettingsModule = {
  firestorePath: 'users/{userId}',
  firestoreRefType: 'doc',
  moduleName: 'userSettings',
  statePropName: 'doc',
};
```

openDBChannel is called after onAuthStateChanged as described in the documentation. This creates problems, when a different user has previously been signed in.

Sometimes {userId} is not resolved in the path at all:
`openDBChannel for Firestore PATH: users/{userId} [users/{userId}]`

Sometimes {userId} is resolved with the previously signed in user id.

Both create a permission error, when proper security rules are in place on Firebase side.

Not sure, but could be related to the fact, that __sync.signedIn and __sync.userId are not cleared properly when closing the channel.

**Comment by usu** [comment]
Yep, that is exactly what I ended up doing 😄

Just thinking out load: If this is later added to the closeDBChannel action, the case where openDBChannel is called 2x without closeDBChannel in between should probably also be considered (e.g. user signing in with new credentials without signing out first).

**Comment by mesqueeb** [comment]
Please be sure to be at least on version 1.22.6 !

**Comment by usu** [comment]
Hi @mesqueeb. I tested with 1.25.1 today.

It now works fine for multiple signin/signout calls, in case closeDBChannel is properly called in between.

I ran into issues, when openDBChannel was called twice (new user signs in without old user signing out before). So I had to make sure that before opening the channel, the application checks whether a user has been signed in and whether any channels had been opened previously. But that seems to be a good idea, anyway.

I would regard the issue as closed 👌

**Comment by mesqueeb** [comment]
What issues did you ran in? 
I think you should do closeDBChannel with {clearModule: true} right? Otherwise the Firestore onSnapshot listener will stay open and the previous user docs will remain there. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by coolhand79** [comment]
I have encountered this issue in 1.25.2

Here's the basics:

CurrentMemberModule:
```javascript
export default {
    state: {},
    firestorePath: "members/{userId}",
    firestoreRefType: "doc",
    moduleName: "currentMember",
    actions: {
        loginWithEmail: async function({}, payload) {
            await firebase.auth().signInWithEmailAndPassword(payload.email, payload.password);
        },

        logout: async function({ dispatch, state }) {
            await firebase.auth().signOut();
            await dispatch("closeDBChannel", {
                clearModule: true
            });
        }
}
//...
```

Use:
```javascript
     // correctly outputs the user id
     console.log("userId:", firebaseApp.auth().currentUser.uid);

     // opening db
     await store.dispatch("currentMember/loginWithEmail", {
         email: 'email1@somewhere.com',
         password: 'secret'
     });
     await store.dispatch("currentMember/openDBChannel");
     
    // SUCCESS, let's try again
     await store.dispatch("currentMember/logout");


     // correctly outputs the user id
     console.log("userId:", firebaseApp.auth().currentUser.uid);

     await store.dispatch("currentMember/loginWithEmail", {
         email: 'email1@somewhere.com',
         password: 'secret'
     });
     await store.dispatch("currentMember/openDBChannel");
     // FAIL with permission error: https://cl.ly/69af6a96cf1d
```

Adding this to the logout method works (for now)
```javascript
     state._sync.signedIn = null;
     state._sync.userId = null;
```

Let me know if there's anything else you need 👍

**Comment by mesqueeb** [comment]
@coolhand79 do you use SSR?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by coolhand79** [comment]
Server side rendering? No, I don't.

**Comment by coolhand79** [comment]
Yes, fair enough 😄 Writing my example code too fast, I suppose.

I've updated it 🌵

**Comment by mesqueeb** [comment]
@coolhand79 After the last `openDBChannel` can check your vuex history stack and see if SET_USER_ID was in the mutations near the end?

Also after second openDBChannel, can you console.log (or just look via the console) at the variables

- `state._sync.signedIn`
- `state._sync.userId`
- `getters.firestorePathComplete`

Can you tell me what they are?
The thing is, they should be overwritten either way, so I'm not sure what the problem is.

**Comment by mesqueeb** [comment]
@coolhand79 I [wrote a test](https://github.com/mesqueeb/vuex-easy-firestore/blob/dev/test/user.js) based on your setup. the test passes.

I'm not sure how I can replicate what you are facing. Do you have any more info for me? I am literally doing the test just like your setup... : (

**Comment by mesqueeb** [comment]
Guys I'm having difficulty replicating this bug. I think I had it once in my project but then it went away so I think it might have been unrelated.

If anyone can give any more info on this bug, much appreciated!

**Comment by mesqueeb** [comment]
@coolhand79 @usu 

I went through hell and came out stronger! I finally was able to tackle every rare case of the userId bug!!! **EVERYTHING SHOULD WORK FINE NOW.**

Please update to the latest version and test it out!!!!

And comment below if you still have any problems!

**Comment by usu** [comment]
@mesqueeb Nice, worked for me in the last version. Thanks for digging into this tricky one!
