### ISSUE TITLE
best practice question

### ISSUE THREAD

**Issue by c0h1b4** [mesqueeb/vuex-easy-firestore#115]
Hello, I would like to have multiple filters for a single collection, where I can access those filters like a computed variable or a getter from the store.

What is the best approach for this?

I am actually opening 3 DataModules with the 'where' clause, but I believe that there must be an easier or more practical way to implement this.

Thanks,
David

**Comment by c0h1b4** [comment]
I made a getter like in the tutorial. Sorry.

const getters = {
  newOrders: state => {
    return Object.values(state.orderData.orders).filter(order => exame.step === 0)
  }
};

**Comment by mesqueeb** [comment]
I'm happy it worked out! Anything else feel free to ask!
