### ISSUE TITLE
Arrayunion not working after webpack?

### ISSUE THREAD

**Issue by zabaat** [mesqueeb/vuex-easy-firestore#123]
In dev mode everything works fine
![image](https://user-images.githubusercontent.com/3325067/50570218-bf92af80-0d35-11e9-891d-026db9be27f7.png)

after build process
![image](https://user-images.githubusercontent.com/3325067/50570224-e81aa980-0d35-11e9-8a94-8224a7001003.png)

Relevant code:
```js
import {
    arrayUnion
} from 'vuex-easy-firestore'
...
...

        return new Promise((resolve, reject) => {
            if (cItemKey === '') {
                cItemKey = shortid.generate()
                console.log('no cart itemKey set, generated:', cItemKey)
            }
            const payload = {
                id: activeOrderId,
                cart: {
                    [cItemKey]: cartItem
                },
                items: arrayUnion(cartItem.id),
                vendors: arrayUnion(cartItem.vendorId),
            }
            console.log("sending order payload", payload)
            return store
                .dispatch(`order/patch`, payload, {
                    merge: true
                })
                .then(resolve)
                .catch(reject)
        })
```

**Comment by mesqueeb** [comment]
Wow that’s weird!!! Seems difficult to debug as well. Let me try. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mesqueeb** [comment]
Btw, `Merge: true` is not applicable like that on a vuex action. 
And vuex easy firestore has `{merge: true}` automatically since `patch` works with firestore’s `update` instead of `set` with `{merge: true}`

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mesqueeb** [comment]
It’s because webpack is changing something and therefore my `isArrayUnion` check is failing

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by zabaat** [comment]
Appreciate the prompt response! I was going to try the native arrayUnion function next, will let you know

**Comment by mesqueeb** [comment]
@zabaat 
Sorry, on an unrelated note:
I saw you commented on `cordova-plugin-firebaseui-auth` that you ended up using a combination of:

`cordova-plugin-firebase-authentication` and `cordova-plugin-googleplus`

I'm actually trying to get my Quasar app with Firebaseui authentication to work on Android and/or iOS with cordova now : D 
I think we have a very similar setup! Did you get it to work?

I'd love to be able to chat with you. You can find me on telegram/twitter via `mesqueeb` or on discord via `Luca Ban (Mesqueeb)#4774` if of course, it's no problem for you.

**Comment by mesqueeb** [comment]
Should be fixed in latest version. (1.25.2)

Please try `npm i vuex-easy-firestore@latest`
and let me know!

If it is fixed, please close the issue! ♡
