### ISSUE TITLE
Realtime updates seems works in one way

### ISSUE THREAD

**Issue by GerryKeys** [mesqueeb/vuex-easy-firestore#125]
Hi, and thanks for your work on this project.

I have a problem with fetching realtime data using openDBChannel mode.

If i try to edit my data from the google firebase dashboard, vuex-easy-firestore intercept correctly the hooks (serverChange) in my module, but the data in my custom vue component, after an initial sync, doesn't sync anymore.

No problem instead with the operations from my-module to firebase cloud storage.

Here is my module:

**[module.js]**
```
export const ProductsModule = {
    firestorePath: 'products',
    firestoreRefType: 'collection', // or 'doc'
    moduleName: 'products',
    statePropName: 'data',
    namespaced: true, // optional but recommended,
    serverChange: {
      convertTimestamps: {},
      // HOOKS for changes on SERVER:
      addedHook: function (updateStore, doc, id, store) { return updateStore(doc) },
      modifiedHook: function (updateStore, doc, id, store) { return updateStore(doc) },
      removedHook: function (updateStore, doc, id, store) { return updateStore(doc) },
    }
  }
```
i call `store.dispatch('products/openDBChannel')` from my vuex store file after registering the plugin with `plugins: [easyFirestore]`

my component is like this:

```
<template>
    
  <div>
   <fade-transition>
      <div class="box" v-show="show">
        <ul id="example-1">
          <li v-for="item in products" :key="item['id']" >
            {{ item.id }}
          </li>
        </ul>
        <p>login page</p>
      </div>
   </fade-transition> 
  </div>


</template>

<script>

export default {

data ()
{
  return {
    show : false,
    products: Object.values(this.$store.state.products.data)
    }
},
mounted: function () {

  // show transition
  setInterval(() => { this.show = true;}, 100);

}

}
</script>
```
when i load the page, it shows correctly the products, but if i try to add a product using the google firebase console, the component doesn't react to the changes.

**Comment by GerryKeys** [comment]
I have solved the issue,

i used the props in order to pass the data to the component and now it works!

Thank you for your awesome plugin.

**Comment by mesqueeb** [comment]
@GerryKeys Sorry for the delayed response!!

I saw your post but didn't know where the error was when I looked yesterday. Everything should work fine with the current build.

I'm happy you resolved your bug. However, I'm confused because showing data directly from the store should work. I'm not sure why it does not.

Maybe instead of `data` which is not reactive, use `computed` instead:

```js
data ()
{
  return {
    show : false,
  }
},
computed:
{
  products () { return Object.values(this.$store.state.products.data) }
},
```

I also wanted to give you another hint about this part:

```html
<li v-for="item in products" :key="item['id']" >{{ item.id }}</li>
```

You don't need to transform an object into an Array to be able to work with it in `v-for`. So you could even do this:

```html
<li v-for="(item, id) in $store.state.products.data" :key="id" >{{ id }}</li>
```

Crazy huh! 😜 but you'll loose any custom order in the list items, because an object doesn't have a fixed prop order. So only if you need a custom order for the items, convert it to an array and add a sort function in a computed prop.

**Comment by GerryKeys** [comment]
Thanks for your suggestions!
Have a nice day

**Comment by mesqueeb** [comment]
For anyone working with HOOKS, there has been a small (non-breaking) change to their behaviour.

Please read about it in the [latest release](https://github.com/mesqueeb/vuex-easy-firestore/releases/tag/v1.26.0).

**Comment by mesqueeb** [comment]
---
After about two years of open source, I finally got accepted for Github Sponsors!

#### 💜 [github.com/sponsors/mesqueeb](https://github.com/sponsors/mesqueeb) 💜 

A little about me:
- I love open-source
- 6 months ago I got a son, and am trying to be an awesome father 😅
- I'm doing freelance work here and there as my main job

#### If anyone was helped with vuex-easy-firestore, **I'd greatly appreciate any support**!

> BTW, donations get's paid DOUBLE by GitHub! (they're alchemists... 🦾)

Going forward 👨🏼‍💻
- I got great plans for the future of vuex-easy-firestore going above and beyond!! Look forward to it!!
- On to many more years of open-sourcing! 🎉
