### ISSUE TITLE
[Question] Firebase service named 'auth' already registered error

### ISSUE THREAD

**Issue by GerardoSabetta** [mesqueeb/vuex-easy-firestore#126]
Hi everyone, I tried to debug this on my own but I can't seem to get it work, I want to try and include this awesome repo in my project but I can't seem to get it to work, whenever I try to add the plugin to my store I get a "duplicated service" Firebase Error
`"{"code":"app/duplicate-service","message":"Firebase: Firebase service named 'auth' already registered (app/duplicate-service).","name":"auth"}"`

How can I fix this? Thanks in advance, cheers!

**Comment by GerardoSabetta** [comment]
Thanks a lot for the immediate reply!

**Comment by mesqueeb** [comment]
@GerardoSabetta Added it to a FAQ in the docs
 
https://mesqueeb.github.io/vuex-easy-firestore/faq.html

**Comment by reut-soficoop** [comment]
Hi, I'm almost about to give up...
I'm fighting against ```Firebase: Firebase service named 'firestore' already registered.```

This is my store.ts
```javascript
import Vue from "vue";
import Vuex from "vuex";
import { argsModule } from "./modules/Arguments";
import { display } from "./modules/Display";
import { documentModule } from "./modules/Document";
import { mainModule } from "./modules/Main";
import { notifications } from "./modules/Notifications";
import { usersModule } from "./modules/Users";
import { sectionsManager } from "./modules/SectionsManager";
import { userModule } from "./modules/User";
import { newSections } from "./modules/Sections-new";
import vuexEasyFirestore from "vuex-easy-firestore";
import * as Firebase from "firebase/app";
import { config } from '@/config';

Vue.use(Vuex);

Firebase.initializeApp(config.firebaseConfig[process.env.NODE_ENV!]);
const FirebaseDependency = Firebase;

// TODO: better naming convention - user & users
const easyFirestore = vuexEasyFirestore(
  [newSections, sectionsManager, argsModule, mainModule, documentModule, usersModule, userModule],
  {
    logging: true,
    FirebaseDependency
  }
);

export const store = new Vuex.Store({
  state: {
    version: "1.0.0"
  },
  modules: {
    display,
    notifications
  },
  plugins: [easyFirestore]
});
```

And this is my main.ts file:
```javascript
import Vue from "vue";
import { router } from "./router";
import { store } from "./store";
import "./registerServiceWorker";
import Vuetify from "vuetify";
import "vuetify/dist/vuetify.min.css";
import VueTruncate from "vue-truncate-filter";
import "font-awesome/css/font-awesome.min.css";
import VeeValidate from "vee-validate";
import VueScrollTo from "vue-scrollto";
import VSwitch from "v-switch-case";
import App from "./App.vue";

Vue.config.productionTip = process.env.NODE_ENV === "production" ? true : false;
Vue.use(VueTruncate);
Vue.use(VeeValidate);
Vue.use(VSwitch);
Vue.use(VueScrollTo);
Vue.use(Vuetify, {
  rtl: true,
  iconfont: "fa4",
  theme: {
    white: "white",
    yellow: "#ecd138",
    purple: "#69378e",
    purpleTransparent: "#8860a6",
    blue: "#b3d4fc"
  }
});

new Vue({
  store,
  mixins: [],
  props: ["title"],
  router,
  render: h => h(App)
}).$mount("#app");

```

@mesqueeb can you help me solve it?
Thanks!

**Comment by mesqueeb** [comment]
@reut-soficoop Very weird. It seems that you do everything correct...

Try this:
- firebase.ts
```ts
import * as Firebase from 'firebase/app'
import { config } from '@/config'

Firebase.initializeApp(config.firebaseConfig[process.env.NODE_ENV!])

export default Firebase
```
- store.ts
```ts
import Vue from 'vue'
import Vuex from 'vuex'
import vuexEasyFirestore from 'vuex-easy-firestore'
import FirebaseDependency from '@config/firebase' // edit path
// other modules

Vue.use(Vuex)

const easyFirestore = vuexEasyFirestore(
  [newSections, sectionsManager, argsModule, mainModule, documentModule, usersModule, userModule],
  {logging: true, FirebaseDependency}
)
// the rest
```
This is almost identical to what I have, but it works on my end. No idea why yours doesn't work.

Be sure to double check you're not importing firebase/app anywhere else in your app. If you do it must be after the store instantiation.

**Comment by reut-soficoop** [comment]
@mesqueeb 
Thanks,
I looked over again and one of my modules had firebase/app import.

**Comment by mesqueeb** [comment]
Oh!! I’m happy you got it!!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mesqueeb** [comment]
---
After about two years of open source, I finally got accepted for Github Sponsors!

#### 💜 [github.com/sponsors/mesqueeb](https://github.com/sponsors/mesqueeb) 💜 

A little about me:
- I love open-source
- 6 months ago I got a son, and am trying to be an awesome father 😅
- I'm doing freelance work here and there as my main job

#### If anyone was helped with vuex-easy-firestore, **I'd greatly appreciate any support**!

> BTW, donations get's paid DOUBLE by GitHub! (they're alchemists... 🦾)

Going forward 👨🏼‍💻
- I got great plans for the future of vuex-easy-firestore going above and beyond!! Look forward to it!!
- On to many more years of open-sourcing! 🎉
