### ISSUE TITLE
Prop deletion on server is not handled on client

### ISSUE THREAD

**Issue by mesqueeb** [mesqueeb/vuex-easy-firestore#128]
By @zabaat

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by zabaat** [comment]
workaround for now, in your store file, just put your logic into your modifiedHook to make the direct modification to the store that you will need to make using normal Vuex methods.
```js
        serverChange: {
            modifiedHook(updateStore, doc, id, store, source, change) {
                // do stuff here!!
                return updateStore(doc)
            },
```

**Comment by mesqueeb** [comment]
Firebase always sends an entire document, no matter which value was actually changed or deleted. That's why we'll need to check each incoming modification to see which props are missing that are present on the local doc, and delete them from the local doc. 

Started work on a library that will help me find which props are not present anymore. 
https://github.com/mesqueeb/compare-anything/blob/master/README.md 

Need to make it compatible with nested props etc so will need but more time. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mesqueeb** [comment]
@zabaat can you try with latest version and let me know?

**Comment by mesqueeb** [comment]
@zabaat Sorry, wasn't fixed when I said it was 8 days ago.
Now it's fixed!

Please try with `npm i vuex-easy-firestore@latest`
and let me know!
