### ISSUE TITLE
Simple setting page with vuex-easy-firestore

### ISSUE THREAD

**Issue by pitw** [mesqueeb/vuex-easy-firestore#132]
I'm trying to set up a simple "Settings Page" where user can store his settings (auth with firebase).

I'm able to read values which are manually written into Firebase - but not able to write.

**My code:**

**store / vuex**

```
const settingsModule = {
    state: {
        address: {
            street: '',
            plz: '',
            city: ''
        }
    },
    mutations: {
        setSettings(state,address) {
            state.address = address;

        }},
    getters: {
        getSettings: state => {
            return state.address
        }
    },
    actions: {
        setSettings (context) {
          context.commit('setSettings')
        }
    },
    firestorePath: 'Settings/{userId}',
    firestoreRefType: 'doc',
    moduleName: 'settingsModule',
    statePropName: 'data',
    namespaced: true,
}
```

**Component**

```
...
     <v-layout row>
                  <v-flex xs12>
                    <v-text-field v-model="settings.data.street" label="Street" required></v-text-field>
                  </v-flex>
                </v-layout>
             <v-layout row>
                  <v-flex xs6>
                    <v-text-field v-model="settings.data.plz" label="PLZ" required></v-text-field>
                  </v-flex>
                        <v-flex xs6>
                    <v-text-field v-model="settings.data.city" label="City" required></v-text-field>
                  </v-flex>
                </v-layout>
                <button @click="saveSettings">Save Settings</button>
              </form>
...
<script>
import {mapActions} from 'vuex';
import {mapState} from 'vuex';

export default {
  methods: {
   ...mapActions('settingsModule', [
    'setSettings',
   ]),
    saveSettings() {
     this.setSettings(this.settings);
    }
  },
  computed: {
      ...mapState({
      settings: state => state.settingsModule,
    })
    }
}
</script>
```

Doesn anybody see what I'm doing wrong?

**Comment by mesqueeb** [comment]
@pitw Hi! Thanks for the issue. 
You have to read the documentation on [add and manage data > 'doc' mode](https://mesqueeb.github.io/vuex-easy-firestore/add-and-manage-data.html#doc-mode)

If you read this you will understand the actions you can use to update your doc.

In your case you can just do:
```js
dispatch('settingsModule/set', {address: 'new address'})
```
and that's it.

you don't need to set up any mutations or actions if you are just updating simple values.

You can even do straight from your templates:
```html
<v-text-field
  :data="$store.state. settingsModule.address.street"
  @change="val => { $store.dispatch('settingsModule/set', {address: {street: val}}) }"
  label="Street"
  required
/>
```

**Comment by mesqueeb** [comment]
@pitw I believe you 😃
Do you have any advice for me how I could make the "Add and manage data" section clearer?
I'd love you input!!

**Comment by pitw** [comment]
My idea for making sections a bit clearer would be some kind of "snippets" (like you did above) in practical use.

It doesnt have to be a fully working and beautifully designed demo application - it can be just some quickly written together code so we get the idea how its meant to be used.

This lib has so many nice an well-considered features that its often hard to understand (at least for me) which feature is best used for which case.
