### ISSUE TITLE
Module state not updated after `set` action

### ISSUE THREAD

**Issue by bpkennedy** [mesqueeb/vuex-easy-firestore#135]
Still coming along with your library in a side project with namespaces modules.  Now I am performing a "module/set" action and it is correctly updating the database.  However the Vuex state (an array) is not being updated.  However, I see that "moduleData" array IS correctly updated - it just doesn't update Vuex state.

Is there something critical that I am missing?  I even tried recalling the "/fetch" and "/fetchAndAdd" but it still doesn't add to the store until I do a browser refresh.  It apparently sees it as querySnapshot.done is true even though I just added one and I would think it would want to pick that up.  I kind of wish that ther was an easy way to tell Vuex-easy-firestore that it needs to throw away what it thinks is "done" and get all fresh again.

Is this where the hooks come in?  I have tried the insert hook and it is the same behavior.

**Comment by bpkennedy** [comment]
Sorry for the typos and syntax errors.  I've had quite a lot of whiskey tonight.

**Comment by mesqueeb** [comment]
@bpkennedy Let's get to the bottom of this.

First of all, a `set` action SHOULD update vuex as well, so we will focus on making that to work properly.
If this works properly we shouldn't have any reason to try and force a complete reset of the state and re-fetching it from firestore again. So let's not focus on that.

First of all, working with arrays can be tricky. Are you overwriting the current array completely, providing it with a new array? Or are you using the [arrayUnion helper](https://mesqueeb.github.io/vuex-easy-firestore/firestore-fields-and-functions.html#arrayunion-and-arrayremove)?

If you are using arrayUnion, please also make sure you're on the latest version of the library, as I had a small bug fix there recently.

Anyway, please provide me with this information so I can check what's wrong:

- The state prop and value before your `set` action
- The exact way you dispatch the `set` action and its payload
- The state prop and value after your `set` action → unchanged?
- Do you see any log about data being patched? Can you open the changes and also provide a screenshot of this?

Cheers!

**Comment by bpkennedy** [comment]
Sounds good, I will be able to get you that in a few hours.

I am overwriting the array whenever I setStories  in my mutation:

```
   Vue.set(state, 'publicStories', [...publicStories])
```

I call that mutation directly after doing a manual /fetch, bundling the querySnapshot docs into an array and push them forward.

I think the issue is that the .done on that call is true - so there is nothing to add/the action bails and doesn't even call that mutation.

I'll get you the other info.

**Comment by mesqueeb** [comment]
Oh no, I see what's wrong. `Vue.set` is completely separate from vuex-easy-firestore's `set` action. So you are using the wrong syntax.

With vuex-easy-firestore you can only use one of these 4 actions:
- dispatch('modulename/set', object)
- dispatch('modulename/insert', object)
- dispatch('modulename/patch', object)
- dispatch('modulename/delete', string)

You cannot use Vue.set, so please don't do that. Vue.set is used by vuex-easy-firestore under the hood. : D

So in your case just do `dispatch('modulename/set', {publicStories: [...publicStories]})` and everything will work!

(change 'modulename' with your module name!)

**Comment by bpkennedy** [comment]
Ah cool, I'll give it a shot and let you know results.

**Comment by bpkennedy** [comment]
Hmm, I think I see what I'm doing here - am i needlessly duplicating storiesData (the Vuex-easy-firestore module) with a separate non-VEF module and trying to keep them reconciled?  Along with deduping  data, I suppose it's better to pick one or the other.

**Comment by bpkennedy** [comment]
All works, and is working well.  Problem solved!  Just usage/misunderstanding the setup of the library.  Thanks!

**Comment by mesqueeb** [comment]
@bpkennedy Great to know! Sorry I couldn't be of more help. : S

please let me know if there's anywhere in the documentation you think I should improve!!
