### ISSUE TITLE
patchBatch example

### ISSUE THREAD

**Issue by thokkane** [mesqueeb/vuex-easy-firestore#141]
How should the patchBatch be called if i have a set of ids and want specific data for each to be updated?

dispatch('moduleName/patchBatch', {doc: {}, ids: []})

**Comment by thokkane** [comment]
Ok. Its just calling 
modifiedHook: function (updateStore, doc, id, store, source, change) {updateStore(doc);  }
for each dispatch('myModule/set', doc) even if they are automatically batched.

Is there a way to fire the modifiedHook only once for a batch?

**Comment by mesqueeb** [comment]
No, this is because of how the Firestore js SDK behaves. It will always fire for each doc individually. 

What is your use case? Maybe I can help you with a work-around. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mesqueeb** [comment]
I'll close because of inactivity. Feel free to continue the discussion below though.
