### ISSUE TITLE
oderBy created_at DESC, item inserted at end instead of at the beginning

### ISSUE THREAD

**Issue by usu** [mesqueeb/vuex-easy-firestore#147]
I have a collection that orders items in reverse order of creation time (newest at the top).

```javascript
store.dispatch('exampleCollection/openDBChannel', {
          where: [
            ['created_by', '==', '{userId}'],
          ],
          orderBy:
            ['created_at', 'desc'],
        })
```

New items are inserted at the end of the list instead of at the beginning. After page reload (refetch of the data), the newly inserted document appears correctly at the beginning of the list.

**Comment by mesqueeb** [comment]
Hi usu! Thanks for your question!
Did you read the [documentation on orderBy](https://mesqueeb.github.io/vuex-easy-firestore/query-data.html#where-orderby-filters)?
There I explain exactly what you can do. ^^

<sub>Vuex Easy Firestore was made with ♥ by Luca Ban.<br>If this library helped you in any way you can support me by buying me <a href="https://www.buymeacoffee.com/mesqueeb">a cup of coffee</a>.</sub>

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by usu** [comment]
Thanks @mesqueeb for pointing this out.
Somehow managed to skip this while reading the docs.

**Comment by mesqueeb** [comment]
@usu no problem! I prbably added that part later so. XD

Good luck!!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mesqueeb** [comment]
---
After about two years of open source, I finally got accepted for Github Sponsors!

#### 💜 [github.com/sponsors/mesqueeb](https://github.com/sponsors/mesqueeb) 💜 

A little about me:
- I love open-source
- 6 months ago I got a son, and am trying to be an awesome father 😅
- I'm doing freelance work here and there as my main job

#### If anyone was helped with vuex-easy-firestore, **I'd greatly appreciate any support**!

> BTW, donations get's paid DOUBLE by GitHub! (they're alchemists... 🦾)

Going forward 👨🏼‍💻
- I got great plans for the future of vuex-easy-firestore going above and beyond!! Look forward to it!!
- On to many more years of open-sourcing! 🎉
