### ISSUE TITLE
[Help Needed] unknown action type: fetchAndAdd

### ISSUE THREAD

**Issue by CelticParser** [mesqueeb/vuex-easy-firestore#149]
I having issues implementing vuex-easy-firestore.  I have attempted various methods and keep getting to the same end point of 

>unknown action type: logbookSummary/fetchAndAdd

Possibly related to [issue#44](https://github.com/mesqueeb/vuex-easy-firestore/issues/44#issue-363614129)?

Bellow is all related files (Commented sections are various attempts). Appreciate any help you can give - Thnx!

```js
// @/stores/index.js
import Vue from 'vue';
import Vuex from 'vuex';

import createEasyFirestore from 'vuex-easy-firestore'
import createEasyAccess from 'vuex-easy-access'

// Modules
import authModule from './modules/auth/store';
import logbookSummary from '@/modules/log-widget/_store'

const fireStorePlugin = createEasyFirestore(
  [logbookSummary],
  { logging: true }
)

const easyAccessPlugin = createEasyAccess({
  vuexEasyFirestore: true
})

const store={
  plugins:[fireStorePlugin, easyAccessPlugin]
}

Vue.use(Vuex);
export default new Vuex.Store({
  modules: {
    authModule,
    logbookSummary
  },
  store
});
```
```js
// @/modules/log-widget/_components/containers/LogbookSummaryContainer.vue
import store from '@/stores'
import state from '../../_store'

import { EventBus } from '../../_utils/event-bus'
import { mapState } from 'vuex'

export default {
  . . .

  beforeCreate() {
    store.registerModule("logbookSummary", state);
    this.$nextTick(() => {
      store.dispatch('logbookSummary/queryLogbookSummary');
      // store.dispatch('logbookSummary/fetchAndAdd', null, {root: true})
    })
  },

  // mounted() {
    // store.dispatch('logbookSummary/getLogSummary');
    // store.dispatch('logbookSummary/fetchAndAdd', null, {root: true})
  // },
}

. . . 
```
```js
// @/modules/log-widget/_store/index.js
import api from '../_api/mock';
import store from '@/stores'

export default {

  firestorePath: 'users/{userId}/logSummary',
  firestoreRefType: 'collection',
  moduleName: 'logbookSummary',
  statePropName: 'data',

  namespaced: true,

  state: {},

  getters: {},

  mutations: {

    TOTAL_HRS_UPDATED (state, val) {
      state.totHrs = val;
    },
    AIR_HRS_UPDATED (state, val) {
      state.airHrs = val;
    },	
    PIC_HRS_UPDATED (state, val) {
      state.picHrs = val;
    },	
    PMC_HRS_UPDATED (state, val) {
      state.pmcHrs = val;
    },	
    VO_HRS_UPDATED (state, val) {
      state.voHrs = val;
    },	
    TRNG_HRS_UPDATED (state, val) {
      state.trngHrs = val;
    },

  },

  actions: {

    async queryLogbookSummary () {

      store.dispatch('logbookSummary/fetchAndAdd', null, {root: true})

      // async queryLogbookSummary ({ commit }) {

      // return new Promise((resolve, reject) => {

      //   api.fetchLogSummaryData
      //   .then((response) => {
    
      //      const r = response,
      //      totHrs = r.total,
      //      airHrs = r.airborne,
      //      picHrs = r.PIC,
      //      pmcHrs = r.PMC,
      //      voHrs = r.VO,
      //      trngHrs = r.training
  
      //      commit('TOTAL_HRS_UPDATED', totHrs ),
      //      commit('AIR_HRS_UPDATED', airHrs ),
      //      commit('PIC_HRS_UPDATED', picHrs ),
      //      commit('PMC_HRS_UPDATED', pmcHrs ),
      //      commit('VO_HRS_UPDATED', voHrs ),
      //      commit('TRNG_HRS_UPDATED', trngHrs ),
  
      //      resolve()
      //    })
      // })
      // .catch((error) => {
      // 	// eslint-disable-next-line
      // 	console.error(error);
      // });
    }
  }
}
```

**Comment by mesqueeb** [comment]
Hi @CelticParser 
thanks for your issue. You just made a small mistake in your configuration.
instead of:
```js
const store={
  plugins:[fireStorePlugin, easyAccessPlugin]
}
export default new Vuex.Store({
  modules: {
    authModule,
    logbookSummary
  },
  store
});
```
you need to do this:
```
export default new Vuex.Store({
  modules: {
    authModule,
  },
  plugins:[fireStorePlugin, easyAccessPlugin]
});
```
logbookSummary should only be passed through the plugin and not added as module.
because my library will take care of adding it as module for you.

PS, I made a sample app, but I haven't finished editing the video yet.
But for now you can [have a look at the repo](https://github.com/mesqueeb/vuex-easy-firestore-sample-app).

**Comment by CelticParser** [comment]
Sorry, I just got back on this today;

I completely rebased this app to use a different framework (Quasar) on monday and I just finally was able to test implementing VuexEasyFirestore into it today -- Awesome! Works like a charm.

I think the whole issue was I was (originally, and not realizing), that I was trying to access the store.modules outside of the Vue instance. Doh!

Thnx!

**Comment by mesqueeb** [comment]
You could do that if you save `store` to the window object. Otherwise be sure to use the correct configuration for adding your vuex-easy-firestore modules to your store, as I show in the example above. 

Ps I also use Quasar for everything 😀

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mesqueeb** [comment]
---
After about two years of open source, I finally got accepted for Github Sponsors!

#### 💜 [github.com/sponsors/mesqueeb](https://github.com/sponsors/mesqueeb) 💜 

A little about me:
- I love open-source
- 6 months ago I got a son, and am trying to be an awesome father 😅
- I'm doing freelance work here and there as my main job

#### If anyone was helped with vuex-easy-firestore, **I'd greatly appreciate any support**!

> BTW, donations get's paid DOUBLE by GitHub! (they're alchemists... 🦾)

Going forward 👨🏼‍💻
- I got great plans for the future of vuex-easy-firestore going above and beyond!! Look forward to it!!
- On to many more years of open-sourcing! 🎉
