### ISSUE TITLE
Thoughts on alternatives to Firestore?

### ISSUE THREAD

**Issue by BenAHammond** [mesqueeb/vuex-easy-firestore#150]
I am looking into alternatives to Firestore that allow me more power and cost less. In the process, I've run across [Wrest](https://github.com/PWAckerman/wrest) and wanted to get your thoughts.

**Comment by BenAHammond** [comment]
Oh totally, I don't expect you to do the work, I'm just discussing ideas.

Interesting point on the DB style, I was chalking up the relational
functionality as a plus :-)

**Comment by mesqueeb** [comment]
Hehehe i just fell in love with NoSQL since it’s so free to change anything at any time. Add props there and there. Change prop types. Etc. All that without having to worry about columns, column types, making db migrations, joining tables etc etc. 

I left the sequel hole and am not eager to go back any time soon. XD

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BenAHammond** [comment]
Yeah, I mostly just want to find a decently viable path to swap out
Firestore before I become to so reliant on it I cannot migrate away.

**Comment by mesqueeb** [comment]
Why don't you try hosting mongo on your own server 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BenAHammond** [comment]
Yeah I'm currently planning on PoCing something with Redis and Socket.io
with GKE for scale

**Comment by BenAHammond** [comment]
Its working out great, I think I have my new backend.

Thanks for the help!

**Comment by mesqueeb** [comment]
What’d you go for? Can you now not use Vuex Easy Firestore anymore?
If it’s not too difficult i can look in your back end’s docs and check if I could add it to this library or not. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BenAHammond** [comment]
Just raw socket.io and redis at the moment, with a function to spit out
generic models and a little bit of wiring to my vuex state.

I pondered migrating over but the Redis backend gives me a lot, lot more
options for data storage and retrieval than maps to the current api. I'm
planning on leveraging all of their robust data api instead of having to
build that into my front end with Firebase's generic store.
