### ISSUE TITLE
Opening an already open db connection

### ISSUE THREAD

**Issue by coolhand79** [mesqueeb/vuex-easy-firestore#152]
Is there a way to know if a db connection is already open? Or, a way to prevent reopening?

I have race a condition where I open a certain route opens a db connection, then patches it. Immediately after patch, it redirects to another route. The next route calls openDBConnection on the same module. Since it happens in such quick succession, the recently patched data is not available yet :( Of course, I can test some of the state data to determine if it's been populated, but it seems there should be some internal way to do this. :)

**Comment by mesqueeb** [comment]
If you do not need to keep your connections open you should use fetchAndAdd 

There is also currently not a built in way to check for open connections through openDBChannel, however fetchAndAdd has this built in. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by coolhand79** [comment]
I understand what you're saying. However, I have a number of modules that I need to open and close depending on the user's state. It's fairly complex, so when their state changes, I may or may not know if the module is open or not. 

Is there no internal flag to identify if the connection is open?

**Comment by mesqueeb** [comment]
Not atm. For now i would save your own custom flag somewhere in your state.

I will make this functionality somewhere over the next couple of weeks as it’s related to open issue #71 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mesqueeb** [comment]
Hi @coolhand79 
I have just pushed version `1.30` where I have made it so `openDBChannel` cannot be executed twice.

Please open your DBChannel like so:
```js
  try {
    await store.dispatch('multipleOpenDBChannels/openDBChannel')
  } catch (e) {
    console.error(e)
  }
```
If something was already open with the same where / orderBy or pathVariables, you'll get an error.

If it is ok for you, please close this issue! ♡

<sub>--<br>Vuex Easy Firestore was made with ♥ by Luca Ban.<br>If this library helped you in any way you can support me by buying me <a href="https://www.buymeacoffee.com/mesqueeb">a cup of coffee</a>.</sub>

**Comment by coolhand79** [comment]
Thanks @mesqueeb - this works to prevent the re-opening. 

However, I still have to manage a flag in my state to know if it's open and with what params. I'd love to be able to manage that on the module itself. Something like 

```javascript
if (!store.state.myModule.channelIsOpen) {
    try {
        await store.dispatch('myModule/openDBChannel')
    } catch (e) {
        console.error(e)
    }
}

```

**Comment by mesqueeb** [comment]
@coolhand79 Thanks for your comment.

You can check which channels are open by doing
```js
console.log(Object.keys(store.state._sync.unsubscribe))
```
This shows all openDBChannels. Remember, one module could have many channels open with different `where` filters or pathVariables etc.

an example of an identifier key could look like:
- `[where]lists.inbox,==,true[orderBy][pathVariables]{}`

or in the case there is no `where`, no `orderby` and no `pathVariables` it will look like:
- `[where][orderBy][pathVariables]{}`

My final note to you is, that when you dispatch openDBChannel it just checks for if it's already open or not in a similar way, **so you really don't have to manually check**. Why do you want to do a manual check?

If you just want to prevent to show an error you can do so by:
```js
 try {
        await store.dispatch('myModule/openDBChannel')
    } catch (e) {
        // console.error(e)
        // don't show an error : D
    }
```

**Comment by mesqueeb** [comment]
@coolhand79 could you provide some more information on **why you'd like to manually check which channels are open with which params?**

**Comment by louisameline** [comment]
We lack information here but it sounds like there is a bad pattern in the OP's way of doing things. There probably is something to reconsider in the app.
If the OP can't refactor at this point, at least he will now be able to know if the channel is open thanks to the `streaming` wrapped promise which is going to be available when #278 is merged.
I think this can be closed now.

**Comment by louisameline** [comment]
Ok, so @coolhand79 you now have a promise at your disposal when opening a channel, to know when it will close. The doc has been updated in this regard. Thank you

**Comment by mesqueeb** [comment]
@coolhand79 feel free to reach out if you don't 100% understand the new possibilities. I will try to give additional information and examples. 😉

**Comment by mesqueeb** [comment]
@coolhand79 If a channel is already open on openDBChannel, it no longer throw an error in the latest version. The promise just resolves right away. I don't believe this will cause any issue, but let me know if it does!
