### ISSUE TITLE
[planned feature] load by id / fetch by id

### ISSUE THREAD

**Issue by razbakov** [mesqueeb/vuex-easy-firestore#153]
Why would you need 2 types of vuex modules? I am having a problem with that approach.
I would rather have only collection and have an additional method `loadById`:

```js
async loadById ({ commit, state, getters, dispatch }, id) {
  if (!id) {
    return
  }
  if (state.collection[id]) {
    return
  }

  const doc = await firestore.collection(config.firestorePath || generatedConfig.firestorePath).doc(id).get()
  if (doc.exists) {
    const data = getters.cleanUpRetrievedDoc(doc.data(), doc.id)
    commit('INSERT_DOC', data)
  }
}
```

If document was already loaded you can just check in the state.

**Comment by mesqueeb** [comment]
The doc mode is for purposes of having a single doc always synced to a Firestore doc, eg. a "user settings page"

Lead by ID is a completely new approach that I have personally never needed. Could you elaborate a bit more on your use case so I can understand why you would need this? 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mesqueeb** [comment]
@razbakov I don't understand why you'd need a loadById function. Please tell me more about your use case. 

You could work with a single document like so:
```js
const myModule = {
  firestorePath: 'userSettings/{id}',
  firestoreRefType: 'doc',
  moduleName: 'userSettings',
  statePropName: 'data',
}
```
And then get the doc by doing:
```js
dispatch('userSettings/openDBChannel', {id: 'someId'})
```
Then you can close and open the channel again with a different ID to switch the data.

Or you could use a collection and keep on fetching and adding documents with different id's:
```js
const myModule = {
  firestorePath: 'userSettings',
  firestoreRefType: 'collection',
  moduleName: 'userSettings',
  statePropName: 'data',
}
// and keep on dispatching fetchAndAdd whenever needed:
dispatch('userSettings/fetchAndAdd', {where: [['id', '==', 'someId']]})
dispatch('userSettings/fetchAndAdd', {where: [['id', '==', 'someOtherId']]})
```

All of this is documented in the documentation. Let me know if you need any further help.

If you can explain to me why you'd need a `loadById` function, let me know. I'm all ears. 😉

**Comment by razbakov** [comment]
@mesqueeb in your example:

```
dispatch('userSettings/fetchAndAdd', {where: [['id', '==', 'someId']]})
```

you suppose that there is an `id` property in document, but I need id of the document.

I need this functionality to build the following:

Let's say we have a chat:

```js
users = {
  alex: {
    name: 'Alex',
    city: 'Munich'
  },
  mesqueeb: {
    name: 'mesqueeb',
    city: 'Earth'
  }
}

chats = {
  uids: {
    alex: true,
    mesqueeb: true
  },
  messages: [
    {
      createdAt: '2018-02-13 11:55:00',
      author: 'alex',
      body: 'message',
      seen: {
        mesqueeb: '2018-02-13 11:57:00'
      }
    }
  ]
}
```

So I want to load chat messages and then lazy-load user information later one-by-one. 

```
<chat-message :user="getUser(message.author)" :message="message.body"

```js
function getUser(id) {
   if (!state.collection[id]) {
      dispatch('users/loadById', id)
   }
   return state.collection[id]
}
```

**Comment by mesqueeb** [comment]
@razbakov I see what you mean. However, the thing is, vuex easy firestore automatically saves the document id of every document onto the document as well. So if you use this library to patch/save users in your users collection, they will also have their document ID saved as a property `id`.

I do this exactly for cases like yours. So I still think you could change your `getUser` function syntax to use functions from my library like so:

```js
// your user module would look like
const users = {
  firestorePath: 'users',
  firestoreRefType: 'collection',
  moduleName: 'users',
  statePropName: 'data',
}

// and your getUser function would be
function getUser (id) {
  const user = state.users[id]
  if (!user) {
    dispatch('users/fetchAndAdd', {where: [['id', '==', id]]})
    return null
  }
  return user
}
```

**Comment by mesqueeb** [comment]
@razbakov I had a thought about this case and I decided I will add a fetchById function with the following syntax:
```js
dispatch('users/fetchAndAdd', {id: 'some-id'})
```
Currently the params you could pass fetchAndAdd are
- `where`
- `orderBy`
- firestorePathParams
- and I'll add `id` which accepts a string to get a single doc by ID.

Please note this would only be possible with `firestoreRefType: 'collection'` because 'doc' mode just uses the doc you configure in the `firestorePath`.

**Comment by mesqueeb** [comment]
@razbakov I have added a `fetchById` action!
See the [release notes](https://github.com/mesqueeb/vuex-easy-firestore/releases/tag/v1.33.0) here.

**Comment by razbakov** [comment]
Thank you!

**Comment by mesqueeb** [comment]
---
After about two years of open source, I finally got accepted for Github Sponsors!

#### 💜 [github.com/sponsors/mesqueeb](https://github.com/sponsors/mesqueeb) 💜 

A little about me:
- I love open-source
- 6 months ago I got a son, and am trying to be an awesome father 😅
- I'm doing freelance work here and there as my main job

#### If anyone was helped with vuex-easy-firestore, **I'd greatly appreciate any support**!

> BTW, donations get's paid DOUBLE by GitHub! (they're alchemists... 🦾)

Going forward 👨🏼‍💻
- I got great plans for the future of vuex-easy-firestore going above and beyond!! Look forward to it!!
- On to many more years of open-sourcing! 🎉
