### ISSUE TITLE
Loaded state

### ISSUE THREAD

**Issue by razbakov** [mesqueeb/vuex-easy-firestore#155]
Please add `loaded` state property which shows if `fetch` method was triggered at least once.

**Comment by mesqueeb** [comment]
@razbakov I have thought about this. (sorry it took so long) but realised that it's better for you to use the actual fetch history which is saved in the state.

Check this line: https://github.com/mesqueeb/vuex-easy-firestore/blob/master/src/module/actions.ts#L220

```js
state._sync.fetched[identifier] = {
  ref,
  done: false,
  retrievedFetchRefs: [],
  nextFetchRef: null
}
```

You can see that during each fetch call I save which part was fetched at `state._sync.fetched`.
- if that is an empty object nothing was fetched yet
- if it is not an empty object something was fetched already

PS: Please also see #142  on how to clear the fetch history.

If this solves what you wanted to do, please close this thread!

<sub>--<br>Vuex Easy Firestore was made with ♥ by Luca Ban.<br>If this library helped you in any way you can support me by buying me <a href="https://www.buymeacoffee.com/mesqueeb">a cup of coffee</a>.</sub>

**Comment by mesqueeb** [comment]
I'm gonna close it for now. But feel free to continue the discussion!

I've added this part to the bottom of the [fetching documentation](https://mesqueeb.github.io/vuex-easy-firestore/query-data.html#fetching-docs):
> If you require to know **wether or not fetch was called at least once**, you can do so by looking at the the state prop called `state._sync.fetched` of your module. If this is an empty object, fetch was not yet triggered. If it has data inside you know fetch has been called at least once.

<sub>--<br>Vuex Easy Firestore was made with ♥ by Luca Ban.<br>If this library helped you in any way you can support me by buying me <a href="https://www.buymeacoffee.com/mesqueeb">a cup of coffee</a>.</sub>
