### ISSUE TITLE
[Bug] id is undefined after patch

### ISSUE THREAD

**Issue by coolhand79** [mesqueeb/vuex-easy-firestore#156]
I've encountered what I think is a bug with /patch in docmode. It appears that executing a patch results in the document's id being undefined on client-side - even though it remains on the server 

Here's my module: 
```javascript
export default {
    firestorePath: "businesses/{businessId}",
    firestoreRefType: "doc",
    moduleName: "currentBusiness",

    serverChange: {
        convertTimestamps: {
            endsAt: "%convertTimestamp%",
            startsAt: "%convertTimestamp%"
        }
    },
    sync: {
        defaultValues: {}
    }
}
```

Here's the code that results in a
```javascript
                await store.dispatch("currentBusiness/openDBChannel", {
                    businessId: "BlGqES7ImfcmaYhUdBQ3"
                });

                console.log(store.state.currentBusiness.id);// <<<<< 'BlGqES7ImfcmaYhUdBQ3' is logged

                setTimeout(async () => {
                    await store.dispatch("currentBusiness/patch", {
                        description: "test"
                    });

                    console.log(store.state.currentBusiness.id); // <<<<< undefined is logged
                }, 5000);
```

As always, HUGE props for the package. It's craze-amaze.

**Comment by stegithub** [comment]
I've this problem too.

**Comment by mesqueeb** [comment]
I fixed it in the latest version.
Please try `npm i vuex-easy-firestore@latest`
and let me know!
<sub>--<br>Vuex Easy Firestore was made with ♥ by Luca Ban.<br>If this library helped you in any way you can support me by buying me <a href="https://www.buymeacoffee.com/mesqueeb">a cup of coffee</a>.</sub>

**Comment by stegithub** [comment]
It seems fixed. Thanks for your timeliness.
Very good job.
