### ISSUE TITLE
Counters structure or automatic counters?

### ISSUE THREAD

**Issue by ctwhome** [mesqueeb/vuex-easy-firestore#157]
Hi guys, I think this is a common but IMO complex question, I just want to know how do you organize counters within the collections. Do you have kind of this structure?: 

`collection -> document -> {count:0}, subcollection -> users`

![image](https://user-images.githubusercontent.com/4195550/52532075-5f712f00-2d1f-11e9-875b-edb39134333f.png)

or what strategy do you use?
 is there something that `vuex-easy-firestore` could provide out of the box?

**Comment by ctwhome** [comment]
I am thinking of another possibility, just adding a custom document within the root collection for the count?
![image](https://user-images.githubusercontent.com/4195550/52538816-76dc0680-2d77-11e9-847e-edb313737ac5.png)

**Comment by mesqueeb** [comment]
Either wil do, shouldn't be too hard to implement as well! If you wanna try your hand at it feel free to pr! 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mesqueeb** [comment]
I feel the first method is better. As the second might cause unexpected behaviour when retrieving all docs. For the first method we can easily patch the collection's parent doc on each insertion or deletion.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ctwhome** [comment]
Well reading here in stackoverflow, https://stackoverflow.com/a/54490290 it says that to return the length of the collection only will cost one read.
```
var collectionSize = await admin.firestore()
.collection(collectionName)
.listDocuments()
.then(val => {
    return val.length
})
```

It is possible to listen for changes in the query (https://firebase.google.com/docs/firestore/pricing#operations) but I don't really understand the part in the docs when it says "Also, if the listener is disconnected for more than 30 minutes (for example, if the user goes offline), you will be charged for reads as if you had issued a brand-new query." isn't the listener closed when the app/website is closed?

**Comment by mesqueeb** [comment]
I gotta think of a way I could add this without bloating the library.

**Comment by louisameline** [comment]
Hi, I do not think it's the job of Vuex-easy-firestore to count documents when Firestore themselves provide no dedicated method, so this issue should unfortunately be closed and reopened if it ever changes.

There is a video made by Firestore themselves (not sure which one anymore) that talks about a couple ways to do this, including one using a cloud function.

**Comment by louisameline** [comment]
Feel free to comment here again if there is new information on this matter. Thank you.

**Comment by ctwhome** [comment]
hi, yes I see that If Firestore doesn't do it itself, why would this package?
I thought it could be a nice addition, due to the great enhancements this package brings, vs using 'raw' firebase.

I find it quite annoying this missed feature in Firestore, I do think it is essential for any DB to come with this our of the box.

**Comment by mesqueeb** [comment]
@ctwhome please keep this feature in your mind. When we announce version 2 we plan to make it very "pluggable" with community plugins. More details will come soon, but this could be a great first community plugin!! I'm counting on you 😉

**Comment by ctwhome** [comment]
So community plugins? wow! that's amazing to know. I can't wait for the v2 and If I can do anything I will!
