### ISSUE TITLE
[TS] Types for where in config not correct

### ISSUE THREAD

**Issue by aronsuarez** [mesqueeb/vuex-easy-firestore#161]
First, this is great tool!

I have found a type error, when i setup a where filter in the initial config is the where type "string[][]" this doesn't work when a boolean or number is present.

```
sync: {
    where: [
      // This gives a type error
      ['analyses_completed', '==', false],
      // This works
      ['analyses_completed', '==', 'false'],
    ],
    debounceTimerMs: 1000,
  },
```

**Comment by mesqueeb** [comment]
You are right. Changed it to `any[][]` will push minor update on this soon.

**Comment by mesqueeb** [comment]
I fixed it in the latest version.
Please try `npm i vuex-easy-firestore@latest`
and let me know!
<sub>--<br>Vuex Easy Firestore was made with ♥ by Luca Ban.<br>If this library helped you in any way you can support me by buying me <a href="https://www.buymeacoffee.com/mesqueeb">a cup of coffee</a>.</sub>

**Comment by mesqueeb** [comment]
---
After about two years of open source, I finally got accepted for Github Sponsors!

#### 💜 [github.com/sponsors/mesqueeb](https://github.com/sponsors/mesqueeb) 💜 

A little about me:
- I love open-source
- 6 months ago I got a son, and am trying to be an awesome father 😅
- I'm doing freelance work here and there as my main job

#### If anyone was helped with vuex-easy-firestore, **I'd greatly appreciate any support**!

> BTW, donations get's paid DOUBLE by GitHub! (they're alchemists... 🦾)

Going forward 👨🏼‍💻
- I got great plans for the future of vuex-easy-firestore going above and beyond!! Look forward to it!!
- On to many more years of open-sourcing! 🎉
