### ISSUE TITLE
third sister plugin: When would vuex-easy-firebase-auth be out? 

### ISSUE THREAD

**Issue by Dinibewerbig** [mesqueeb/vuex-easy-firestore#167]
You were talking about working on it in an earlier post. Thanks for your answer.

**Comment by mesqueeb** [comment]
Hi! Thanks for your message!
I have thought long about authentication, and I have about 4 small web & cordova apps all using a single "auth" vuex module with all the authentication logic.

I realised, authentication requirements can be so different from project to project, it's difficult for me to come up with what a streamlined package should look like. 😅

What would you like to see in a vuex-easy-firebase-auth package?
Are there any specific default actions you'd love to have?

**Comment by Dinibewerbig** [comment]
Hi! Thanks for your reply! 

I am a newbie and don't much about authentication yet. I only want the standard sign-up, login page with e-mail, google and facebook login and I wanted it integrated into my website and not as a pop-up. Very basic stuff so I am sure I can figure it out myself. Also I use Nuxt and nuxt generate, so your plugin wouldn't probably be much of a help, I assume. It's just your plugins look very professional and before I implement something myself I always check what smarter people than myself have come up with. Just wanted to check that out. Thank you though, you are very very kind.

**Comment by Dinibewerbig** [comment]
I have just found something very similar... https://github.com/james2doyle/nuxt-firebase-auth which sort of works for me know...  It works also fine with nuxt generate as a static generated deployment, which is important to me, because I want to use static hosting for economical reasons.  This guy has had the same issue... having to rebuild authentication everytime from scratch. So he created this codebase. Only thing which bugs me, that he is using vuexfire. But I will eventually replace it with your vuex-easy-firebase, which sort of does the same. What would also be nice having  is :  routing to individual private user pages after being authenticated. Just the routing logic. From a newbie perspective I feel everybody anyway needs these basic things in every app. And authentication with firebase will stay the same, so a plugin could offer all the different login options and some routing options, but I am a newbie, and don-t know if that makes much sense. Anyways, cheers, and keep up your awesome work!

**Comment by louisameline** [comment]
Hi! It's good to know that there is interest in a lib for Firebase Auth, and thank you for the references.
This is out of scope here however, this issue can probably be closed so we can focus on Firestore issues :)
