### ISSUE TITLE
How to catch errors on set/insert/patch

### ISSUE THREAD

**Issue by halloway** [mesqueeb/vuex-easy-firestore#168]
First of all...VUEX-EASY-FIRESTORE is awesome!
I am wondering how to catch errors when they happen whilst loading, setting or updating data.
I can see in the console of the browser for instance that an error is shown if there are missing permissions as security rules are blocking access for Firebase.
Would be great to know where to access those error in code so the UI can be updated to inform the user what is going on.
Example below:

```
const homeModule = {
    firestorePath: '/home/welcome',
    firestoreRefType: 'doc', // or 'doc'
    moduleName: 'homeModule',
    statePropName: 'data',
    namespaced: true, // automatically added
    // you can also add your own state/getters/mutations/actions
}
```

      this.$store.dispatch("homeModule/set", {
        text: text,
        weather: weather
      })

I tried it this way.
```
      this.$store.dispatch("homeModule/set", {
        text: text,
        weather: weather
      }).catch(e => {
          console.log('My Error:' + e)
       )
```

Cheers

**Comment by mesqueeb** [comment]
Hi.
There is indeed no possibility to catch errors.

The reason is because how I implemented sync:
- I created an object (which I called the "syncstack") in which I collect patches/inserts/deletions. 
- Each insert/patch adds the change to the syncstack and then resets a timer.
- If the timer has run for 1000ms without new changes to the syncstack it will commence a batch sync.

I'm not sure how I could return or pass on errors from these sync errors to the insert or patch action calls, since they're basically not linked...

I'm personally seeing Firestore errors in my console.log and make sure there won't be any on the client! XD but indeed this is not an ideal approach...

If you have any advice for me let me know!

**Comment by halloway** [comment]
Currently I don't have any advise.
Of course it makes sense to make sure there are no error but they can
always happen due to things which can't be controlled.

Am Di., 26. Feb. 2019 um 00:55 Uhr schrieb Luca Ban <
notifications@github.com>:

**Comment by klauserber** [comment]
Hi, I have a similar problem right now when I try to patch a doc when it is already delete. This can happen any time in a multi user system.

I think it would be nice to have a global error handler, where we can deal with this sort of problems. In most cases, we simply have to inform the user, that something was going wrong.

And... thank you for the great piece of Software :-)

**Comment by louisameline** [comment]
As far as I'm concerned, I was expecting dedicated hooks for errors. I can't wrap my head around the idea that there could be sync errors that the app will never know and that it will keep on working as if everything was alright, thus generating more errors. Optimistic UI updates are ok, but not ignoring errors altogether. The library looks great overall, congratulations and thanks! But this might be a deal breaker for me for the time being

**Comment by mesqueeb** [comment]
@louisameline I'd be more than happy if you could help me add this feature by looking at my source code and working on a PR, of course I'll guide you and can show you where the syncing process actually takes place. if then you could take the lead on making some sort of error handler I think the whole community could benefit greatly. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by louisameline** [comment]
Hi @mesqueeb I need to figure out if I'm going to use this library or not, if yes I'll take a look :)

**Comment by mesqueeb** [comment]
@louisameline go for yes! 😄  let's add this feature together, shouldn't be too hard if we work together.
My discord is `Luca Ban [Mesqueeb]#4774`

**Comment by mesqueeb** [comment]
@halloway @klauserber @louisameline 

I finished implementing the ability for any action to catch errors.
```js
// any of these:
dispatch('module/set', {id, data})
dispatch('module/patch', {id, data})
dispatch('module/insert', {data})
dispatch('module/delete', id)
// can now use:
  .then(id => console.log(id))
  .catch(e => console.error(e))
```
And also for the batch actions:
```js
// any of these:
dispatch('module/patchBatch', {doc, ids})
dispatch('module/insertBatch', docs)
dispatch('module/deleteBatch', ids)
// can now use:
  .then(ids => console.log(ids))
  .catch(e => console.error(e))
```

Please mind that before v1.35.0 this would only take a split millisecond:
```js
// even though this is a promise:
const newId = await dispatch('module/insert', newDoc)
// it gets resolved with the new ID almost immediately
```
But now it will wait for the debounce timer (1 sec by default) before it's resolved.
```js
const newId = await dispatch('module/insert', newDoc)
const newId2 = await dispatch('module/insert', newDoc)
const newId3 = await dispatch('module/insert', newDoc)
// these all get resolved when the 1 sec debounce timer finishes
```
There were further no breaking changes besides the fact that resolving this promise now takes as long as the debounce timer.
