### ISSUE TITLE
Since Quasar v1.0, Firebase Throws Exception

### ISSUE THREAD

**Issue by JasonAlanKennedy** [mesqueeb/vuex-easy-firestore#169]
Since upgrading Quasar to v1.0, Firebase throws:

>Firebase: No Firebase App '[DEFAULT]' has been created - call Firebase App.initializeApp() (app/no-app)

At:

>Exception: TypeError: 'caller', 'callee', and 'arguments' properties may not be accessed on strict mode functions or the arguments objects

The above error prevents the application from initializing (client-side).

Firebase is initialized before Vuex as a plugin in the `src/boot` directory.

All other usages of firebase and firestore works as expected other than the use of this plugin.

Quasar has determined that its how this plugin is init'd.

To implement the error; install Quasar v1.0+ and load firebase as a plugin. Then add vuex-easy-firestore as normal to the main store file.

**Comment by mesqueeb** [comment]
You can work around it by initialising Firebase before you initialise the Vuex store and then passing the Firebase dependency to vuex-easy-firestore.
Please read the [documentation here](https://mesqueeb.github.io/vuex-easy-firestore/faq.html#firebase-error-app-duplicate-service).

It works for me on Quasar V1. 😉
This is my store file:
```js
import VuexEasyFirestore from 'vuex-easy-firestore'
import FirebaseDependency from '@config/firebase'
import storeRoot from './root'
import items from '../modules/items'
import lists from '../modules/lists'
import user from '../modules/user'
import selection from '../modules/selection'
import auth from '../modules/auth'

const easyFirestore = VuexEasyFirestore([
  items, lists, user
], { logging: true, FirebaseDependency })

export default function () {
  return {
    ...storeRoot,
    modules: {selection, auth, itemGet: {namespaced: true}},
    plugins: [easyFirestore]
  }
}
```

Let me know how it goes!

**Comment by JasonAlanKennedy** [comment]
Thanx,

I didn't take the 
>Firebase Error app/duplicate-service

literally as "app **OR** duplicate-service"

**Comment by mesqueeb** [comment]
@JasonAlanKennedy No problem! Glad you got it sorted out 😊

**Comment by mesqueeb** [comment]
---
After about two years of open source, I finally got accepted for Github Sponsors!

#### 💜 [github.com/sponsors/mesqueeb](https://github.com/sponsors/mesqueeb) 💜 

A little about me:
- I love open-source
- 6 months ago I got a son, and am trying to be an awesome father 😅
- I'm doing freelance work here and there as my main job

#### If anyone was helped with vuex-easy-firestore, **I'd greatly appreciate any support**!

> BTW, donations get's paid DOUBLE by GitHub! (they're alchemists... 🦾)

Going forward 👨🏼‍💻
- I got great plans for the future of vuex-easy-firestore going above and beyond!! Look forward to it!!
- On to many more years of open-sourcing! 🎉
