### ISSUE TITLE
What is the main difference with nuxt-fire? 

### ISSUE THREAD

**Issue by troublesprouter** [mesqueeb/vuex-easy-firestore#173]
I noticed there are two similar projects. I'm new to development. What's the main difference between this project and https://github.com/lupas/nuxt-fire?

Thank you.

**Comment by mesqueeb** [comment]
The one is for Nuxt, and Vuex easy Firestore is not yet unable with Nuxt. :)

Use whichever you like best and feel free to ask me anything!! 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by troublesprouter** [comment]
Thank you. Do you mean Vuex Easy Firestore is _not_ currently compatible with Nuxt?

I am using Nuxt.

**Comment by mesqueeb** [comment]
Yes you cannot use Vuex easy Firestore with Nuxt right now. I hope to change this in the future and make it compatible!!

Because of the way Nuxt handles vuex store. :)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by troublesprouter** [comment]
Perfect. Thank you.

**Comment by mesqueeb** [comment]
---
After about two years of open source, I finally got accepted for Github Sponsors!

#### 💜 [github.com/sponsors/mesqueeb](https://github.com/sponsors/mesqueeb) 💜 

A little about me:
- I love open-source
- 6 months ago I got a son, and am trying to be an awesome father 😅
- I'm doing freelance work here and there as my main job

#### If anyone was helped with vuex-easy-firestore, **I'd greatly appreciate any support**!

> BTW, donations get's paid DOUBLE by GitHub! (they're alchemists... 🦾)

Going forward 👨🏼‍💻
- I got great plans for the future of vuex-easy-firestore going above and beyond!! Look forward to it!!
- On to many more years of open-sourcing! 🎉
