### ISSUE TITLE
Cannot delete docs with dots.in.their.ids

### ISSUE THREAD

**Issue by halabe** [mesqueeb/vuex-easy-firestore#174]
Hi - Thanks for the great package. Most of my firestore doc ids have internal.periods.  The package seems to interpret these as paths to doc properties, so when I try to delete a doc named this way, I get an error (in the DELETE_PROP function).... "Cannot delete reactive property on undefined, null, or primitive value: undefined"

Is there any workaround other than renaming all my docs?  I have a lot of them, and an iOS app in production that would be disrupted by a massive rename.

**Comment by mesqueeb** [comment]
Hi! Thanks for your post!
The entire application is build around the fact that there are dots in paths and nested props!
So I'm afraid it'll be quite impossible for me to change this. 😅

If you want you could fork the project and change the dot to something else. It won't be easy but i'm prepared to help you out if you want. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by halabe** [comment]
Thanks for the response.  I wouldn't propose changing the dots (though, I think I'd learn a lot trying!).  Instead, just one delete, could we give the caller a way to indicate that the id passed is really an id, like `dispatch('myModule/delete', id, { path: false })`  Maybe an optional options param at the end will turn out to be a place to hang other useful options?

I'll look into this myself, but I'm pretty new to this stuff.  In the meantime I'll figure out how to make my delete request directly to firestore.  Maybe a go-around-me-to-google would be a good part of the easy-firestore api as a general purpose answer to dummies like me :-)

**Comment by halabe** [comment]
FYI - That was "easy" :-)... I just added a getter to every (collection) module that returns a doc's ref, given its id.  Then I added a generic delete to my main store, like this:
```
    uneasyDelete (context, payload) {
      // delete the doc with payload.ref using firestore directly
      // easy-firestore doesn't handle doc ids with '.' dots
      return payload.ref.delete()
```
Thanks again for this **fantastic** package and your quick responses.  (I'm really enjoying learning about this stuff!)

PS - maybe the easy-firestore "go-around-to-google" feature is a just getter in each store that returns a doc ref given an id. (Is that in the package someplace?  I wrote my own).

**Comment by mesqueeb** [comment]
@halabe I'm glad you got it working.
By the way see this for another reason why you should avoid `.` in id's:
https://firebase.google.com/docs/firestore/manage-data/add-data#update_fields_in_nested_objects

Finally, if you log the getters of a vuex-easy-firestore module you'll see there's a getter called `dbRef`.
Eg. if your module is a 'collection', this DB ref will be the ref to the collection.

So you could do this:
`store.getters['myCollectionModule/dbRef'].doc(someDocId)`

**Comment by halabe** [comment]
I don't think there's any ambiguity for firestore in that case, since the parameter to the `doc` method is understood to be exclusively the doc name (which allows `.`).  It's the object parameter to `set` which may have `.` delimited key paths as the keys.

Excellent that you provide the dbRef getter.  Thanks for that tip, and again, thanks very much for this great package and your kind attention!

**Comment by mesqueeb** [comment]
@halabe I'll close this for now! But feel free to continue the discussion. 😉
