### ISSUE TITLE
convert documentReference onto object

### ISSUE THREAD

**Issue by Fulbert** [mesqueeb/vuex-easy-firestore#178]
Hi,

Thanks for this nice project. This is really useful.

I've stores with documentReference fields.
In my stores, I'd like to convert them to "literal object", containing the document itself and not the reference.

I've done this through hooks. But then I noticed that I need not only to do it in addedHook, but also modifiedHook, then insertHook, and repeat it for each documentReference fields and stores I've got. This is the exact same code, for each of them. So of course I've done a function, but still, with async function, it's verbose.

So now I've something like this : https://github.com/Fulbert/servicetask/blob/master/src/store/firestore/index.js

Did I miss something? Wouldn't it be possible to have an option to convert documentReference in literal object ? Or this should be done in the view ? If so, how (computed properties cannot be async) ?

**Comment by mesqueeb** [comment]
Hello @Fulbert 
Thanks for your issue!

I kind of understand what you mean.

First of all, as you know from the [hooks documentation](https://mesqueeb.github.io/vuex-easy-firestore/hooks.html#execution-timings-of-hooks), the hook to use on initial fetch:

<b>hook timing</b>  |  
-- | --
on `openDBChannel`<Br>and<Br>`fetchAndAdd` | `serverChange.addedHook` is executed once for each doc

Now, I'm not 100% sure of the reason that you also need to add the same hook that converts your docRef into a doc in `serverChange.modifiedHook`.

Can you please try to add this config to each module:
```js
sync: {
  guard: ['customer'],
}
```
This will basically prevent the `customer` field from syncing to the server after it's been retrieved once and converted into a document.
Then try to remove the `modifiedHook` and see if that works. 😉

### Another way

I want to say though, there must be another way. Having a single document reference on each task might seem intuitive, if you come from a SQL background, but actually retrieving this document per task is a **really bad practice**. 😭

I think Firebase will charge you a single read per retrieval of the document reference, even though every task might have the same document. 😕

In my opinion it might be better to save a "customer id" as well on each task, and retrieve a bulk of most recent used customers into a customers vuex module, then just use a getter or something to have the tasks with the actual customer attached (connecting the two modules basically).

This way you will never have multiple reads per single customer and you could do something like this inside your task Vue template, when a task is opened to retrieve the customer data:
```js
mounted () {
  const customerId = this.task.customerId
  this.$store.dispatch('customer/fetchAndAdd', {where: [['customerId', '==', customerId]]}
}
```

But I didn't look at your whole application, so I'm just speaking **theoretically**. 🧐

Also I might be wrong about how Firebase charges things, I didn't double check their docs when writing this post. 😐

<sub>--<br>Vuex Easy Firestore was made with ♥ by Luca Ban.<br>If this library helped you in any way you can support me by buying me <a href="https://www.buymeacoffee.com/mesqueeb">a cup of coffee</a>.</sub>

**Comment by mesqueeb** [comment]
Dear @Fulbert I couldn't find enough information on Firebase charges of document reads, so I asked a question [on StackOverflow here](https://stackoverflow.com/questions/55202782/does-firebase-charge-for-retrieving-docs-from-firestore-js-sdk-cache).

**Comment by Fulbert** [comment]
Thanks for your answer. I'm really new to all this, and as you said, I tried to make it like SQL. Also I didn't think how firebase will charge.

As I've an another store already filled with customers, it should be actually really easy to retrieve the data's. I'll take a look and edit my post to let you know.

**Comment by mesqueeb** [comment]
Dear @Fulbert 
Please don’t edit your original post. I think it might be useful for others who come looking here as well. 😉

I'll close this issue for now but feel free to continue the discussion below! I'll try to help as much as I can. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mesqueeb** [comment]
@Fulbert were you able to rework your architecture? 
If you check that stackoverflow question I posted earlier you'll see that every single get() is charged as a read. So even if you only have 20 different customerRefs on 500 docs, they'll charge you for 1000 reads lol. 

This means that you'll be loosing a lot of pennies to google when your app grows. 😉

I'd still keep the customerRef saved on the doc as well, might come in handy in some cases, but also save a regular customerID on there. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Fulbert** [comment]
@mesqueeb I've reworked my architecture. My first solution was definitely bad, and as I was already loading customer in an another store, it's way easier to find the customer datas in the views with the id.

Thanks for your help.

I'm now working on FCM, but then I'll try to work with cache (I'm building PWA) to reduce number of reads. By the way, openDBChannel is one read?

**Comment by mesqueeb** [comment]
@Fulbert not at all

The [docs now mention that openDBChannel uses Firestore onSnapshot](https://mesqueeb.github.io/vuex-easy-firestore/query-data.html#realtime-updates-opendbchannel).

Please carefully read the docs at the [official Firestore documentation](https://firebase.google.com/docs/firestore/query-data/listen). To my understanding, every doc that comes in via onSnapshot is charged as 1 read.

**Comment by mesqueeb** [comment]
---
After about two years of open source, I finally got accepted for Github Sponsors!

#### 💜 [github.com/sponsors/mesqueeb](https://github.com/sponsors/mesqueeb) 💜 

A little about me:
- I love open-source
- 6 months ago I got a son, and am trying to be an awesome father 😅
- I'm doing freelance work here and there as my main job

#### If anyone was helped with vuex-easy-firestore, **I'd greatly appreciate any support**!

> BTW, donations get's paid DOUBLE by GitHub! (they're alchemists... 🦾)

Going forward 👨🏼‍💻
- I got great plans for the future of vuex-easy-firestore going above and beyond!! Look forward to it!!
- On to many more years of open-sourcing! 🎉
