### ISSUE TITLE
[planned feature] Split local hooks into updateStore & updateFirestore

### ISSUE THREAD

**Issue by mesqueeb** [mesqueeb/vuex-easy-firestore#179]
Currently inside a local hook you can:
- prevent anything from happening when you do not call `updateStore`
- change the document before it gets added to the store and synced to Firebase

You cannot:
- prevent the document from syncing to Firebase but still update the vuex module
- change the document before it gets synced to firebase but **after** the vuex module is updated

I plan to **create a second hook** to change the doc before Firestore sync but after Vuex.

**EDIT:**
I finished this functionality.
Check out the [new documentation on Hooks](https://mesqueeb.github.io/vuex-easy-firestore/hooks.html).

**Comment by Mattertorian** [comment]
I look forward to this functionality. 

In our app we use luxon DateTimes to do time math. Unfortunately, creating DateTimes within the local change hooks causes firebase to throw the usual 'Custom Classes not supported' error.

Do you have a time frame for this feature? :)

**Comment by Mattertorian** [comment]
After reading through my comment I see it came off as quite demanding.

What to ask is if you are currently working on the feature. Otherwise I will take a look at it (with my admittedly noobish skills) and submit a PR 😀

**Comment by mesqueeb** [comment]
Hi @Mattertorian !!
I'm tot working on it, but it shouldn't be too hard. The key is to find where the local hook kicks in and then just making it split in two without breaking the existing hook!! 

I can work on it in about a week or so, but if you need it faster you can definitely look into it yourself. I'll help out if you get stuck!! 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Mattertorian** [comment]
I'll give it a go and see how far I can get.

**Comment by Mattertorian** [comment]
I have created a solution for the problem. However, I couldn't find a good way to implement the functionality exactly like you proposed. Instead, the hooks now have two additional function calls available, vuexUpdateFn and firestoreUpdateFn. These should be used instead of updateStoreFn in the case where the updates should be split.

What do you think of this solution. Would you prefer an approach where the functionality of updateStoreFn simply depends on the use of firestoreUpdateFn? 

As an example, `insert` looks like this now:

`insert ({state, getters, commit, dispatch}, doc) {

      const store = this
      // check payload
      if (!doc) return
      // check userId
      dispatch('setUserId')
      const newDoc = doc
      if (!newDoc.id) newDoc.id = getters.dbRef.doc().id
      // apply default values
      const newDocWithDefaults = setDefaultValues(newDoc, state._conf.sync.defaultValues)
      // define the store update
      function storeUpdateFn (_doc) {
        commit('INSERT_DOC', _doc)
        return dispatch('insertDoc', _doc)
      }
      // only commits document to vuex 
      function vuexUpdateFn (_doc) {
        commit('INSERT_DOC', _doc)
        return [_doc.id]
      }
      // only prepares document for firestore sync 
      function firestoreUpdateFn (_doc) {
        return dispatch('insertDoc', _doc)
      }
      // check for hooks
      if (state._conf.sync.insertHook) {
        state._conf.sync.insertHook(storeUpdateFn, newDocWithDefaults, store, vuexUpdateFn, firestoreUpdateFn)
        return newDocWithDefaults.id
      }
      storeUpdateFn(newDocWithDefaults)
      return newDocWithDefaults.id
    },`

**Comment by mesqueeb** [comment]
thanks for your input! I'm gonna let it sink in for tonight and come back to this tomorrow.

I think I need to make some modifications. I'll be in touch here!!

**Comment by Mattertorian** [comment]
Cool. Looking forward to it!

**Comment by mesqueeb** [comment]
@Mattertorian just finished implementing this.

You can look here how I did it:
https://github.com/mesqueeb/vuex-easy-firestore/blob/dev/src/module/actions.ts#L619

Basically the hooks will go in this order:
1. patchHook (before vuex module update & sync)
2. patchHookBeforeSync (this is after vuex module is already updated but before sync)

Now I just need to add tests and documentation and then I'll update the version and push to npm.

**Comment by Mattertorian** [comment]
That looks quite nice. I look forward to trying it. 

I will report back if I encounter any issues.

**Comment by mesqueeb** [comment]
<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mesqueeb** [comment]
@Mattertorian 
I just pushed latest version to NPM. 😉
new documentation:
https://mesqueeb.github.io/vuex-easy-firestore/hooks.html#hooks-on-local-changes

Can you please let me know if you can succeed at modifying the doc, changing that timestamp to something else inside `patchHookBeforeSync`, and then see if the VUEX store still have your original timestamp format. 🧐

You will also need to use `serverChange.addedHook` to convert the timestamp that comes from the server back to your own class. 👀

Let me know how it goes!!!!!!

<sub>--<br>Vuex Easy Firestore was made with ♥ by Luca Ban.<br>If this library helped you in any way you can support me by buying me <a href="https://www.buymeacoffee.com/mesqueeb">a cup of coffee</a>. ☕️</sub>

**Comment by Mattertorian** [comment]
Great job! I will try it out in the coming days and report back.

**Comment by Mattertorian** [comment]
@mesqueeb 
I have tried out the new functionality and it is pretty great.

One odd behavior I have encountered is with the automatically filled 'created_at' and 'created_by'.
These are not filled until the 'insertDoc' action is dispatched. This means that the doc synced to Firestore will contain the fields but the doc in the Vuex store will not. If a doc in the store is patched, the empty fields will be synced to Firestore, causing them to become blank.

Currently the behavior can be escaped by simply adding the fields manually in the hooks. 

Would you consider adding the 'created_at' and 'created_by' fields to the doc which is injected into the hooks?

Best wishes,
Mathias

**Comment by mesqueeb** [comment]
@Mattertorian you're right.
I'll have to re-arrange some code for this. I'll see if I can do this easily without having to re-write too much. 😅

I'm busy with freelance projects this week, so maybe next weekend though!!! Please hang on! 🙌🏻

<sub>--<br>Vuex Easy Firestore was made with ♥ by Luca Ban.<br>If this library helped you in any way you can support me by buying me <a href="https://www.buymeacoffee.com/mesqueeb">a cup of coffee</a>. ☕️</sub>

**Comment by Mattertorian** [comment]
@mesqueeb 
No problem. The way I see it, you might be able to add `created_at` and `created_by` to the newDoc in the insert action when you set the `id`
Until then I'll just do it manually. 

Appreciate your work!

**Comment by zv3** [comment]
@mesqueeb I have a similar use case where I use javascript `Date` objects to easily manipulate dates in the app, but need them stored as strings in a specific date format. 

I could get this working nicely by using the newly added `beforeSync` hooks but then hit another issue when I tested a batch insert, it seems like the new `beforeSync` hooks aren't used when dispatching batch operations (insert, patch), and so I was wondering if there is a way to get this working in the current version, or if you have in mind adding `beforeSync` hooks support for batch operations in the future.

Thanks much!

**Comment by mesqueeb** [comment]
Hi @zv3 in most cases you use batch actions, you can also use regular actions because they automatically get grouped and batch synced in the same way. Can you show your use case of batch actions so I can quickly show you a workaround by refactoring that to a regular action loop ?

Added another hook for beforeBatchSync would be the thing I should do, but currently I'm swamped so i won't be adding that soon. So allow me to give you a workaround you can use for the time being. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by zv3** [comment]
Hey @mesqueeb, thanks for the prompt response! I've pasted below part of the code where I use the `beforeSync` hooks and the actions that also live in the same vuex module, but I think I get the idea of what I should be doing to make up for the missing batch hooks (based on your reply), in that I can dispatch the `set` action in a loop and it would work exactly the same as if I dispatched a single `insertBatch`. Let me know!

```javascript

function onServerAddedOrModified(updateStore, doc) {
  // Transform the date string (YYYYMMDD) to a JS Date object for easy manipulation.
  updateStore({ ...doc, date: dayjs(doc.date).toDate() });
}

export default {
  firestorePath: 'items',
  firestoreRefType: 'collection',
  moduleName: 'items,
  statePropName: 'data',
  sync: {
    insertHookBeforeSync(updateFirestore, doc) {
      updateFirestore({ ...doc, date: dayjs(doc.date).format('YYYMMDD') });
    },
    patchHookBeforeSync(updateFirestore, doc) {
      updateFirestore({ ...doc, date: jsDate2LogDate(doc.date) });
    },
  },
  serverChange: {
    addedHook: onServerAddedOrModified,
    modifiedHook: onServerAddedOrModified,
  },

 ...,

  actions: {
    addItem({ dispatch }, item) {
      dispatch('set', item);
    },

    addItems({ dispatch }, items) {
      dispatch('insertBatch', items);
    }
  },
```

**Comment by mesqueeb** [comment]
@zv3 yes exactly.

In a future version (v2.0) I'm thinking of removing the batch actions, because iterating over them yourself is the exact same result.

In your case just do:
```js
addItems({ dispatch }, items) {
  items.forEach(item => dispatch('insert', item))
}
```

**Comment by zv3** [comment]
@mesqueeb Yep, have noticed that too. Awesome! Thanks so much for the help. Appreciate all the time and effort you've put into this amazing Vuex library!

**Comment by mesqueeb** [comment]
---
After about two years of open source, I finally got accepted for Github Sponsors!

#### 💜 [github.com/sponsors/mesqueeb](https://github.com/sponsors/mesqueeb) 💜 

A little about me:
- I love open-source
- 6 months ago I got a son, and am trying to be an awesome father 😅
- I'm doing freelance work here and there as my main job

#### If anyone was helped with vuex-easy-firestore, **I'd greatly appreciate any support**!

> BTW, donations get's paid DOUBLE by GitHub! (they're alchemists... 🦾)

Going forward 👨🏼‍💻
- I got great plans for the future of vuex-easy-firestore going above and beyond!! Look forward to it!!
- On to many more years of open-sourcing! 🎉

**Comment by louisameline** [comment]
I think this issue can be closed now so we can get a clearer view of what's left.

**Comment by louisameline** [comment]
As the beforeBatchSync hook will not be added and that the initial request in this issue has been addressed, I will now close this issue. Feel free to comment if there is anything else. Thank you
