### ISSUE TITLE
[Bug] arrayUnion() + multiple items

### ISSUE THREAD

**Issue by halloway** [mesqueeb/vuex-easy-firestore#183]
Got across some weird behaviour when I am trying to use arrayUnion to add data from an array to Firestore. Trying as per below:

```
const unique = ["1@1.com", "2@2.com"];
        store.dispatch("communicationModule/patch", {
          id: "feedback",
          recipients: arrayUnion(...unique)
        });
```

Only the first element of unique is added to the array of recipients.

Using the direct way without vuex-easy-firestore works as expected and both entries from the array are pushed to Firestore.

```
const unique = ["1@1.com", "2@2.com"];
db.collection("communication")
.doc("feedback")
.update({recipients: firebase.firestore.FieldValue.arrayUnion(...unique)});
```
Am I missing here something or is it simply not supported?

**Comment by mesqueeb** [comment]
Hi @halloway and thanks for your issue.
I'm so Sorry! But currently arrayUnion and arrayRemove are only compatible with 1 item per 1000ms. : S

I will try to find some time this weekend to patch it so it can support multiple items as well. PLease hold on a few more days! ( related issue: #177 )

In the meanwhile you can use this as a work around:

```js
store.dispatch('myModule/set', {recipients: arrayUnion('1@1.com')})
setTimeout(_ => store.dispatch('myModule/set', {recipients: arrayUnion('2@2.com')}), 1001)

**Comment by mesqueeb** [comment]
Hi @halloway
I fixed this issue in the latest version!
Please try `npm i vuex-easy-firestore@latest`

You can now use `arrayUnion(...unique)`!

and let me know!

If it is fixed, please close the issue! ♡

<sub>--<br>Vuex Easy Firestore was made with ♥ by Luca Ban.<br>If this library helped you in any way you can support me by buying me <a href="https://www.buymeacoffee.com/mesqueeb">a cup of coffee</a>.</sub>

**Comment by halloway** [comment]
Aloha.

Works like a charm now. Thanks for the swift fix!

**Comment by mesqueeb** [comment]
---
After about two years of open source, I finally got accepted for Github Sponsors!

#### 💜 [github.com/sponsors/mesqueeb](https://github.com/sponsors/mesqueeb) 💜 

A little about me:
- I love open-source
- 6 months ago I got a son, and am trying to be an awesome father 😅
- I'm doing freelance work here and there as my main job

#### If anyone was helped with vuex-easy-firestore, **I'd greatly appreciate any support**!

> BTW, donations get's paid DOUBLE by GitHub! (they're alchemists... 🦾)

Going forward 👨🏼‍💻
- I got great plans for the future of vuex-easy-firestore going above and beyond!! Look forward to it!!
- On to many more years of open-sourcing! 🎉
