### ISSUE TITLE
Computed properties not updating after patch

### ISSUE THREAD

**Issue by c0h1b4** [mesqueeb/vuex-easy-firestore#185]
Hello,
I am using the vuex-easy-firestore with vuetifyjs and I have this data table that when I update an item/document from the table with the dispatch/patch command, the data table does not refresh. I can see the update on the firestore database but my getters/computed properties/etc don't see the update happening and don't refresh the data.
Funny thing is that if I go to the firestore directly and change the value manually, the data table updates automatically.
I tried using multiple different data sources for the data table, like getters, computed properties and methods that filter the data. And none of them refreshes after the patch is sent.
Any ideas?

Thanks,
David

**Comment by mesqueeb** [comment]
Hi david. 👋🏻
Thanks for your issue. 
Let’s get to the bottom of this!
Please share as much information on your code as you can. I can only help you once i’m able to reproduce your problem on my end so i can see what’s wrong. 

Easiest would be sharing your repo. If that’s not possible i'd need your relevant code on your Vuex module and the vue component and any other relevant code related to displaying the data. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by c0h1b4** [comment]
I will try to make a live demo of this issue tonight and will post here.

**Comment by mesqueeb** [comment]
if it's difficult to make a demo you could just post the .vue and the vuex module files here. I could start by reviewing those.

I'm pretty sure this is a basic vue / vuex reactivity problem so I mainly would have to look at your  getters and computed properties that are not re-calculated. 🌝

**Comment by c0h1b4** [comment]
Hi Mesque, I think I found the issue.

I have a table that filters all the items that doesn't have a field/property. For example, a doc that doesn't has a photo field.
When I add the photo field locally, the action to add this new field/property doesn't propagates/update the table filter. If I do this remotely, it filters.

I am almost ready making a small todo table demo that shows the issue.

I will publish the project git here this weekend.

Thanks for the help.

**Comment by mesqueeb** [comment]
Perhaps you could solve this by setting default values:
https://mesqueeb.github.io/vuex-easy-firestore/extra-features.html#default-values

This makes sure that every doc has the same prop even if the props were added later and not available on some docs on the server. Try it and let me know. ^ ^

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by c0h1b4** [comment]
Yes, you are correct. As stated on the doc:

"Also, to make sure there are no vue reactivity issues, these default values are also applied to any doc that doesn't have them that's retrieved from the server."

I believe that this is the issue here.

**Comment by mesqueeb** [comment]
Alright! So basically the rule to remember:

any time you add a new prop but some users might have docs on the server without that prop you **must** add a default value for that prop in the module sync settings. 

If this actually solved your problem please close the issue. Otherwise let’s dig deeper! 😉

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
