### ISSUE TITLE
Where and OrderBy sync

### ISSUE THREAD

**Issue by bseng** [mesqueeb/vuex-easy-firestore#186]
First of all congrats on the library!

I've got a question around where and orderby. If I want to filter some fields that is set dynamically by the user on like a dropdown list, how will that get sync back to vuex-easy-firestore?

**Comment by mesqueeb** [comment]
Thanks for your question! 😃

- OrderBy is only relevant when retrieving data and has no influence on syncing data to the server. 
- where filter is only usable with collections and a collection will always sync doc data by the doc's ID, so also no influence on syncing data to the server. 

You just gotta be carefull with changing [path variables](https://mesqueeb.github.io/vuex-easy-firestore/extra-features.html#variables-for-firestorepath-or-filters), as one module is supposed to have one path, so after you change a path variable it's better to always dispatch clearModule.

Does this answer your question? 🧐

Let me know if you run into a problem! 🙃


<sub>--<br>Vuex Easy Firestore was made with ♥ by Luca Ban.<br>If this library helped you in any way you can support me by buying me <a href="https://www.buymeacoffee.com/mesqueeb">a cup of coffee</a>.</sub>


<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mesqueeb** [comment]
I'm going to close the question for now, but if this did not solve your problem, feel free to comment below and I'll help you out!!

<sub>--<br>Vuex Easy Firestore was made with ♥ by Luca Ban.<br>If this library helped you in any way you can support me by buying me <a href="https://www.buymeacoffee.com/mesqueeb">a cup of coffee</a>.</sub>

**Comment by mesqueeb** [comment]
---
After about two years of open source, I finally got accepted for Github Sponsors!

#### 💜 [github.com/sponsors/mesqueeb](https://github.com/sponsors/mesqueeb) 💜 

A little about me:
- I love open-source
- 6 months ago I got a son, and am trying to be an awesome father 😅
- I'm doing freelance work here and there as my main job

#### If anyone was helped with vuex-easy-firestore, **I'd greatly appreciate any support**!

> BTW, donations get's paid DOUBLE by GitHub! (they're alchemists... 🦾)

Going forward 👨🏼‍💻
- I got great plans for the future of vuex-easy-firestore going above and beyond!! Look forward to it!!
- On to many more years of open-sourcing! 🎉
