### ISSUE TITLE
[Bug] docs are not added after refresh during offline mode

### ISSUE THREAD

**Issue by mesqueeb** [mesqueeb/vuex-easy-firestore#188]
Related: #187 
@nVitius

**Comment by mesqueeb** [comment]
@nVitius I pushed a fix for your problem.
I had to build a PWA on a test project of mine to make sure everything works. And according to my tests, with these changes it all works now. 😎

The main fixes I made are in the [actions.ts](https://github.com/mesqueeb/vuex-easy-firestore/commit/c849d88993afd18cd75556f2049cbdf73ccfa272#diff-e27111d9aabef5fb717e074ee7fbe1c8) file. You can check with the link.

Please install the latest version and let me know! 🙃

<sub>--<br>Vuex Easy Firestore was made with ♥ by Luca Ban.<br>If this library helped you in any way you can support me by buying me <a href="https://www.buymeacoffee.com/mesqueeb">a cup of coffee</a>.</sub>

**Comment by nVitius** [comment]
@mesqueeb I just saw your message. You can disregard the comment I left on the old PR just now. I'll test the changes. Thanks!

**Comment by mesqueeb** [comment]
---
After about two years of open source, I finally got accepted for Github Sponsors!

#### 💜 [github.com/sponsors/mesqueeb](https://github.com/sponsors/mesqueeb) 💜 

A little about me:
- I love open-source
- 6 months ago I got a son, and am trying to be an awesome father 😅
- I'm doing freelance work here and there as my main job

#### If anyone was helped with vuex-easy-firestore, **I'd greatly appreciate any support**!

> BTW, donations get's paid DOUBLE by GitHub! (they're alchemists... 🦾)

Going forward 👨🏼‍💻
- I got great plans for the future of vuex-easy-firestore going above and beyond!! Look forward to it!!
- On to many more years of open-sourcing! 🎉
