### ISSUE TITLE
[planned feature] increment

### ISSUE THREAD

**Issue by c0h1b4** [mesqueeb/vuex-easy-firestore#190]
Is it possible to have the increment function available?

https://firebase.googleblog.com/2019/03/increment-server-side-cloud-firestore.html

import { increment } from 'vuex-easy-firestore'

store.dispatch('myModule/patch', {
  id: '001',
  field1: increment(), // just add 1
  field2: increment(4), // add 4 to the field2
})

**Comment by mesqueeb** [comment]
Please hold on a couple more days, I will add this function!

<sub>--<br>Vuex Easy Firestore was made with ♥ by Luca Ban.<br>If this library helped you in any way you can support me by buying me <a href="https://www.buymeacoffee.com/mesqueeb">a cup of coffee</a>.</sub>

**Comment by mesqueeb** [comment]
Dear @c0h1b4 I finished implementing `increment`!
Please update to the latest version and check the [documentation here](https://mesqueeb.github.io/vuex-easy-firestore/firestore-fields-and-functions.html#increment).

**Comment by c0h1b4** [comment]
Perfect!
You rule.

**Comment by mesqueeb** [comment]
---
After about two years of open source, I finally got accepted for Github Sponsors!

#### 💜 [github.com/sponsors/mesqueeb](https://github.com/sponsors/mesqueeb) 💜 

A little about me:
- I love open-source
- 6 months ago I got a son, and am trying to be an awesome father 😅
- I'm doing freelance work here and there as my main job

#### If anyone was helped with vuex-easy-firestore, **I'd greatly appreciate any support**!

> BTW, donations get's paid DOUBLE by GitHub! (they're alchemists... 🦾)

Going forward 👨🏼‍💻
- I got great plans for the future of vuex-easy-firestore going above and beyond!! Look forward to it!!
- On to many more years of open-sourcing! 🎉
