### ISSUE TITLE
Add an example using Typescript?

### ISSUE THREAD

**Issue by garyo** [mesqueeb/vuex-easy-firestore#191]
This looks like a really useful module! I'm not sure how to use it with my Vuex typescript module though.

Here's my Typescript Vuex module. When I try to compile it, it says `Module<ProjectState, RootState>` doesn't have property `firestorePath`.

```typescript
import { Module } from 'vuex'
import { RootState, ProjectState } from './types'

export const state: ProjectState = {
  questionAnswers: {},
}

export const project: Module<ProjectState, RootState> = {
  firestorePath: 'users/{userId}/projects',
  firestoreRefType: 'collection',
  moduleName: 'project',
  statePropName: 'data',
  namespaced: true,
  state,
  getters: {
  },
  mutations: {
    /* tslint:disable:no-shadowed-variable */
    answerQuestion(state, {questionId, answer}) {
      state.questionAnswers[questionId] = answer
    },
  },
  actions: {
    answerQuestion(context, {questionId, answer}) {
      context.commit('answerQuestion', { questionId, answer })
    }
  },
}

export default project
```

**Comment by garyo** [comment]
I added a `vuex-easy-firestore.d.ts` to get around that:
```typescript
import { Module } from 'vuex'

declare module 'vuex/types/index' {
  export interface Module<S, R> {
    firestorePath: string
    firestoreRefType: string
    moduleName: string
    statePropName: string
  }
}
```
and now it does actually compile.

**Comment by mesqueeb** [comment]
@garyo Yes, if you use TypeScript you'll have to somehow use the types used by my library. Seems like you did it correctly! 🙃

<sub>--<br>Vuex Easy Firestore was made with ♥ by Luca Ban.<br>If this library helped you in any way you can support me by buying me <a href="https://www.buymeacoffee.com/mesqueeb">a cup of coffee</a>.</sub>

**Comment by mesqueeb** [comment]
---
After about two years of open source, I finally got accepted for Github Sponsors!

#### 💜 [github.com/sponsors/mesqueeb](https://github.com/sponsors/mesqueeb) 💜 

A little about me:
- I love open-source
- 6 months ago I got a son, and am trying to be an awesome father 😅
- I'm doing freelance work here and there as my main job

#### If anyone was helped with vuex-easy-firestore, **I'd greatly appreciate any support**!

> BTW, donations get's paid DOUBLE by GitHub! (they're alchemists... 🦾)

Going forward 👨🏼‍💻
- I got great plans for the future of vuex-easy-firestore going above and beyond!! Look forward to it!!
- On to many more years of open-sourcing! 🎉
