### ISSUE TITLE
[NUXT] Default site setting to sync when loggedIn

### ISSUE THREAD

**Issue by BaptisteCool** [mesqueeb/vuex-easy-firestore#193]
Hi, Great JOB, I will love it soon (^_^)

I have juste a problem to set some default value witch i want to sync to the users/{userId} when loggedIn

> [vuex-easy-firestore] error trying to set userId.
>  Try doing `dispatch('module/setUserId', userId) before openDBChannel or fetchAndAdd.`

OR 
[vuex] do not mutate vuex store state outside mutation handlers.

Example i have : 
```
// in my component
computed: {
    drawerTemporary: {
      get() {
        return this.$store.get('userData/drawerTemporary')
      },
      set(newValue) {
        this.$store.set('userData/drawerTemporary', newValue)
      }
    },
}
// in module
firestorePath: 'users/{userId}',
  firestoreRefType: 'doc', // or 'doc'
  moduleName: 'userData',
  statePropName: 'data',
  namespaced: true, // automatically added

  sync: {
    debounceTimerMs: 2000, // defaults to 1000
    defaultValues: {
      drawerTemporary: true
    }
  }

in plugin when i set user after OnStateChange(user => { if(user) dispatch('setUser', user) })
  async setUser({ commit }, user) {
    await commit('setUser', user)

    await $nuxt.$store.dispatch('userData/openDBChannel').catch(console.error)
  },
```

Has you can see, i use Nuxt 2.5

How is it possible to sync only when retrieve data from user/{userId} ?

Thanks.

**Comment by mesqueeb** [comment]
Hi!
The library is not supporting NUXT. There are several SSR issues that I don't know how to work around, especially since I don't use SSR.
(Also see open issues: #66 #124 #159)

Further, specific to your problem, it seems to me you are trying to retrieve data for a module before you are authenticated via Firebase Auth via their JS SDK?

At the point where you do:
```js
await $nuxt.$store.dispatch('userData/openDBChannel').catch(console.error)
```
you should check if your `firebase.auth().currentUser` exists or not.
1. if at this point you have no currentUser, you need to authenticate the firebase SDK
2. if you do have a currentUser, try [passing the Firebase dependency](https://mesqueeb.github.io/vuex-easy-firestore/extra-features.html#pass-firebase-dependency) as described
3. if it still doesn't work, it's a problem with NUXT and I currently don't have to recourses to make it compatible with NUXT. 😕

Let me know how it goes! 🙃

**Comment by BaptisteCool** [comment]
Ok, Thank for answer. I will try special conditional getter and setter if user is loggedIn.

**Comment by BaptisteCool** [comment]
Get data is possible but i have issue with set.
I should try again later. Maybe i'm missing something.

I'm waiting a nuxtjs compatibility (^_^).

**Comment by mesqueeb** [comment]
I will close this issue in favour for the other three issues I linked above. And I'll also post here when there's ever a PR with NUXT compatibility!

Feel free to continue the discussion below. 🙃

<sub>--<br>Vuex Easy Firestore was made with ♥ by Luca Ban.<br>If this library helped you in any way you can support me by buying me <a href="https://www.buymeacoffee.com/mesqueeb">a cup of coffee</a>.</sub>

**Comment by stact** [comment]
Hey :)
any roadmap for Nuxt compatibility?

**Comment by mesqueeb** [comment]
Hi! 
No I don’t think i’ll ever need Nuxt personally so...
But feel free to make a PR!!!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Mattertorian** [comment]
I have found that using Nuxt in 'spa' mode makes it compatible with module. It still works when you nuxt generate static content. 
Of course this does nothing for you if actually depend on server side rendering.

**Comment by mesqueeb** [comment]
---
After about two years of open source, I finally got accepted for Github Sponsors!

#### 💜 [github.com/sponsors/mesqueeb](https://github.com/sponsors/mesqueeb) 💜 

A little about me:
- I love open-source
- 6 months ago I got a son, and am trying to be an awesome father 😅
- I'm doing freelance work here and there as my main job

#### If anyone was helped with vuex-easy-firestore, **I'd greatly appreciate any support**!

> BTW, donations get's paid DOUBLE by GitHub! (they're alchemists... 🦾)

Going forward 👨🏼‍💻
- I got great plans for the future of vuex-easy-firestore going above and beyond!! Look forward to it!!
- On to many more years of open-sourcing! 🎉
