### ISSUE TITLE
Possible bug in docs: setPropName in doc mode

### ISSUE THREAD

**Issue by artfabrique** [mesqueeb/vuex-easy-firestore#199]
https://mesqueeb.github.io/vuex-easy-firestore/query-data.html#automatic-initial-doc-insertion
in the code sample, you have `statePropName` set to data but it's not used for `doc` mode.

**Comment by mesqueeb** [comment]
Do you mean `statePropName`?
You can set a statePropName both in collection or doc mode. Or you can set it to an empty string so it syncs directly to your module state.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by artfabrique** [comment]
Yes I mean `statePropName`.
But for some reason, all properties outside `data` property in the store are created and synced to firestore when you are in a doc mode while `statePropName` is set to "data"

**Comment by artfabrique** [comment]
maybe it's because i use vuex-easy-access as well and i call
```js
this.$store.set("myModule/loading",false)
```
and my module state is
```js
const state = {
    loading: true,
    data: {
        foo:"bar"
    }
}
````

**Comment by mesqueeb** [comment]
Yeah. So when you use vuex easy access it should take into account your `statePropName` as well. 

See here the source code where it takes into account the statePropName:
https://github.com/mesqueeb/vuex-easy-access/blob/68a94b4a9732e196b5bd63592980a92653455169/src/makeSetters.ts#L69


This means however that you cannot target properties outside of your statePropName with easy access! 🙈 do you understand?

Basically if you have a couple of options:
- use the vuex easy firestore mutation instead (recommended)
  - `commit('myModule/loading', true)
- don’t use a statePropName, then easy-access will properly target the other values as well.
  - the downside is, you’ll have to add `loading` to easy-firestore’s guard config to make sure it doesn’t get synced. 
- set up a new custom mutation or action. 


<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by artfabrique** [comment]
Thanks! I've ended up with `fillables:["data"]`!
so basically what was happening: when I was setting a loading prop a news prop was created inside data?

I now have another very strange behaviour:
as soon as I make my store module a vuex-easy-firestore one all actions in that module start to be called twice. So for example, if I do `this.$store.dispatch("myFBModule/testAction")` inside a `App.vue.created()` thre testAction simply gets called twice. And I fail to reproduce it in the clean repo to share with you..

**Comment by mesqueeb** [comment]
The new `loading` prop appears because vuex-easy-access automatically converts:
- `set('myModule/loading', true)
To:
- `dispatch('myModule/set', {data: {loading: true}})`

Therefore, you cannot use the easy-access “setter” for props outside a `statePropName` of a easy-firestore module. 

That’s why you’ll have to use one of my suggestions above and not the `set()` function. 😉


As for the actions being called twice, i’ll need more info on your code to see why. This certainly shouldn’t happen so 😅
Maybe you can just share your repo? I can look at the source how you set everything up.

**Comment by artfabrique** [comment]
@mesqueeb added you as collaborator.
yarn
yarn serve

in chrome in console you will see `SurveyData.test` called twice from App.vue.created

**Comment by artfabrique** [comment]
when I change namespaced to false action called once as expected.

**Comment by mesqueeb** [comment]
@artfabrique Did you forget to sync? Last commit is 9 days ago. `App.vue` doesn't have a `created` function ;)

**Comment by artfabrique** [comment]
oops )

**Comment by artfabrique** [comment]
@mesqueeb OH MY GOD! 5 hours.. if I add my vuex-easy-firestore enabled vuex module to the modules:{} section of the root store all actions get doubled.

**Comment by mesqueeb** [comment]
Yes.
Exactly! 😉
I just now made a PR onto your repository actually.

So any "vuex-easy-firestore" modules are added inside the plugin, and shouldn't be added directly as module to the store! 👽

**Comment by artfabrique** [comment]
Yeah ) I think maybe it should my mentioned somewhere in the docs for newbies like me 🤣

**Comment by mesqueeb** [comment]
Thanks for the advice  @artfabrique !
I've added an issue, i'll eventually get around to add a sanity check when the plugin runs.

Feel free to open any new issue when you run into a problem again! 🙃

<sub>--<br>Vuex Easy Firestore was made with ♥ by Luca Ban.<br>If this library helped you in any way you can support me by buying me <a href="https://www.buymeacoffee.com/mesqueeb">a cup of coffee</a>.</sub>
