### ISSUE TITLE
warn devs to not pass VEF-modules directly to store modules

### ISSUE THREAD

**Issue by mesqueeb** [mesqueeb/vuex-easy-firestore#200]
Should do a sanity check when the plugin runs.
---
<sub>
After about two years of open source, I finally got accepted for Github Sponsors!

#### 💜 [github.com/sponsors/mesqueeb](https://github.com/sponsors/mesqueeb) 💜 

A little about me:
- I love open-source
- 6 months ago I got a son, and am trying to be an awesome father 😅
- I'm doing freelance work here and there as my main job

#### If anyone was helped with vuex-easy-firestore, **I'd greatly appreciate any support**!

> BTW, donations get's paid DOUBLE by GitHub! (they're alchemists... 🦾)

#### Going forward 👨🏼‍💻
- I got great plans for the future of vuex-easy-firestore going above and beyond!! Look forward to it!!
- On to many more years of open-sourcing! 🎉
</sub>

**Comment by mesqueeb** [comment]
#199

**Comment by mesqueeb** [comment]
✅ Docs are updated
https://github.com/mesqueeb/vuex-easy-firestore/commit/5c1842b512bbdc4102aa5523e3fd7157c04590f0#diff-85ad37f4d4d62ce0f24ea8a26b95ba09

Now just a sanity check

**Comment by louisameline** [comment]
I'll close this as I think it's obvious now and we can focus on the next version
