### ISSUE TITLE
Do not mutate vuex store state outside mutation handlers

### ISSUE THREAD

**Issue by codegrue** [mesqueeb/vuex-easy-firestore#201]
Whenever I perform a single patch action, for example:

`this.$store.dispatch("mystore/patch", { id: id, type: value });`

I immediately get **9** of these errors every time. Any idea what could cause this?

```
[Vue warn]: Error in callback for watcher "function () { return this._data.$$state }": "Error: [vuex] do not mutate vuex store state outside mutation handlers."

Error: [vuex] do not mutate vuex store state outside mutation handlers.
```

Note: even with the errors, firestore is updated successfully as intended.

**Comment by mesqueeb** [comment]
Yes, it's because my library is not (yet) compatible with strict-mode.
Please remove `strict` from your vuex settings (whenever you want to use vuex-easy-firestore modules).

Please see #111 for more information on this.

**Comment by mesqueeb** [comment]
I'll close this issue in favour of #111 so be sure to "subscribe" to that thread to follow the progress. 😉

**Comment by codegrue** [comment]
Curious, does this mean with Strict mode off, I could directly v-model bind to a vuex (i.e. Firebase) property?

**Comment by mesqueeb** [comment]
I’m personally not a fan of strict mode. It’s like giving a chicken wings but taking away its ability to fly...

It’s like forcing students to have the same opinion than a teacher. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
