### ISSUE TITLE
Is there a pattern for using v-model?

### ISSUE THREAD

**Issue by codegrue** [mesqueeb/vuex-easy-firestore#203]
Assuming I have a field that I want immediately bound to the database bi-directionally, is there a way to do this cleanly? This is what I have done using a computed property and it's a good chunk of (repetitive) code to have for each bound value:

```
  <v-text-field v-model="name" label="Name"></v-text-field>

  ...

  data: function() {
    return {
      item: null,
    };
  },
  created() {
    const id = this.$route.params.item_id;
    this.item = this.$store.getters["items/item"](id);
  },
  computed: {
    name: {
      set(value) {
        this.$store.dispatch("items/patch", { id: this.item.id, name: value });
      },
      get() {
        return this.item.name;
      }
    }
  }
```

Edit: One issue with this above technique is database changes don't seem to trigger the "get" and thus a data change in the bound control.

**Comment by mesqueeb** [comment]
Hi @codegrue 👋🏻 
I use this pattern myself sometimes as well ^^

You’re close!! The setter is correct but for the getter just reference the state value of your store. 
  
return this.$store.state.moduleName.statePropName[this.item.id]

You see this is a simple vue reactivity issue, you set the item once on created, but then keep on showing the outdated value. 

That getter you use in the created hook is a single function call so it looses reactivity afterwards. 😉 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
