### ISSUE TITLE
Equivalent of .first() on a collections's data

### ISSUE THREAD

**Issue by codegrue** [mesqueeb/vuex-easy-firestore#205]
Given `this.$store.state.module.data`, how would one grab the first item from this collection? In particular, I need the firestore Id of this first item. Tried:

```
this.$store.state.module.data[0] <- undefined

this.$store.state.module.data.limit(1) <- limit is not a function
```

I can see with console.log that I have an observable with multiple Id's, but I just can't seem to access it like an array.

**Comment by mesqueeb** [comment]
The data is saved in an object, so you can only access the items by id. 

You can easily convert this to an array by setting up a getter that does `return Object.values(state.data)`

However be careful as the array might have a different order in different browsers. To have an ensured order you need to write your own array sort logic and add this to the same getter. 😉

If this helped you let me know and close the issue!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by codegrue** [comment]
When I do `return Object.values(state.data)` I get an array of size 0. Even though I can see in state that the collection is not empty.

**Comment by mesqueeb** [comment]
Can you post the code of your entire module?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by codegrue** [comment]
```
const engines = {
  firestorePath: "boats/{boatId}/engines",
  firestoreRefType: "collection", // or 'doc'
  moduleName: "engines",
  statePropName: "data",
  namespaced: true, // automatically added

  state: {},
  getters: {
    first: state => {
      console.log(state.data); // shows Observer with two items
      console.log(Object.values(state.data)); // shows empty array
      return Object.values(state.data)[0]; // returns undefined
    }
  },
  mutations: {},
  actions: {}
};

export default engines;


```

**Comment by mesqueeb** [comment]
That’s weird. Does it log anything if you do this in the getter?

```js
console.log(state.data.Y7t7nC9tRzHPbTSNtA1t)
```
?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by codegrue** [comment]
That produced undefined also.

**Comment by mesqueeb** [comment]
As we discussed outside of this issue.

You should change your getter to expect `state.data` it might still be still empty. Otherwise you cannot use that getter after the promise of `openDBChannel` is resolved.

```js
first: state => {
  const dataArray = Object.values(state.data)
  return dataArray.length ? dataArray[0] : null
}
```
Use something like this, and whenever you call that getter somewhere double check if you received a value.

**Comment by mesqueeb** [comment]
---
After about two years of open source, I finally got accepted for Github Sponsors!

#### 💜 [github.com/sponsors/mesqueeb](https://github.com/sponsors/mesqueeb) 💜 

A little about me:
- I love open-source
- 6 months ago I got a son, and am trying to be an awesome father 😅
- I'm doing freelance work here and there as my main job

#### If anyone was helped with vuex-easy-firestore, **I'd greatly appreciate any support**!

> BTW, donations get's paid DOUBLE by GitHub! (they're alchemists... 🦾)

Going forward 👨🏼‍💻
- I got great plans for the future of vuex-easy-firestore going above and beyond!! Look forward to it!!
- On to many more years of open-sourcing! 🎉
