### ISSUE TITLE
fetch not working with 'doc' mode

### ISSUE THREAD

**Issue by artfabrique** [mesqueeb/vuex-easy-firestore#206]
I've tried to use 
```js
dispatch("myModule/fetch", {id:"testDoc"})
````
and it seems that plugin tries to call `.limit()` in document reference and fails obviously because its not a collection.

in the module config i have
```js
firestorePath: "myModule/{docId}",
firestoreRefType: "doc",
moduleName: "myModule",
statePropName: "data",
```

**Comment by mesqueeb** [comment]
fetch is only usable with collection mode. 
Also the way you pass your path variable as `id` is wrong, it should be exactly the same prop name as you wrote in your path, so in this case `docId`. 😉

You just have to do this instead:
```js
dispatch('myModule/fetchAndAdd', {docId: 'testDoc'})
```
Try that and let me know how it goes 🙃

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by artfabrique** [comment]
> fetch is only usable with collection mode. You need to use `fetchAndAdd` instead!
Sure, I'm just giving feedback on docs and error string: https://mesqueeb.github.io/vuex-easy-firestore/query-data.html#manual-fetch-handling
it's not mentioned here that `fetch` works only with collections

**Comment by mesqueeb** [comment]
@artfabrique thanks!! I’ll update the docs ^^

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mesqueeb** [comment]
updated the [documentation](https://mesqueeb.github.io/vuex-easy-firestore/query-data.html#manual-fetch-handling) and also the library will now give an error in the console
