### ISSUE TITLE
Can I clear filters

### ISSUE THREAD

**Issue by berendsmatt** [mesqueeb/vuex-easy-firestore#210]
Hiya,
On an earlier view I open the the DB channel with a where filter. However from this view I want to open the collection as a whole. 
However it still opens with the filtered list (If the other view was visited).
     
      await this.$store.dispatch('events/closeDBChannel') // Tried , {clearModule: true}) 
      await this.$store.dispatch('events/openDBChannel')

The only workaround I've found is to add a new where filter.
Am I missing something simple?
Thanks mate

**Comment by mesqueeb** [comment]
I think that’s pretty straightforward and simple no?
- Close the current dbchannel, you dont have to clear the module per se 
- Open a new one with a new where filter or pass an empty array to where to clear them I think. 

Does this work? 🙃 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by berendsmatt** [comment]
await this.$store.dispatch('events/openDBChannel', { where: [] })
Perfect. 
For some reason I was thinking the closeDBChannel would also remove filters.

**Comment by mesqueeb** [comment]
Ah no, but i see the confusion! 
I’ll keep in mind if i can make it clearer with a next release!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
