### ISSUE TITLE
Usage of patchBatch

### ISSUE THREAD

**Issue by thokkane** [mesqueeb/vuex-easy-firestore#211]
Can you provide an example of the patchBatch function? For example if I need to update thee docs with doc specific data
{id:1,title:"Test1"},{id:2,title:"Test2"}, {id:3,title:"Test3"}
```javascript
dispatch('moduleName/patchBatch', {doc: {}, ids: []})
´´´

**Comment by mesqueeb** [comment]
patchBatch is for updating multiple ids with the same content. In your case, you can just execute single patch calls directly after each other. they will be synced together anyway so you won’t loose performance!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by thokkane** [comment]
The thing is i'd like to use patchBatchHook. Now it will trigger the patchHook for each update, which triggers unnecessary runs of the same code.

Any chance you could add patchBatch with seperate content for the ids?

**Comment by mesqueeb** [comment]
@thokkane I see. Can you please elaborate a little bit on your use case for the `patchBatchHook`, so I can decide if the use case is common enough or present you with a manual workaround.

**Comment by thokkane** [comment]
I’m building a tree out of the collection everytime an update occur to document data for that tree. When there is an update in the tree, mutliple docs need to be updated as the contextual data is in each. In patchBatchHook, it would just trigger the tree update to run once. Now patchHook is triggering the tree build four times since four docs are updated.

**Comment by mesqueeb** [comment]
You could add a simple debounce function to your patchHook. If you post your patchHook here I'll modify it with the debounce function. 😄

**Comment by thokkane** [comment]
This is what i got. Its checking if the returned doc has a property that is used for the tree build and if so it rebuilds the tree. This is now at most fired four times since up to four items may need new context data in the tee.
```javascript
patchHook: function (updateStore, doc, store) { 
            updateStore(doc)
            var updateTree = false
            typeof doc.data.context !== "undefined" ? store.dispatch('buildTree') : null
        },
```

**Comment by mesqueeb** [comment]
Here is a simple debounce helper you could use:

```js
/**
 * Debounce helper
 *
 * let wait = startDebounce(1000)
 * wait.done.then(_ => handle())
 * wait.refresh() // to refresh
 *
 * @param {number} ms
 * @returns {{done: any, refresh: () => {}}}
 */
export default function startDebounce (ms) {
  let startTime = Date.now()
  const done = new Promise((resolve, reject) => {
    const interval = setInterval(_ => {
      const now = Date.now()
      const deltaT = now - startTime
      if (deltaT >= ms) {
        clearInterval(interval)
        resolve(true)
      }
    }, 10)
  })
  const refresh = () => (startTime = Date.now())
  return { done, refresh }
}
```

Then in your hook you could do something like this:

```js
patchHook: function (updateStore, doc, store) { 
  updateStore(doc)
  if (doc.data.context === undefined) return
  if (window.debouncer) return window.debouncer.refresh()
  window.debouncer = startDebounce(1000)
  window.debouncer.then(_ => store.dispatch('buildTree'))
},
```
Do you understand? 🙃

Let me know how it goes!

**Comment by thokkane** [comment]
@mesqueeb thanks. Its working :) One line i needed to change from debouncer.then to debouncer.done.then.

**Comment by mesqueeb** [comment]
Ahhh!!! That's my typo!!! 😅 sorry

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mesqueeb** [comment]
---
After about two years of open source, I finally got accepted for Github Sponsors!

#### 💜 [github.com/sponsors/mesqueeb](https://github.com/sponsors/mesqueeb) 💜 

A little about me:
- I love open-source
- 6 months ago I got a son, and am trying to be an awesome father 😅
- I'm doing freelance work here and there as my main job

#### If anyone was helped with vuex-easy-firestore, **I'd greatly appreciate any support**!

> BTW, donations get's paid DOUBLE by GitHub! (they're alchemists... 🦾)

Going forward 👨🏼‍💻
- I got great plans for the future of vuex-easy-firestore going above and beyond!! Look forward to it!!
- On to many more years of open-sourcing! 🎉
