### ISSUE TITLE
How to detect when all docs have been fetched

### ISSUE THREAD

**Issue by thokkane** [mesqueeb/vuex-easy-firestore#212]
Does the line     if (querySnapshot.done === true)  still work? What is the best way to detect when all docs have been added to the store?
```javascript
dispatch('myModule/fetch', {where: [['archived', '==', true]]})
  .then(querySnapshot => {
    if (querySnapshot.done === true) {
      // `{done: true}` is returned when everything is already fetched and there are 0 docs:
      console.log('finished fetching all docs')
      return
    }
    querySnapshot.forEach(doc => {
       const fetchedDoc = doc.data()
       fetchedDoc.id = doc.id
       store.commit('myModule/INSERT_DOC', fetchedDoc)
    })
  })
```

**Comment by mesqueeb** [comment]
Hi @thokkane
yeah it should definitely still work! I didn't change anything to the code.

Are you experiencing any problem with this?

You can also [look at the source code](https://github.com/mesqueeb/vuex-easy-firestore/blob/master/src%2Fmodule%2Factions.ts#L298) to see how it works.

Let me know if there's something not working!

**Comment by fergusmeiklejohn** [comment]
I'm calling fetchAndAdd and I'm not passing a custom limit object {limit: 0} and yet it's still fetching over 50 docs. Is this 50 limit still valid?

**Comment by mesqueeb** [comment]
if you _don't_ pass a custom limit object, it will default to 50. 😉 

did you execute this?
```js
dispatch('fetchAndAdd', {limit: 0})
```

**Comment by louisameline** [comment]
I think this can safely be closed. We'll have to reconsider the argument passed to the resolve promise handler.
