### ISSUE TITLE
Update firebase dependency to 6.1.0

### ISSUE THREAD

**Issue by c0h1b4** [mesqueeb/vuex-easy-firestore#216]
Hello, I just updated my firebase to the latest version and I'm getting this error:

{"type":"warning","data":"" > vuex-easy-firestore@1.34.0" has incorrect peer dependency "firebase@^5.8.0"."}

Any chance to have the dependency in sync with firebase version?

Thanks,
Mauro

**Comment by c0h1b4** [comment]
Hello, I just updated my firebase to the latest version and I'm getting this error:

{"type":"warning","data":"\" > vuex-easy-firestore@1.34.0\" has incorrect peer dependency \"firebase@^5.8.0\"."}

Any chance to have the dependency in sync with firebase version?

Thanks,
Mauro

**Comment by mesqueeb** [comment]
Yes. You can make sure they're the same version by passing your Firebase dependency to my library.

Please see the documentation here:
https://mesqueeb.github.io/vuex-easy-firestore/extra-features.html#pass-firebase-dependency

Let me know how it goes!

**Comment by mesqueeb** [comment]
---
After about two years of open source, I finally got accepted for Github Sponsors!

#### 💜 [github.com/sponsors/mesqueeb](https://github.com/sponsors/mesqueeb) 💜 

A little about me:
- I love open-source
- 6 months ago I got a son, and am trying to be an awesome father 😅
- I'm doing freelance work here and there as my main job

#### If anyone was helped with vuex-easy-firestore, **I'd greatly appreciate any support**!

> BTW, donations get's paid DOUBLE by GitHub! (they're alchemists... 🦾)

Going forward 👨🏼‍💻
- I got great plans for the future of vuex-easy-firestore going above and beyond!! Look forward to it!!
- On to many more years of open-sourcing! 🎉
