### ISSUE TITLE
Combine Vuex-easy-firestore with an existing vuex instance

### ISSUE THREAD

**Issue by Sitarman** [mesqueeb/vuex-easy-firestore#218]
Hello mesqueeb,
Is there a straightforward way to combine vuex-easy -firestore with an existing vuex project? Is it feasable? The existing project I refer to provides firebase Auth only.
Cheersi
Steve

**Comment by Sitarman** [comment]
Ah! I seem to have it working!

**Comment by Sitarman** [comment]
Success!!

**Comment by mesqueeb** [comment]
Hi @Sitarman 
Glad you got it working!! 😅

if you run into any specific issues feel free to open another issue.

<sub>--<br>Vuex Easy Firestore was made with ♥ by Luca Ban.<br>If this library helped you in any way you can support me by buying me <a href="https://www.buymeacoffee.com/mesqueeb">a cup of coffee</a>. ☕️</sub>

**Comment by mesqueeb** [comment]
---
After about two years of open source, I finally got accepted for Github Sponsors!

#### 💜 [github.com/sponsors/mesqueeb](https://github.com/sponsors/mesqueeb) 💜 

A little about me:
- I love open-source
- 6 months ago I got a son, and am trying to be an awesome father 😅
- I'm doing freelance work here and there as my main job

#### If anyone was helped with vuex-easy-firestore, **I'd greatly appreciate any support**!

> BTW, donations get's paid DOUBLE by GitHub! (they're alchemists... 🦾)

Going forward 👨🏼‍💻
- I got great plans for the future of vuex-easy-firestore going above and beyond!! Look forward to it!!
- On to many more years of open-sourcing! 🎉
