### ISSUE TITLE
how to wait for data to be updated in Firestore

### ISSUE THREAD

**Issue by ctwhome** [mesqueeb/vuex-easy-firestore#220]
Hi!

I can't find the way to wait for data to be updated in Firestore.
```
this.$sotre.set('organizations/patch', {obj})
.then(()=>{
    // it doesn't do anything here
})
.catch(error => console.log(error))
```

 is it possible to know If the data actually synced with Firestore? At that moment I want to call other functions that depend on that. 

thanks!

**Comment by ctwhome** [comment]
Ah of course... With hooks right? :innocent:   jezz sorry!

**Comment by mesqueeb** [comment]
Hi @ctwhome 
Just waiting for the Vuex Store to be updated and the sync data to be pushed to Firestore, you'll do good with hooks yeah. 😅

If you really need to wait until Firestore updates server side you'll need to use serverside hooks. However, they won't be triggered when the change you made is a local change. So in this case you should force a serverside hook by syncing an object with a prop `firestore().FieldValue.serverTimestamp()`.

If you don't undrestand I could give you an example, but I'd really need to know more on your use case to be able to give good advice.

I'll close it for now but feel free to continue the discussion. 😉

**Comment by ctwhome** [comment]
Hi Luca, 

thanks for the info and for asking. 
I want to show a loading bar when loading new collections (because I clear them up when exiting the router). Right now I have a message that says: "no documents in this collection" while loading, but that is not what I want. I need to know when the call is being made to activate the spinner. 


```
serverChange: {
    addedHook: function(updateStore, doc, id, store) {
      updateStore(doc)
      console.log('🎹 EXECUTED HEREEE')
    },
```

I may need a mini example to see exactly when the server is finished

thaaaanks!

**Comment by mesqueeb** [comment]
serverChange addedHook cant be used for fetching data manually.  
You’re talking about openDBChannel or fetchAndAdd right??

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ctwhome** [comment]
Yes indeed, openDBChannel and fetchAndAdd, but also for inserts, updates and deletes. I don't know how to wait for the server

**Comment by mesqueeb** [comment]
I was confused, because your question asked for _waiting for "inserts and updates"_,
but your use case describes _waiting for `openDBChannel` or `fetchAndAdd`_... 🧐

Waiting for `openDBChannel` or `fetchAndAdd` is easy:
```js
await dispatch('module/openDBChannel')
// or
await dispatch('module/fetchAndAdd')
```

Waiting until a server update is made:
- why do you need this. I don't understand your use case and I feel like you can have a different solution all together, without having to need to wait for the actual server update. Firebase saves everything in local cache anyway, so if you're offline waiting for the actual server update won't work either... 🙃

if it's because you insert a new document locally and you change a route (or some variable) and that document _should_ be fetched but takes a while until it shows up, then this has nothing to do with wether or not firebase actually wrote the data on their servers, because the Firebase SDK should have the received the data locally and saved it in cache either way. This means that when it's read it's also read from cache again... 😉

Could you please try explaning your use case a bit clearer because I don't fully understand... 😅

**Comment by ctwhome** [comment]
this toke time for me to reply! sorry!
I have an example: 
 
![blinking](https://user-images.githubusercontent.com/4195550/66150209-f70bf080-e614-11e9-9709-08fb78ae4624.gif)

that blinking occurred because I am showing "No ideas yet" when entering in the route, I clear the state and (ideas) and immediately open with other params, all ideas that are in the same organization. FYI, Organizations have ideas, but I have mixed all the ideas in the same collection, so when I go to one organization I openDBConnect where I filter all the ideas by organizationId. I am not entirely sure if this is the best practice, but ok. 

![image](https://user-images.githubusercontent.com/4195550/66150961-98e00d00-e616-11e9-9656-dcc1c363168d.png)

So the idea is that I can watch when vuex-easy-firestore is performing an action, like writing, or fetching data... so I can hide the message of "No ideas yet" until Firestore is finished. 

I can control the timing with await as you say, I was wondering if you are already firing some commits to vuex to know when firebase is busy or not.
![loading](https://user-images.githubusercontent.com/4195550/66151314-5539d300-e617-11e9-8f76-cd4c18f3cdf5.gif)


I hope this makes things a bit more clear, sorry for the labyrinth.

**Comment by stegithub** [comment]
Hi @mesqueeb thanks for your work. About (maybe) this issue, i need to know if the returned value is from cache or from server (from your doc: "the action returns a promise which resolves when the state of the module has been populated with data (served either from cache or server), so you know you can start working with it").
Is there a method to know it? i'm changing the value from firebase and at starting App i've first old value and than newest (i want to know that is an old value).

**Comment by louisameline** [comment]
Hi there! Have you seen the `refreshed` promise that you can get from `openDBChannel`?
https://mesqueeb.github.io/vuex-easy-firestore/query-data.html#realtime-updates-opendbchannel

**Comment by stegithub** [comment]
> Hi there! Have you seen the `refreshed` promise that you can get from `openDBChannel`?
> https://mesqueeb.github.io/vuex-easy-firestore/query-data.html#realtime-updates-opendbchannel

Thanks, i've update package, seems to work
