### ISSUE TITLE
Gett an invalid doc reference with collection

### ISSUE THREAD

**Issue by jefnight** [mesqueeb/vuex-easy-firestore#222]
I am getting the following error when trying to access a collection.  The firestore has a root collection of 'clients' which I was using without error directly from my components.

Error in created hook: "FirebaseError: [code=invalid-argument]: Invalid document reference. Document references must have an even number of segments, but clients has 1"

```javascript
const clientsModule = {
    firestorePath: 'clients',
    firestoreRefPath: 'collection',
    moduleName: 'clientsModule',
    statePropName: 'data',
    namespaced: true,
}
export default clientsModule
```
Accessing from my ClientsList.vue component
```javascript
created() {
    this.$store.dispatch('clientsModule/openDBChannel').then().catch(console.error)
  },
```

**Comment by mesqueeb** [comment]
I think that perhaps you have two modules with the same name? 😅
You need to add the VEF config lines to your actual vuex module and not in a separate object. Then you need to pass on that vuex module ONLY as plugin to my library, which will take care of mounting it to your vuex store.

Please double check this line of the setup documentation:
### 2. Create a Vuex store init file
```
// include as PLUGIN in your vuex store
// please note that "myModule" should ONLY be passed via the plugin
```
https://mesqueeb.github.io/vuex-easy-firestore/setup.html#setup

Does this help?

**Comment by jefnight** [comment]
Thanks for the quick reply.
 I have followed you setup to the letter except for passing the store in the main.js file.  Without this the store doesn't get initialised.  Ive checked my code and there are no other inits of this object.

Main.js looks like:
```javascript
import Vue from 'vue'
import './plugins/vuetify'
import App from './App.vue'
import router from './router/router'
import store from './store/index.js'
Vue.config.productionTip = false
Vue.use(require('vue-moment'));

new Vue({
  router,
  store,
  render: h => h(App),
}).$mount('#app')
```

Index.js
```javascript
import Vue from 'vue'
import Vuex from 'vuex'
import VuexEasyFirestore from 'vuex-easy-firestore'
// import * as user from './modules/userModule'
Vue.use(Vuex)

// import from step 1
import { Firebase, initFirebase } from '../firebase-config'
// import from step 3 (below)
import clientsModule from './modules/clientsModule'

// do the magic 🧙🏻‍♂️
const easyFirestore = VuexEasyFirestore(
  [clientsModule],
  {logging: true, FirebaseDependency: Firebase}
)

// include as PLUGIN in your vuex store
// please note that "myModule" should ONLY be passed via the plugin
const storeData = {
  plugins: [easyFirestore],
  // ... your other store data
}

// initialise Vuex
const store = new Vuex.Store(storeData)
// eslint-disable-next-line
console.log("*****Inside")
// initFirebase
initFirebase()
.then((val) =>{
        // eslint-disable-next-line
        console.log("*****Inside", val)
        // initFirebase
    })
  .catch(error => {
      // eslint-disable-next-line
      console.log("*****",error)
    // take user to a page stating an error occurred
    // (might be a connection error, or the app is open in another tab)
  })

export default store
```

**Comment by mesqueeb** [comment]
@jefnight Do you have a repo you can share so I can try and step through the error myself?
I have no idea where this error comes from and haven't experienced this myself.

**Comment by jefnight** [comment]
@mesqueeb I only have it in gitlab but can send you a download - does that suit?

**Comment by jefnight** [comment]
Hi have solved the issue - stupid error - used firestoreRefPath instead of firestoreRefType !!

**Comment by mesqueeb** [comment]
Oh wow! 
Sorry for non noticing sooner!!! 😅 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mesqueeb** [comment]
---
After about two years of open source, I finally got accepted for Github Sponsors!

#### 💜 [github.com/sponsors/mesqueeb](https://github.com/sponsors/mesqueeb) 💜 

A little about me:
- I love open-source
- 6 months ago I got a son, and am trying to be an awesome father 😅
- I'm doing freelance work here and there as my main job

#### If anyone was helped with vuex-easy-firestore, **I'd greatly appreciate any support**!

> BTW, donations get's paid DOUBLE by GitHub! (they're alchemists... 🦾)

Going forward 👨🏼‍💻
- I got great plans for the future of vuex-easy-firestore going above and beyond!! Look forward to it!!
- On to many more years of open-sourcing! 🎉
