### ISSUE TITLE
"Duplicate getter key" error with custom getters

### ISSUE THREAD

**Issue by okatsuralau** [mesqueeb/vuex-easy-firestore#223]
Using custom getters is throwing a "Duplicate getter key".

Here is a code sample (see the console):

https://codesandbox.io/s/vuex-easy-firestore-demo-viwjo

**Comment by mesqueeb** [comment]
Sorry, I overlooked the issue!
You are passing the `todos` module twice. Once in the plugin and once in your store.

From the [setup documentation](https://mesqueeb.github.io/vuex-easy-firestore/setup.html#setup):
> // include as PLUGIN in your vuex store
> // please note that "myModule" should ONLY be passed via the plugin

So just don't pass it into modules 😉 

<sub>--<br>Vuex Easy Firestore was made with ♥ by Luca Ban.<br>If this library helped you in any way you can support me by buying me <a href="https://www.buymeacoffee.com/mesqueeb">a cup of coffee</a>. ☕️</sub>

**Comment by mesqueeb** [comment]
Gonna close this, but feel free to continue the discussion!

**Comment by mesqueeb** [comment]
---
After about two years of open source, I finally got accepted for Github Sponsors!

#### 💜 [github.com/sponsors/mesqueeb](https://github.com/sponsors/mesqueeb) 💜 

A little about me:
- I love open-source
- 6 months ago I got a son, and am trying to be an awesome father 😅
- I'm doing freelance work here and there as my main job

#### If anyone was helped with vuex-easy-firestore, **I'd greatly appreciate any support**!

> BTW, donations get's paid DOUBLE by GitHub! (they're alchemists... 🦾)

Going forward 👨🏼‍💻
- I got great plans for the future of vuex-easy-firestore going above and beyond!! Look forward to it!!
- On to many more years of open-sourcing! 🎉
