### ISSUE TITLE
Missing vuex-easy-access in Dependencies

### ISSUE THREAD

**Issue by ockam** [mesqueeb/vuex-easy-firestore#226]
On the latest [commit (5d8acf)](https://github.com/mesqueeb/vuex-easy-firestore/commit/5d8acf2247d52fd8a37e3b9231d565a2cf9c318e), the dependency to vuex-easy-access has been moved to devDependencies, but is still imported in `dist/index.esm.js`, therefore should still be listed in Dependencies.

**Comment by mesqueeb** [comment]
@ockam !!! That's a problem!! I'll fix it asap :S

**Comment by mesqueeb** [comment]
Fixed on latest version! Thanks!!!

<sub>--<br>Vuex Easy Firestore was made with ♥ by Luca Ban.<br>If this library helped you in any way you can support me by buying me <a href="https://www.buymeacoffee.com/mesqueeb">a cup of coffee</a>. ☕️</sub>

**Comment by mesqueeb** [comment]
---
After about two years of open source, I finally got accepted for Github Sponsors!

#### 💜 [github.com/sponsors/mesqueeb](https://github.com/sponsors/mesqueeb) 💜 

A little about me:
- I love open-source
- 6 months ago I got a son, and am trying to be an awesome father 😅
- I'm doing freelance work here and there as my main job

#### If anyone was helped with vuex-easy-firestore, **I'd greatly appreciate any support**!

> BTW, donations get's paid DOUBLE by GitHub! (they're alchemists... 🦾)

Going forward 👨🏼‍💻
- I got great plans for the future of vuex-easy-firestore going above and beyond!! Look forward to it!!
- On to many more years of open-sourcing! 🎉
