### ISSUE TITLE
{userId} document in Firestore

### ISSUE THREAD

**Issue by EvanAgee** [mesqueeb/vuex-easy-firestore#235]
![image](https://user-images.githubusercontent.com/1692674/62327876-44ce7600-b477-11e9-8ac5-d28d4140a64d.png)

I'm occassionally having the issue of my document having an ID of {userId} in Firestore despite having my openDBChannel wrapped in Firebase.auth().onAuthStateChanged().

```
Firebase.auth().onAuthStateChanged(async user => {
  if (user) {
    await Promise.all([
      store.dispatch('user/openDBChannel'),
      store.commit(`user/login`, null)
    ]);
  }
});
```

Been dealing with this for hours trying to figure out what's wrong, any help is appreciated.

**Comment by mesqueeb** [comment]
@EvanAgee Hi.
This is usually a problem when there's two Firebase instances active.
Are you passing the Firebase dependency like so:
https://mesqueeb.github.io/vuex-easy-firestore/extra-features.html#pass-firebase-dependency

Let me know!!! ;)

**Comment by mesqueeb** [comment]
Did it work? 🧐🥺🤗

**Comment by stegithub** [comment]
Hi, i've the same problem randomly, after refresh page sometimes have this problem, sometimes not. I'm not passing the firebase dep (is the same passing it). 
Is during the same case (onAuthStateChanged).
plugin v.^1.34.3

**Comment by mesqueeb** [comment]
Hi @stegithub and @EvanAgee 
Lately I noticed a similar bug in my apps. There's something wrong with the reactivity of getters in Vuex I assume. 

One workaround I found was to always execute what I explain in this post:
https://github.com/mesqueeb/vuex-easy-firestore/issues/253#issuecomment-546745926

Just change the `companyId` with `userId` and manually pass the user via the mutation I describe there. 😉 

I'm pretty sure this will solve the problem at hand. I'm going to try and find a better solution in the long run.
Let me know how it went!!

<sub>--<br>Vuex Easy Firestore was made with ♥ by Luca Ban.<br>If this library helped you in any way you can support me by buying me <a href="https://www.buymeacoffee.com/mesqueeb">a cup of coffee</a>. ☕️<br>You can also reach out <a href="https://twitter.com/mesqueeb">on twitter</a> if you want a one-on-one coding review/lesson. 🦜</sub>

**Comment by mesqueeb** [comment]
Good news! I think I was able to fix the bug (with some help ♥) and I just pushed the latest version with the fix: `v1.34.4`

Can you install the latest version; delete any work-arounds you had; and try to see if the problem was fixed?

It should be fixed but maybe some apps still have edge-cases, so let me know how it goes 🙃

<sub>--<br>Vuex Easy Firestore was made with ♥ by Luca Ban.<br>If this library helped you in any way you can support me by buying me <a href="https://www.buymeacoffee.com/mesqueeb">a cup of coffee</a>. ☕️<br>You can also reach out <a href="https://twitter.com/mesqueeb">on twitter</a> if you want a one-on-one coding review/lesson. 🦜</sub>

**Comment by EvanAgee** [comment]
Awesome, thanks so much for the hard work @mesqueeb !

**Comment by stegithub** [comment]
Thanks @mesqueeb

**Comment by mesqueeb** [comment]
---
After about two years of open source, I finally got accepted for Github Sponsors!

#### 💜 [github.com/sponsors/mesqueeb](https://github.com/sponsors/mesqueeb) 💜 

A little about me:
- I love open-source
- 6 months ago I got a son, and am trying to be an awesome father 😅
- I'm doing freelance work here and there as my main job

#### If anyone was helped with vuex-easy-firestore, **I'd greatly appreciate any support**!

> BTW, donations get's paid DOUBLE by GitHub! (they're alchemists... 🦾)

Going forward 👨🏼‍💻
- I got great plans for the future of vuex-easy-firestore going above and beyond!! Look forward to it!!
- On to many more years of open-sourcing! 🎉
