### ISSUE TITLE
Does vuex-easy-firebase support mapActions?

### ISSUE THREAD

**Issue by eltonlau1994** [mesqueeb/vuex-easy-firestore#237]
It seems the current module is set inside VuexEasyFirestore function. I tried to implement mapAction but it said Vuex cannot find the module name.

When I use module property in storeData, vuex function api is unable to find.

Does that mean if I want to use VuexEasyFirestore function, I have to give up the use of mapAction?

Thanks.

**Comment by mesqueeb** [comment]
Hi @eltonlau1994  👋
thanks for your post.

vuex-easy-firestore will dynamically create and register modules to your vuex store AFTER the store's initialisation.
This may be the reason that mapActions cannot be used. ;)

I am personally not a fan of mapActions and mapGetters and therefore have never tested it!

You can learn more about how vuex-easy-firestore creates modules by looking at this line:
https://github.com/mesqueeb/vuex-easy-firestore/blob/master/src/index.ts#L50

Feel free to make a PR as well! 🤗

**Comment by louisameline** [comment]
Vuex v4 roadmap:

> Getting rid of mapXXX helpers via scoped-slot based store consumer component

Not sure what it means exactly but they seem to be on their way out. Never liked them either

**Comment by louisameline** [comment]
To provide a more specific answer to this isue: there are no plans to work specifically on a solution to this.

However, we'll probably be using plain actions in the future (not inserted by a plugin anymore), so I can't see why it wouldn't work then. If mapActions haven't been deprecated by that time anyway.

Thank you
