### ISSUE TITLE
Firebase.firestore.FieldValue.serverTimestamp() cannot be used for a property

### ISSUE THREAD

**Issue by rchan** [mesqueeb/vuex-easy-firestore#24]
When setting a property with Firebase.firestore.FieldValue.serverTimestamp(), it does not resolve correctly, it saves the method definition instead to firestore

the created_at and updated_at generated by the framework works correctly

**Comment by mesqueeb** [comment]
@rchan Can you try again with v1.7.1 and let me know how it goes?

**Comment by mesqueeb** [comment]
@rchan I will look into the `Firebase.firestore.FieldValue.serverTimestamp()` bug soon, sorry it's not fixed yet.
For now the library should be usable with `v1.9.0` as there was a bug in `v1.8.0`.
Next on my list is to add tests for custom usage of `Firebase.firestore.FieldValue.serverTimestamp()`

**Comment by mesqueeb** [comment]
@rchan 
I have fixed it so you can now use `Firebase.firestore.FieldValue.serverTimestamp()` with custom fields.
please update to: `npm i vuex-easy-firestore@latest`

Thank you so much for the bug report.

**Comment by mesqueeb** [comment]
@rchan I made all new documentation! Check it out:
[new full documentation](http://mesqueeb.github.io/vuex-easy-firestore/feedback.html)

**Comment by mesqueeb** [comment]
---
After about two years of open source, I finally got accepted for Github Sponsors!

#### 💜 [github.com/sponsors/mesqueeb](https://github.com/sponsors/mesqueeb) 💜 

A little about me:
- I love open-source
- 6 months ago I got a son, and am trying to be an awesome father 😅
- I'm doing freelance work here and there as my main job

#### If anyone was helped with vuex-easy-firestore, **I'd greatly appreciate any support**!

> BTW, donations get's paid DOUBLE by GitHub! (they're alchemists... 🦾)

Going forward 👨🏼‍💻
- I got great plans for the future of vuex-easy-firestore going above and beyond!! Look forward to it!!
- On to many more years of open-sourcing! 🎉
