### ISSUE TITLE
I can't see fetched data in state

### ISSUE THREAD

**Issue by antonijap** [mesqueeb/vuex-easy-firestore#246]
I am a beginner and I would like to utilize your library to make my life easier but I bumped into a problem. I followed the documentation, tried various changes but it simply doesn't work for me. I get no errors but my Vue Chrome plugin says that there is no data in my modules. Nothing is fetched although there are some samples in Firebase (Firestore).

This is my repo: https://github.com/antonijap/udomi-2.0/tree/new/vuex-firestore-setup/src

I appreciate any help.

**Comment by mesqueeb** [comment]
---
<sub>
After about two years of open source, I finally got accepted for Github Sponsors!

#### 💜 [github.com/sponsors/mesqueeb](https://github.com/sponsors/mesqueeb) 💜 

A little about me:
- I love open-source
- 6 months ago I got a son, and am trying to be an awesome father 😅
- I'm doing freelance work here and there as my main job

#### If anyone was helped with vuex-easy-firestore, **I'd greatly appreciate any support**!

> BTW, donations get's paid DOUBLE by GitHub! (they're alchemists... 🦾)

#### Going forward 👨🏼‍💻
- I got great plans for the future of vuex-easy-firestore going above and beyond!! Look forward to it!!
- On to many more years of open-sourcing! 🎉
</sub>
