### ISSUE TITLE
Cannot update a value and increment the same value

### ISSUE THREAD

**Issue by colbyashcroft** [mesqueeb/vuex-easy-firestore#247]
You cannot currently send the two updates shown below within the same sync debounce window without completely breaking the package (by breaking the package I'm unable to make any more changes to firestore via vuex-easy-firestore after I attempt the code below)

``` 
      dispatch('patch', {id, value: 0})
      dispatch('patch', {id, value: increment(1)})
```

You can replicate this issue using the [github link](https://github.com/colbyashcroft/vuex_easy_firestore_increment_problem) or a [github.io link](https://colbyashcroft.github.io/vuex_easy_firestore_increment_problem/)

In the github.io link I've added a console.log in your package in the function `makeBatchFromSyncstack`  the log happens when looping through the update array and it logs  the update item that is eventually used in the firebase batch function, you can see the log in the code below.

```
    updates.forEach(function (item) {
        var id = item.id;
        var docRef = (collectionMode) ? dbRef.doc(id) : dbRef;
        if (state._conf.sync.guard.includes('id'))
            delete item.id;
        // @ts-ignore
        console.log('easyFirestoreUpdateItem', item);
        batch.update(docRef, item);
    });
```

Clicking the increment button simply uses vuex-easy-firestore to increment the value.  if you click on it a few times, wait for the sync debouce to finish you will see an update log that looks like this for the value

![image](https://user-images.githubusercontent.com/44585904/65552171-f373bd80-dee0-11e9-9022-213c98babd3b.png)

when you simply click the reset button it will use vuex-easy-firestore to set the value to 0.  if you click on that button and wait for the sync debounce to finish you will get an update log that looks like this for value

![image](https://user-images.githubusercontent.com/44585904/65552439-a217fe00-dee1-11e9-8847-3063267e4955.png)

Now the interesting part happens when you click the reset button, and then quickly (before the sync debounce finishes) click on the increment button.  this series of actions will result in code that is essentially this
``` 
      dispatch('patch', {id, value: 0})
      dispatch('patch', {id, value: increment(1)})
```
and that produces an update log that looks like this
![image](https://user-images.githubusercontent.com/44585904/65552593-0a66df80-dee2-11e9-9af8-c5c777734983.png)
which is the increment helper class that you created rather than the firebase update.  This results in the following error
```
index.cjs.js:350 Uncaught (in promise) FirebaseError: Function WriteBatch.update() called with invalid data. Unsupported field value: a custom t object (found in field value)
```

Firebase itself can handle the batch updates when they are sent in as separate commands directly to batch
```
      var batch = db.batch();
      const ref = db.collection("collectionName").doc(id);
      batch.update(ref, {value: 3});
      batch.update(ref, {value: increment(10)})
      batch.commit()
```
This code can be demonstrated by clicking on the "Batch Firestore" button in the github.io link.  that button will just run the code above.  the Count does not get updated automatically though so you will need to refresh the page after clicking the button to see that the value gets set to 13.

**Comment by mesqueeb** [comment]
Hi @colbyashcroft thanks for reporting! 😄 

An interesting find as well. 🧐

Can you try this?
```js
dispatch('patch', {id, value: 0})
dispatch('batchSync')
dispatch('patch', {id, value: increment(1)})
```

**Comment by colbyashcroft** [comment]
@mesqueeb 

Thanks for your feedback,  sorry it took a bit to get back to you.  the series of calls you recommended does fix the issue.

So to be clear
```
dispatch('patch', {id, value: 0})
dispatch('batchSync')
dispatch('patch', {id, value: increment(1)})
```
works without any errors and fixes the issue with
```
dispatch('patch', {id, value: 0})
dispatch('patch', {id, value: increment(1)})
```

**Comment by colbyashcroft** [comment]
I discovered another way to break it that makes less sense to me.

I have a [github](https://github.com/colbyashcroft/vuex_easy_firestore_increment_problem2) and a [github.io](https://colbyashcroft.github.io/vuex_easy_firestore_increment_problem2) where you can test the problem.  the github.io also has the change where you can see the update log before it tries to run the batch.

So in the theoretical application where I'm breaking it we have a collection of that each document is a list of books.  the list of books is theoretically user sortable so we want to keep track of the order of each book. so each document in the collection would looks something like this.

```
{
id: 'string'
books: {
            abcd: {
                      id: 'abcd',
                      title: 'book1',
                      author: 'author1',
                      order: 0
                     },
            efgh: {
                      id: 'efgh',
                      title: 'book2',
                      author: 'author2',
                      order: 1
                     },
            ijkl: {
                      id: 'ijkl',
                      title: 'book3',
                      author: 'author3',
                      order: 2
                     }
          }
}
```


now in order to add a new book at say order 1,  you would want to find all of the books with order greater than or equal to 1 and increment them by 1 so you would have a patch that looked something like this

```
update = {
id: 'string'
books: {
            newBook: {
                      id: 'newBook',
                      title: 'book4',
                      author: 'author4',
                      order: 1
                     },
            efgh: { order: increment(1) },
            ijkl: {order: increment(1) }
          }
}
dispatch('patch', update);
```

This results in an updateArray in your 'makeBatchFromSyncStack' function that looks like this
![image](https://user-images.githubusercontent.com/44585904/66077831-03f9e880-e51e-11e9-9515-5041050a1016.png)

Now If I were to edit the title of the book at position 0 before adding a new book at position 1 I would end up with the following patches.

```
update1 = {
id: 'string'
books: {
            abcd: {title: 'editedTitle'},
          }
}
dispatch('patch', update1)

update2 = {
id: 'string'
books: {
            newBook: {
                      id: 'newBook',
                      title: 'book4',
                      author: 'author4',
                      order: 1
                     },
            efgh: { order: increment(1) },
            ijkl: {order: increment(1) }
          }
}
dispatch('patch', update2);
```

So adding this new patch of the title of an item that is not being modified in the second patch will brake easy firestore and create the same error

```Function WriteBatch.update() called with invalid data. Unsupported field value: a custom t object (found in field books.efgh.order)```

it produces the same problem in the update object where the items being incremented are still not converted to the Firestore.incrment but still have your increment object in them.

![image](https://user-images.githubusercontent.com/44585904/66078684-b2525d80-e51f-11e9-99d1-e7cbcc84032a.png)


So originally thought it was when you were trying to increment the exact same value but this makes it looks like it's something else.

Hope this can help with the troubleshooting.

Let me know if you have any questions

**Comment by mesqueeb** [comment]
@colbyashcroft thank you for your repo. I was able to find the bug.
I'm pushing an update now.

**Comment by mesqueeb** [comment]
Should be fixed in latest version! (1.34.3 and above)

Please try `npm i vuex-easy-firestore@latest`
and let me know!

If it is fixed, please close the issue! ♡

<sub>--<br>Vuex Easy Firestore was made with ♥ by Luca Ban.<br>If this library helped you in any way you can support me by buying me <a href="https://www.buymeacoffee.com/mesqueeb">a cup of coffee</a>. ☕️<br>You can also reach out <a href="https://twitter.com/mesqueeb">on twitter</a> if you want a one-on-one coding review/lesson. 🦜</sub>

**Comment by colbyashcroft** [comment]
It no longer breaks. thank you

**Comment by mesqueeb** [comment]
---
<sub>
After about two years of open source, I finally got accepted for Github Sponsors!

#### 💜 [github.com/sponsors/mesqueeb](https://github.com/sponsors/mesqueeb) 💜 

A little about me:
- I love open-source
- 6 months ago I got a son, and am trying to be an awesome father 😅
- I'm doing freelance work here and there as my main job

#### If anyone was helped with vuex-easy-firestore, **I'd greatly appreciate any support**!

> BTW, donations get's paid DOUBLE by GitHub! (they're alchemists... 🦾)

#### Going forward 👨🏼‍💻
- I got great plans for the future of vuex-easy-firestore going above and beyond!! Look forward to it!!
- On to many more years of open-sourcing! 🎉
</sub>
