### ISSUE TITLE
Skip is defaultValues when inserting a new object

### ISSUE THREAD

**Issue by Mattertorian** [mesqueeb/vuex-easy-firestore#255]
Hi @mesqueeb 

Once again thanks for a great library!

I have an issue when I try to use a custom Class as the payload in
`dispatch('myModule/insert', payload)`
I get an error that defaultValues could not be merged onto a custom object.
I handle the conversion to a 'plain' object in the hooks and would like to use the custom Class until that hook. 
Is it currently possible to skip the setDefaultValues step?

Keep up the good work!

Best wishes,
Mattertorian

**Comment by mesqueeb** [comment]
Hi @Mattertorian This is currently not possible I'm sorry. 😅 

I don't have the time currently to add this feature, but if you feel like it, feel free to make a PR!

**Comment by mesqueeb** [comment]
---
After about two years of open source, I finally got accepted for Github Sponsors!

#### 💜 [github.com/sponsors/mesqueeb](https://github.com/sponsors/mesqueeb) 💜 

A little about me:
- I love open-source
- 6 months ago I got a son, and am trying to be an awesome father 😅
- I'm doing freelance work here and there as my main job

#### If anyone was helped with vuex-easy-firestore, **I'd greatly appreciate any support**!

> BTW, donations get's paid DOUBLE by GitHub! (they're alchemists... 🦾)

Going forward 👨🏼‍💻
- I got great plans for the future of vuex-easy-firestore going above and beyond!! Look forward to it!!
- On to many more years of open-sourcing! 🎉

**Comment by louisameline** [comment]
Hello, unfortunately I don't think it would be a good idea to allow this.
Especially not with the features coming to v-e-f in the next version.
I think it is safe to close the request.
Thank you
