### ISSUE TITLE
Explain dispatch use better

### ISSUE THREAD

**Issue by 12vanblart** [mesqueeb/vuex-easy-firestore#256]
Something I struggled to get working until finding [the sample app](https://github.com/mesqueeb/vuex-easy-firestore-sample-app) was where to put `dispatch(module/command)`. 

It'd be nice if a section was added to either the "Installation & Setup" or "Add and manage data" page that `this.$store.dispatch()` can be used from a component, as well as adding a link to the example app's repository on the front page to make finding it easier than through GitHub's "Used By" package feature.

**Comment by mesqueeb** [comment]
@12vanblart thank you for your post.
The thing about my sample app is that it's really not the best app and I didn't give it nearly too much love for me to want to promote it more. 😄 

Dispatching actions from your store can literally be done anywhere in your app. Doesn't even need to be inside a Vue Component. So all this depends on how you want to build your app really... 😅 

Thanks for your issue though! I'll try to make some time to build a better sample app, re-upload it and promote it a little better.

I'll close this issue in favour of others that asked for the same thing, but feel free to continue the discussion down below! 🙃 

<sub>--<br>Vuex Easy Firestore was made with ♥ by Luca Ban.<br>If this library helped you in any way you can support me by buying me <a href="https://www.buymeacoffee.com/mesqueeb">a cup of coffee</a>. ☕️<br>You can also reach out <a href="https://twitter.com/mesqueeb">on twitter</a> if you want a one-on-one coding review/lesson. 🦜</sub>

**Comment by mesqueeb** [comment]
---
<sub>
After about two years of open source, I finally got accepted for Github Sponsors!

#### 💜 [github.com/sponsors/mesqueeb](https://github.com/sponsors/mesqueeb) 💜 

A little about me:
- I love open-source
- 6 months ago I got a son, and am trying to be an awesome father 😅
- I'm doing freelance work here and there as my main job

#### If anyone was helped with vuex-easy-firestore, **I'd greatly appreciate any support**!

> BTW, donations get's paid DOUBLE by GitHub! (they're alchemists... 🦾)

#### Going forward 👨🏼‍💻
- I got great plans for the future of vuex-easy-firestore going above and beyond!! Look forward to it!!
- On to many more years of open-sourcing! 🎉
</sub>
