### ISSUE TITLE
Vuex not in sync after first page load when deployed

### ISSUE THREAD

**Issue by Nrevi** [mesqueeb/vuex-easy-firestore#257]
For some reason when I deploy to firebase hosting vuex isn’t in sync after the first page load if I add an entry through a restful api or manually on firebase. This isn’t the case when the web application is hosted locally - everything is always in sync.

**Comment by mesqueeb** [comment]
@Nrevi I don't have this problem either on my end. I have persistence enabled for all my projects and none of them have documents created back. 🧐

I'd have to look at some code to try and reason on what's going wrong. 😅

**Comment by Nrevi** [comment]
I noticed that if on mobile, the web application is in sync after logging in and when i add data on other devices the data updates accordingly without reloading. However, after not opening the browser for let's say an hour? the data only updates if i reload.

But, if i logout and log-in back. everything is in sync.

**Comment by Nrevi** [comment]
Here's some of my code that is relevant - 

db/index.js
`
export default {
  firestorePath: 'users/{userId}',
  firestoreRefType: 'doc', // or 'doc'
  moduleName: 'db',
  statePropName: 'data',
  namespaced: true // automatically added
}
`

store/index.js
`
import Vue from 'vue'
import Vuex from 'vuex'
import VuexEasyFirestore from 'vuex-easy-firestore'
import auth from './auth/index'
import db from './db/index'

Vue.use(Vuex)

const easyFirestore = VuexEasyFirestore([db], {
  logging: true,
  FirebaseDependency: Vue.prototype.$firebase
})

export default new Vuex.Store({
  plugins: [easyFirestore],
  state: {},
  mutations: {},
  actions: {},
  modules: {
    auth
  }
})

firebase plugin
`
import * as firebase from 'firebase/app'

import 'firebase/auth'
import 'firebase/firestore'
import 'firebase/performance'

export default {
  install(Vue) {
    var firebaseConfig = {
      apiKey: process.env.VUE_APP_FIREBASE_apiKey,
      authDomain: process.env.VUE_APP_FIREBASE_authDomain,
      databaseURL: process.env.VUE_APP_FIREBASE_databaseURL,
      projectId: String(process.env.VUE_APP_FIREBASE_projectId),
      storageBucket: process.env.VUE_APP_FIREBASE_storageBucket,
      messagingSenderId: process.env.VUE_APP_FIREBASE_messagingSenderId,
      appId: process.env.VUE_APP_FIREBASE_appId
    }

    // Initialize Firebase
    firebase.initializeApp(firebaseConfig)
    firebase.firestore().enablePersistence()

    firebase.performance()

    Vue.prototype.$firebase = firebase
    window.$firebase = firebase
    //Access auth by just doing 'this.$auth'
    window.$auth = Vue.prototype.$auth = firebase.auth()
  }
}

main.js

`
import Vue from 'vue'
import App from './App.vue'
import router from './router'
import store from './store'
import vuetify from './plugins/vuetify'
import firebaseDev from './plugins/firebase-dev'
import Vuelidate from 'vuelidate'
import wordsAPI from './axios/wordsAPI'

Vue.use(Vuelidate)
Vue.use(firebaseDev)
Vue.prototype.$wordsApi = wordsAPI

Vue.prototype.$auth.onAuthStateChanged(user => {
  if (user) {
    store.dispatch('db/setUserId', user.uid)
    store.dispatch('db/openDBChannel')
  } else {
    store.dispatch('db/closeDBChannel', { clearModule: true })
  }
  store.dispatch('auth/fetchUser', user)
  new Vue({
    router,
    store,
    vuetify,
    render: h => h(App)
  }).$mount('#app')
})

Vue.config.productionTip = false

`
`
`

**Comment by mesqueeb** [comment]
Thanks for providing some code. 😉 

Can you try this initialisation method instead?
```js
import * as Firebase from 'firebase/app'
import 'firebase/firestore'

function initFirebase () {
  Firebase.initializeApp({ /* your Firebase config */})
  return new Promise((resolve, reject) => {
    Firebase.firestore().enablePersistence()
      .then(resolve)
      .catch(err => {
        if (err.code === 'failed-precondition') {
          reject(err)
          // Multiple tabs open, persistence can only be
          // enabled in one tab at a a time.
        } else if (err.code === 'unimplemented') {
          reject(err)
          // The current browser does not support all of
          // the features required to enable persistence
        }
      })
  })
}

export { Firebase, initFirebase }
```
then initialise it just after creating your store like so:
```js
// initialise Vuex
const store = new Vuex.Store(storeData)

// initFirebase
initFirebase()
  .catch(error => {
    // take user to a page stating an error occurred
    // (might be a connection error, or the app is open in another tab)
  })

export default store
```

**Comment by mesqueeb** [comment]
Good news! I think I was able to fix the bug (with some help ♥) and I just pushed the latest version with the fix: `v1.34.4`

Can you install the latest version; delete any work-arounds you had; and try to see if the problem was fixed?

It should be fixed but maybe some apps still have edge-cases, so let me know how it goes 🙃

<sub>--<br>Vuex Easy Firestore was made with ♥ by Luca Ban.<br>If this library helped you in any way you can support me by buying me <a href="https://www.buymeacoffee.com/mesqueeb">a cup of coffee</a>. ☕️<br>You can also reach out <a href="https://twitter.com/mesqueeb">on twitter</a> if you want a one-on-one coding review/lesson. 🦜</sub>

**Comment by Nrevi** [comment]
Thanks, I'll implement the new version later today. I'll let you know.

**Comment by Nrevi** [comment]
Sorry for the late response but this patch has definitely resolved my issue.

**Comment by mesqueeb** [comment]
---
<sub>
After about two years of open source, I finally got accepted for Github Sponsors!

#### 💜 [github.com/sponsors/mesqueeb](https://github.com/sponsors/mesqueeb) 💜 

A little about me:
- I love open-source
- 6 months ago I got a son, and am trying to be an awesome father 😅
- I'm doing freelance work here and there as my main job

#### If anyone was helped with vuex-easy-firestore, **I'd greatly appreciate any support**!

> BTW, donations get's paid DOUBLE by GitHub! (they're alchemists... 🦾)

#### Going forward 👨🏼‍💻
- I got great plans for the future of vuex-easy-firestore going above and beyond!! Look forward to it!!
- On to many more years of open-sourcing! 🎉
</sub>
