### ISSUE TITLE
objects and class instances don't work with arrayRemove

### ISSUE THREAD

**Issue by jacksonrya** [mesqueeb/vuex-easy-firestore#264]
Removing a single Firestore DocumentReference object from an array of length one using arrayRemove(foo).

Firestore array is emptied. Vuex array is not emptied; the last element remains. The two fall out of sync.

The array within the payload of 'module/PATCH_DOC' is of length one—the local state is updated without change.

** Haven't had a change to sandbox it yet in order to find how specific or general this issue is relative to: array length, working with DocumentReference objects. Will update issue if sandboxing finds anything different.

**Comment by mesqueeb** [comment]
Hi @jacksonrya
I'm sorry I haven't been able to look into this yet! I will try to as soon as possible and update here.

---
<sub>
After about two years of open source, I finally got accepted for Github Sponsors!
💜 [github.com/sponsors/mesqueeb](https://github.com/sponsors/mesqueeb) 💜 

A little about me:
- I love open-source
- 6 months ago I got a son, and am trying to be an awesome father 😅
- I'm doing freelance work here and there as my main job

If anyone was helped with vuex-easy-firestore, **I'd greatly appreciate any support**!

BTW, donations get's paid DOUBLE by GitHub! (they're alchemists... 🦾)


I got great plans for the future of vuex-easy-firestore going above and beyond!! Look forward to it!!

On to many more years of open-sourcing! 🎉
</sub>

**Comment by louisameline** [comment]
@jacksonrya quick question: does your array contains arrays/objects?
If yes, please check this: #80

**Comment by louisameline** [comment]
Any news on this @jacksonrya? I will reopen the issue if you can tell us more about it. Thank you very much

**Comment by stegithub** [comment]
@mesqueeb hi, maybe i've the same problem (v^1.34.4). When i use arrayUnion/arrayRemove i've not store in sync with firestore, (only once time debugging your code). Here some details:
i'm using sync/addedHook and sync/patchHook to sync. When i use arrayUnion/arrayRemove i execute updateStore(doc) in sync/patchHook but then in sync/addedHook i've no doc updated.
Debugging i've seen that in your code (PATCH_DOC) there's something wrong (maybe) on this lines:
if (isArray(originVal) && isArrayHelper(newVal)) {
       newVal = newVal.executeOn(originVal);
}
executeOn not removing item on array, and maybe yes it's adding item.
Is correct that in sync/addedHook "doc" is not updated? have i to check store values?
Thanks for your work

**Comment by stegithub** [comment]
i've seen that during arrayUnion in sync/addedHook, store is updated but not the doc. Is it correct? maybe doc updated is usefull.
Instead during arrayRemove the state is not updated.

**Comment by mesqueeb** [comment]
@stegithub can you show me exactly how your addedHook looks like because I'm confused about your setup. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by stegithub** [comment]
> @stegithub can you show me exactly how your addedHook looks like because I'm confused about your setup.
> 
> Sent with [GitHawk](http://githawk.com)

addedHook(updateStore, doc, id, store) {
         updateStore(doc)
}

**Comment by stegithub** [comment]
i've also:
patchHook(updateStore, doc, store) { 
            updateStore(doc)
        }
in an action i remove item array in a field and add it into other field. And above the problem

**Comment by stegithub** [comment]
@mesqueeb can i reopen the issue? You can easily replicate the issue only with the hooks and dispatching PATCH to remove/add on array with arrayRemove/arrayUnion. See all the scopes of 2 hooks.
I'm using it like:
dispatch(PATCH, {id: doc_id, not_linked_account: arrayRemove(docRef)})

**Comment by mesqueeb** [comment]
@stegithub
The reason this bug is occuring is because you are trying to remove a `docRef`.
To execute arrayRemove I'm trying to find whatever you pass inside the array with a simple `indexOf`, you can see it on this line:
https://github.com/mesqueeb/vuex-easy-firestore/blob/master/src/utils/arrayHelpers.ts#L40

And thus, when passing a `docRef` or an object probably, it won't be able to find them inside the array, and therefore not removing it from your vuex module. 😅 

As a workaround you can manually remove the docRef from your array inside your vuex state.

I'll rename this ticket to "objects and class instances don't work with arrayRemove".

**Comment by stegithub** [comment]
> @stegithub
> The reason this bug is occuring is because you are trying to remove a `docRef`.
> To execute arrayRemove I'm trying to find whatever you pass inside the array with a simple `indexOf`, you can see it on this line:
> https://github.com/mesqueeb/vuex-easy-firestore/blob/master/src/utils/arrayHelpers.ts#L40
> 
> And thus, when passing a `docRef` or an object probably, it won't be able to find them inside the array, and therefore not removing it from your vuex module. 😅
> 
> As a workaround you can manually remove the docRef from your array inside your vuex state.
> 
> I'll rename this ticket to "objects and class instances don't work with arrayRemove".

I'm trying to push changes that fix it but i've no permission

**Comment by mesqueeb** [comment]
@stegithub You need to make a pull request :)

**Comment by stegithub** [comment]
> @stegithub You need to make a pull request :)

And i cannot push on my branch?

**Comment by stegithub** [comment]
> @stegithub You need to make a pull request :)

need to do a fork and then PR?

**Comment by mesqueeb** [comment]
Yes

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mesqueeb** [comment]
@stegithub @jacksonrya this issue should now be fixed in v1.35.3, partially because of @stegithub 's PR! thanks!!

<sub>--<br>Vuex Easy Firestore was made with ♥ by Luca Ban.<br>If you use this library in your projects, you can support the maintenance of this library by a small <a href="https://github.com/sponsors/mesqueeb">contribution via Github 💜</a>.<br>You can also reach out <a href="https://twitter.com/mesqueeb">on twitter</a> if you want a one-on-one coding review/lesson. 🦜</sub>
