### ISSUE TITLE
allow `null` for `statePropName`

### ISSUE THREAD

**Issue by mesqueeb** [mesqueeb/vuex-easy-firestore#267]
> - [ ] `statePropName` cannot be set to `null`, you currently have to set an empty string. I've seen this in other places too. This is an unexpected because as a general rule, the absence of a value should be represented by `null`. Only in very rare cases empty strings should be used.

**Comment by louisameline** [comment]
I'm doing this, an easy issue to begin with

**Comment by mesqueeb** [comment]
Any library I'm using that has "-anything" at the end is my own library 😉

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by louisameline** [comment]
I hope this is ok, this is the first time I use TypeScript:
https://github.com/louisameline/vuex-easy-firestore/tree/statePropName

It's backwards compatible for empty strings.

**Comment by louisameline** [comment]
Would you share an email so we can discuss at some point? I might have things to ask you now and then.

Like, I wanted to talk about coding style. I usually follow the style of libraries I edit, but to be honest I have a hard time here to grasp everything that happens in the lib. I wanted to know how open you are to having a less compact code, and maybe let me follow a couple conventions I appreciate. I loosely follow Google's JS style guides.
As a sample of my own style, this is how I'd write the `patch` action:

https://gist.github.com/louisameline/ac6ebf402eca4848f5f03f6ee6e0b920

The original's below

https://github.com/mesqueeb/vuex-easy-firestore/blob/838c7b6d9f0ced1142805c7480b8416abce613c3/src/module/actions.ts#L597-L628

Let me know! Thanks

**Comment by louisameline** [comment]
BTW I noticed `patch` should probably return a promise on the Firestore's call success, but that's another discussion

**Comment by mesqueeb** [comment]
Hi @louisameline
Thank you very much for looking into this. I've sent you an email. I'm currently on the road so haven't been able to check your PR yet! Btw I'm on timezone Tokyo (+9gmt)
I imagine you're on +1 ?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mesqueeb** [comment]
@louisameline commented on your PR. Thanks a lot !!!!

**Comment by louisameline** [comment]
I'm on +1 yes, let me get back to you!

**Comment by mesqueeb** [comment]
Thanks again for this! As you know I've merged and implemented it. 😄
