### ISSUE TITLE
[Question] Reject action with hook

### ISSUE THREAD

**Issue by scriptPilot** [mesqueeb/vuex-easy-firestore#269]
Is there a way to reject a dispatch('.../insert') action from a hook?

**Comment by louisameline** [comment]
What would be the use case for this please?

**Comment by mesqueeb** [comment]
@scriptPilot Yes:

<img width="627" alt="Screenshot 2019-11-20 14 23 39" src="https://user-images.githubusercontent.com/3253920/69211422-5f9d3580-0ba1-11ea-966a-48ecf0b59bda.png">

See:
https://mesqueeb.github.io/vuex-easy-firestore/hooks.html#hooks-on-local-changes

Let me know how it goes 😉 

<sub>--<br>Vuex Easy Firestore was made with ♥ by Luca Ban.<br>If this library helped you in any way you can support me by buying me <a href="https://www.buymeacoffee.com/mesqueeb">a cup of coffee</a>. ☕️<br>You can also reach out <a href="https://twitter.com/mesqueeb">on twitter</a> if you want a one-on-one coding review/lesson. 🦜</sub>
