### ISSUE TITLE
Doc Patch: no way to replace a deep nested object

### ISSUE THREAD

**Issue by louisameline** [mesqueeb/vuex-easy-firestore#274]
Hi!

The current `patch` action does not allow to replace a deep nested object, it only allows to extend it. Firestore's `update` method allows it though.
This could be a new feature.

Thanks!

**Comment by louisameline** [comment]
I search and this can be used, just needs a few editions to work with Vue: https://www.npmjs.com/package/object-path

**Comment by mesqueeb** [comment]
A new `update` action that allows replacing parts of a (deep) nested object without merging everything is planned for v2 😉 
stay tuned!
