### ISSUE TITLE
Fixing openDBChannel

### ISSUE THREAD

**Issue by louisameline** [mesqueeb/vuex-easy-firestore#276]
Hi!

There are many issues in that function.

- when the promise is rejected because of `preventInitialInsert`, the channel is not closed
- the same promise is used at channel startup and in the error callback, but it can't be as it will already have been resolved. Effectively, it means that the user currently can't catch errors that happen in the channel
- the error returned by Firebase is considered as a string but it's an Error object
- the `unsubscribe` reference is not emptied upon error
- `resolve()` is unnecessarily called at times where it can't be anything but resolved already
- you write `return resolve()` many times in the callback, which is confusing from a coding point of view, because the returned value is not passed to anything, so I corrected it to `resolve(); return`

I fixed it all up and added a promise which gets passed when `openDBChannel` resolves.
I amended the doc too, to explain these things (I also removed a couple lines which were not meaningful).

I haven't made a PR yet since I need to test this, but you can see it here already:
https://github.com/louisameline/vuex-easy-firestore/commit/09fb10fbaf382191105e35a84b5781215ba0b6da

Thanks!

**Comment by mesqueeb** [comment]
@louisameline I have reviewed the changes and they're really good!
If you could make a PR for me, I'll do some testing on my end and merge.
Thanks!!! 😄
