### ISSUE TITLE
openDBChannel's promise should not be rejected when it's already open

### ISSUE THREAD

**Issue by louisameline** [mesqueeb/vuex-easy-firestore#279]
When the user triggers an action to `openDBChannel` and that it's already open, the promise returned by the action gets rejected. This is really counter-intuitive as what the user asks (having an open channel) is actually successfully in effect, so the promise really should be resolved.

A warning or simple log to the console to say that it was already open is enough.

**Comment by mesqueeb** [comment]
Yes, I agree. I realised how stupid this was a few weeks after I had already implemented it.
Now however there are already a bunch of people who are dependant on this, so I really can't change it anymore in v1.

I'm also planning this for v2 (as you know. ;)

**Comment by louisameline** [comment]
It probably wouldn't be a breaking change though. People might have done something like this:
```javascript
dispatch('module/openDBChannel')
  .then(doSomething)
  .catch(error => {
    if (error == 'channelAlreadyOpenError') {
      doSomething()
    }
  }
})
```
So if we resolve instead of rejecting with this error, it's the same to them.
A change is actually more likely to fix apps that accidently try to open the channel again, than break ones. To say it another way: why would *not throwing an error* break things? ;)

**Comment by louisameline** [comment]
This can wait until the next version actually. The structure will change in the next version and I think it would be a waste of time to adapt the lib to make it work now.

**Comment by mtltechtemp** [comment]
@mesqueeb @louisameline Why not simply exposing the DBChannel state?
That would allow to simply put the `open` request in a condition.

**Comment by louisameline** [comment]
I see no reason to add that extra condition to your code if the promise is resolved anyway when the stream is already open. I feel it would be encouraging you to write overhead "channel-starting" code, while the point is rather to write "channel-running" code that handles errors well and that makes you confident the channel will actually always be open. I'm not sure this is very clear sorry! You'll see the next version is going to be much simpler than the current one, I don't think you'll feel the need for a boolean state anymore.

**Comment by mesqueeb** [comment]
I'm thinking of changing this in v1.0 anyway, because I had another re-think about it and I feel it's not a breaking issue. I can't imagine any scenario of someone's app breaking because of this.

@eneskaya @coolhand79 let me know if you disagree.

**Comment by mtltechtemp** [comment]
@louisameline @mesqueeb Maybe we could simply add a boolean to disable the throwing of that error if we want to be on the safe side.

**Comment by mtltechtemp** [comment]
@mesqueeb Do you have any ETA for the v2 ?

**Comment by mesqueeb** [comment]
no ETA, this is a 100% free-time only project. I work on it whenever I find the time 🙃

**Comment by mtltechtemp** [comment]
@mesqueeb You might want to use [gitpay](https://gitpay.me/) people might want to raise some issues ;)

**Comment by mesqueeb** [comment]
fixed in latest version

**Comment by louisameline** [comment]
This can unfortunately not be fixed the way it was fixed, it has side effects as we currently run through the whole process of opening the channel again, while we should return the same objects as the ones that were created the first time the stream was opened. It's quite some work of refactoring, I think it's not worth it to take care of it before the next major version of the library.

I'll revert this and leave the ticket open.
