### ISSUE TITLE
9 records in firebase, logging 9 + 89k undefined

### ISSUE THREAD

**Issue by riksnelders** [mesqueeb/vuex-easy-firestore#281]
Any idea what the hell is happening here ? This might be due to hotspotting maybe ?

Edit: This only happens when I use clearModule:true

![image](https://user-images.githubusercontent.com/15074808/70023338-71b2a700-1597-11ea-8ba2-367aeea1fe02.png)

**Comment by louisameline** [comment]
Please try to debug the error that happens just before (in red) and if it persists, give us more context: when, what, where. Thank you

**Comment by louisameline** [comment]
Nb: If you have a loop making calls to Firestore, you'd better prevent the code from running right now to avoid crazy bills. Also set a maximum budget in Firebase just in case it ever happens.

**Comment by riksnelders** [comment]
When page is created, db channel is opened
When page is navigated away from, db channel is closed
Whenever i add {clearModule:true} to the closeDBchannel this happens.

If u navigate back same cycle happens.  and only happens when the clear module is used.

The error before is just simply the logs from development from vuex-easy-firestore

**Comment by louisameline** [comment]
As it happens, I corrected several things in that opendbchannel function, would you check out my branch (currently waiting for the PR to get merged) and see if it fixes your issue?

**Comment by riksnelders** [comment]
Seems empty objects are not deleted from store. I really have no clue where this is coming from.

Might it be firebase related?
![image](https://user-images.githubusercontent.com/15074808/70246585-43d88880-1778-11ea-9c0d-c04373cd0a27.png)


Same stuff

**Comment by louisameline** [comment]
Read my last comment in this thread, it might be what you experienced: https://github.com/mesqueeb/vuex-easy-firestore/issues/180

**Comment by mesqueeb** [comment]
@riksnelders I'm pretty sure that this is some mistake, an infinite loop or something in your front-end code.
I just publish 1.35.1 which includes @louisameline fixes for openDBChannel. 🎉

However, there's a chance this won't fix the problems for you if you have a loop somewhere so I'd have to look at your code to know what is happening exactly. 😅
can you share your repo?

**Comment by riksnelders** [comment]
@mesqueeb hey. I cannot share the repo.

Hiw do u explain the empty Objects to be just as much as ever inserted in firebase. It can not be a loop.. Else it kept on adding stuff..

**Comment by mesqueeb** [comment]
@riksnelders I cannot explain the empty objects, because I don't know why you have so many! 😆 
I cannot explain anything if I cannot see code...

The problem you mention I have never experienced or heard of, so it must be something in your code. That's why I can't help you without seeing the code.

**Comment by riksnelders** [comment]
It pretty much shows the amount of records that were ever in firebase.. I dont get it when using another package.

``` 
   beforeDestroy() {
      this.$store.dispatch('cargo/closeDBChannel', {clearModule: true}).catch(console.error);

    },
    created() {
      let where = [
        ['companyId', '==', parseInt(this.getAPICompanyID)]
      ];
      this.$store.dispatch('cargo/openDBChannel', {where}).then(() => {
        console.log(this.$store.state.cargo);
        console.log(this.cargoTest)
      });
    }
``` 
Module is setup like so:
``` 
import state from './state'
import mutations from './mutations'
import actions from './actions'
import getters from './getters'


const products = {
  firestorePath: '/outgoing-cargos',
  firestoreRefType: 'collection', // or 'doc'
  moduleName: 'cargo',
  statePropName: 'cargo',
  namespaced: true, // automatically added
  // this object is your store module (will be added as '/myModule')
  // you can also add state/getters/mutations/actions

  state, getters, mutations, actions
}

export default products
```

**Comment by riksnelders** [comment]
With 1.36.1 I'm getting this error now
```
Vue warn]: Error in beforeDestroy hook: "TypeError: Cannot read property 'resolve' of undefined"

found in

---> <LoadingOverview> at src/views/loading/LoadingOverview.vue
       <App> at src/App.vue
         <Root>
```

**Comment by louisameline** [comment]
I guess you try to clear the state yourself if the promise can't be found when you destroy. If you use openDBChannel, do you use the `clear` option?

**Comment by riksnelders** [comment]
No only in the close

**Comment by louisameline** [comment]
Please elaborate.

**Comment by riksnelders** [comment]
``` 
  beforeDestroy() {
      this.$store.dispatch('cargo/closeDBChannel', {clearModule: true}).catch((error)=>console.error(error));

    },
    created() {
      let where = [
        ['companyId', '==', parseInt(this.getAPICompanyID)]
      ];
      this.$store.dispatch('cargo/openDBChannel', {where}).then(() => {
        console.log(this.$store.state.cargo);
      });
    }
```

**Comment by louisameline** [comment]
I have no issues on my end with `dispatch('module/closeDBChannel', {clearModule: true})`.

Did you know that the library currently stores data at the root of your module, under keys named `_conf` and `_sync`? They will be removed in a future version of the lib, but for now they must stay there. I suspect you delete these properties inadvertantly.

**Comment by riksnelders** [comment]
I do not delete anything from the store. I only use functions from the package itself

**Comment by louisameline** [comment]
Ok, I am not sure what else we can do for you without more information. Could you debug the last error on your side?

**Comment by louisameline** [comment]
We have a new 1.35.2 version to be used, just in case it would help. Otherwise, since there is nothing we can do without further information, I will now close this issue and encourage you to debug on your side. Feel free to comment if you have more information to share. Thank you.

**Comment by riksnelders** [comment]
@louisameline @mesqueeb  I might have found this issue..
It seems to occur when either state of a prop = [] or {}  (mostlikely []) as the data is an object.

Using _filter(on the state containing the [])  Seems to be causing issues somehow. 
Haven't had time to completely debug this, since I'm short on time to get some stuff fixed and live ASAP. Any one wanna help me out debugging this?

**Comment by mesqueeb** [comment]
@riksnelders What? 😄 
Can you add me on discord, we can discuss. `Luca Ban [Mesqueeb]#4774`

**Comment by riksnelders** [comment]
added

**Comment by mesqueeb** [comment]
To anyone coming here.
This was debugged in a meeting between me and Rik.

The problem was that by mistake an array was used as the `statePropName`, instead of an object!
**You can only use an object to host your documents in a collection!**

As per example I'll show a wrong and correct version:

# ⛔ Wrong
```
  firestorePath: '/myCollection,
  firestoreRefType: 'collection',
  moduleName: 'myModule',
  statePropName: 'data',
  namespaced: true, // automatically added
  state: {
    data: []
  }
}
```
# ✅ Correct
```
  firestorePath: '/myCollection,
  firestoreRefType: 'collection',
  moduleName: 'myModule',
  statePropName: 'data',
  namespaced: true, // automatically added
  state: {
    data: {}
  }
}
```
