### ISSUE TITLE
Missing `addedHook` calls upon `insert`

### ISSUE THREAD

**Issue by louisameline** [mesqueeb/vuex-easy-firestore#289]
It seems that a `dispatch('module/insert')` will not trigger a call to the `serverChange: { addedHook: fn }` callback.

**Comment by mesqueeb** [comment]
Yes. This is intensional. 
I made the hooks so local changes only trigger the local hooks.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mesqueeb** [comment]
as we discussed,
if you want to wait for the server to have actually received the actual change you can do this:
```js
dispatch('module/insert').then(() => { /* server received the change */ })
```
this was briefly touched upon in [these release notes](https://github.com/mesqueeb/vuex-easy-firestore/releases/tag/v1.35.0).
