### ISSUE TITLE
Is there a way to limit openDBChannel?

### ISSUE THREAD

**Issue by hugomsm** [mesqueeb/vuex-easy-firestore#290]
Hello,

With openDBChannel in a module using collection mode, it will sync all the docs for a collection with my Vuex module, right? But what if I have a collection with many docs? I will pay for the read of everyone everytime I use my app, even without needing to read all of them everytime in the app.

I would like to implement a "load more" feature. I know that's possible with the "fetchAndAdd" feature, but the data will not stay in sync.

Do you know any way to achieve this keeping the data in sync?

Thanks!

**Comment by hugomsm** [comment]
And it is possible to use limit with onSnapshot on Firebase, I'm using it.

Example:

```  
let additionalQuery = this.$db
                .collection(this.collection)
                .where("xxx_id", "==", this.xxx_id)
                .orderBy(this.field)
                .startAfter(this.lastVisible[this.field])
                .limit(10)
                .onSnapshot(async querySnapshot => {
                  var data = [];
                  querySnapshot.forEach(function(doc) {
                    data.push({
                      ...doc.data(),
                      id: doc.id
                    });
                  });
```

**Comment by louisameline** [comment]
Hi, in the documentation, I see no way to change the parameters of a snapshot listener after it has been created, so I don't think you can tell it "listen to 10 more documents please".
Are you sure you need realtime updates on so many objects that you need to paginate them? It sounds resource-heavy.

**Comment by hugomsm** [comment]
> Hi, in the documentation, I see no way to change the parameters of a snapshot listener after it has been created, so I don't think you can tell it "listen to 10 more documents please".
> Are you sure you need realtime updates on so many objects that you need to paginate them? It sounds resource-heavy.

Thank you for the answer. Let me give an example: imagine that you have a customer's shop and it has its products list. Imagine that the shop has more than 1000 different products, and each product is a document inside a "shop123/products" collection. In Firestore, I'll pay for every document read, right? So every time I open this shop products page, I'll pay for 1000 reads, even if I only check the first 10 products.

As a suggestion, you could put a starting limit to the openDBChannel action (as is possible in the "fetchAndAdd" method) and maybe create a new action for this library to call the next ones, like I did in my code. I did a workaround, creating an array of subscriptions and then I add this "additionalQuery" (which is for the load more function) to this array, and this additionalQuery pushes the new data to my existing data array which is rendered in my component. You can see in the following:

```
let self = this;
 let additionalQuery = this.$db
                .collection(this.collection)
                .where("xxx_id", "==", self.xxx_id)
                .orderBy(this.field)
                .startAfter(this.lastVisible[this.field])
                .limit(10)
                .onSnapshot(async querySnapshot => {
                  var data = [];

                  querySnapshot.forEach(function(doc) {
                    data.push({
                      ...doc.data(),
                      id: doc.id
                    });
                  });

                  for (var i = 0; i < data.length; ++i) {
                    self.$set(self.data, i + index, data[i]);
                  }
                  await delay;
                  self.hasMore = data.length === 10;
                  resolve();
                });

              this.subscriptions.push(additionalQuery);
```

**Comment by louisameline** [comment]
But I'm not sure people really need realtime updates on hundreds of items at the same time, unless you have a solid use case to support that. With global warming and all, maybe you can save some computing power here! I'm not sure we should consider implementing it in the future.

Although the current version is not great at doing it, you can actually change the parameters of the doc module and call `openDBChannel` again, it will open a new channel. Make sure to manage the closing of channels yourself though with the `stop` method.

**Comment by hugomsm** [comment]
Ok, I got it, I'm just trying to reduce  documents unecessary reads in Firestore. You're right, maybe nobody really needs realtime updates on hundres of items at same time, but if there's many people using the app, it would make sense to have pagination to reduce my read costs. 

And it's possible to be made using the native Firestore onSnapshot, so I just suggested that because, as I read in the docs, the openDBChannel relies in this function, so I imagined that this would be a good improvement for large scale applications.

**Comment by louisameline** [comment]
I understand and it's already possible as you can set filters (where, limit) in the config of the collection module before you call `openDBCollection` again, and they will be used to open a new channel, while the first one stays open. All you have to do on your end if you absolutely want to open DBchannels is to keep track of `this.lastVisible[this.field]` and set it in the filters yourself, because we don't do that for you.

We'll work on pagination for the next major version of the lib, but probably not in relation to `openDBCollection` because it seems like a bad idea to listen in realtime to so many objects.

**Comment by louisameline** [comment]
I'll close this as a won't do. You'll need to close the openDBChannel yourself, change some query parameter that suits you, and open it again. Thank you
