### ISSUE TITLE
Sync in background after local store changes

### ISSUE THREAD

**Issue by richie87** [mesqueeb/vuex-easy-firestore#292]
Hey,

first of all i'd like to thank you for your great work!

So far everything is working as expected, except one little thing :smile:

If i add or update a document via `dispatch('myModule/set', doc)` the whole store is getting updated, after the request is done via the Firestore API.... Because of the `serverChange` Hooks i guess.

The problem is that my "layout" disappear and reappear after the reload of the firestore data.

My question is, if its possible to use somehow the local API Call `Vue.set()`on the store data and the firestore sync should happen in the background and should not trigger any `serverChange` Hook.

I hope you understand my question :smile:

Thanks again!

**Comment by mesqueeb** [comment]
vuex easy firestore already has optimistic UI built in.
> firestore sync should happen in the background and should not trigger any serverChange Hook.
this is already the case...
`serverChange` does not trigger when you do `dispatch('myModule/set', doc)` unless you have data that changes when it reaches the server like `serverTimestamp`. : )

I'll need to see much more code before I can understand what you want to achieve.

I'll probably need to know what your `doc` payload is you're setting and also if you have any custom hooks set up.

**Comment by louisameline** [comment]
I'll close due to the lack of activity. Feel free to comment again if you have more information. Thank you.
