### ISSUE TITLE
Is there a way to convert Timestamp to moment instances?

### ISSUE THREAD

**Issue by beardo01** [mesqueeb/vuex-easy-firestore#293]
I see that there is a way to specify `convertTimestamps` in the `serverChange` config and have the Timestamp objects converted to Date objects, however I'd rather convert them to Moment objects for use in my project.

Is there a way to convert to moment instances instead? I also tried converting in the `serverChange.addedHook` but this seems to fire ahead of the `convertTimestamps` config, so the date is being stored as a Date object regardless.

Any help is appreciated!

**Comment by mesqueeb** [comment]
@beardo01 Thanks for the question.
You sure can do!

First, don't use the built in `convertTimestamps` functionality.
Then, in `addedHook` do this:

```js
import { findAndReplaceIf } from 'find-and-replace-anything'

// function that replaces a 'firebaseTimestamp' with moment date
function replaceFirebaseTimestamps (foundVal) {
  if (!(foundVal instanceof Firebase.firestore.Timestamp)) return foundVal
  return Moment(foundVal.toDate())
}


// then in addedHook:
addedHook: function (updateStore, doc) {
  const docWithMomentDates = findAndReplaceIf(doc, replaceFirebaseTimestamps)
  updateStore(docWithMomentDates)
},
```

This is just one example with my library [find-and-replace-anything](https://github.com/mesqueeb/find-and-replace-anything) but of course there are a million ways you can do this. 😉 

Also, please double check if `foundVal instanceof Firebase.firestore.Timestamp` is the correct way to test for Timestamps coming from the server. I haven't tested it.

**Comment by beardo01** [comment]
Hey @mesqueeb, thanks for the reply! I actually ended up changing the way I attacked this problem, however I appreciate the example.

Cheers!
