### ISSUE TITLE
"TypeError: Cannot read property 'where' of undefined" only with fetchAndAdd

### ISSUE THREAD

**Issue by justice47** [mesqueeb/vuex-easy-firestore#303]
I'm having error when trying to execute this:
```javascript
this.$store.dispatch("resultsDetailedModule/fetchAndAdd", {
        pathVariables: {
          sessionID: this.$store.getters.SELECTED_SESSION.id,
          resultID: this.$store.state.resultsModule.selectedResult.id
        }
      });
```
But then I'm changing `fetchAndAdd` to `openDBChannel` all is working right.
Here is the error:
![image](https://user-images.githubusercontent.com/29502063/76862481-3cdd0e00-686f-11ea-9f75-25c1df30fad5.png)

**Comment by mesqueeb** [comment]
Thanks for reporting. 
I probably know how to fix this bug, but might not be able to immediately fix it. Just about to head to bed.
 
As a work around can you try this for now?
```js
this.$store.dispatch("resultsDetailedModule/fetchAndAdd", {
          sessionID: this.$store.getters.SELECTED_SESSION.id,
          resultID: this.$store.state.resultsModule.selectedResult.id
      });
```

**Comment by justice47** [comment]
@mesqueeb thanks for a really quick reply!

Unfortunately I've got another error in this case:
![image](https://user-images.githubusercontent.com/29502063/76863892-48313900-6871-11ea-9703-7630efe0f2ae.png)

**Comment by mesqueeb** [comment]
Hi @justice47 👋🏻
The latest version should have fixed this!

Let me know how it goes 😉 

<sub>--<br>Vuex Easy Firestore was made with ♥ by Luca Ban.<br>If you use this library in your projects, you can support the maintenance of this library by a small <a href="https://github.com/sponsors/mesqueeb">contribution via Github 💜</a>.<br>You can also reach out <a href="https://twitter.com/mesqueeb">on twitter</a> if you want a one-on-one coding review/lesson. 🦜</sub>
