### ISSUE TITLE
timestamp convert for nested props

### ISSUE THREAD

**Issue by Fulbert** [mesqueeb/vuex-easy-firestore#306]
Hello,

I'd like to do something like this : `'signatures.customer.date': '%convertTimestamp%'`.
Unfortunately it doesn't work. That might be useful ?

In the midtime I'm going to use the addedHook.

Thanks!

**Comment by mesqueeb** [comment]
@Fulbert Good catch. I believe nested properties might not be supported.

However, I think using the addedHook is a great solution.
For version 2.0 I'm doing things differently, so for the time being until version 2.0 comes out, you can continue to use the addedHook.

Thanks for reporting!
<sub>--<br>Vuex Easy Firestore was made with ♥ by Luca Ban.<br>If you use this library in your projects, you can support the maintenance of this library by a small <a href="https://github.com/sponsors/mesqueeb">contribution via Github 💜</a>.<br>You can also reach out <a href="https://twitter.com/mesqueeb">on twitter</a> if you want a one-on-one coding review/lesson. 🦜</sub>
