### ISSUE TITLE
id not returned when dispatching insert

### ISSUE THREAD

**Issue by thokkane** [mesqueeb/vuex-easy-firestore#307]
I'm getting undefined for the id when calling this simple createDoc function. I'm using two path variables for the module. Using version 1.35.2.
```
methods:{
        async createDoc(){
            const id = await this.$store.dispatch('media/insert', {
                name:'Test',
            })
            console.log(id)
        },
}
```
Is there a bug?

**Comment by mesqueeb** [comment]
@thokkane
thanks for your ticket!!
that could be a bug. I definitely intended to return the ID. I'll look into it asap!!

**Comment by thokkane** [comment]
@mesqueeb  good to check this also for the moduleName/set

**Comment by thokkane** [comment]
@mesqueeb did you have a chance to look at this?

**Comment by mesqueeb** [comment]
@thokkane I found the bug. I seem to have broken it in about 1.35.2 I believe.

Temporary work around:
```
const id = getters['moduleName/dbRef'].doc().id
const newDoc = {id, /* and other fields */}
dispatch('moduleName/insert', newDoc)
```
With this you provide your own random ID, it's the exact same code I do internally any way, and you won't need to wait for the promise.

I will fix this issue that the promise that gets resolved returns the ID again, however please note that the promise only gets resolved when the sync finalises, and can thus take 1-2 sec. or longer if you keep making api calls within 1000ms.

I am now writing a failing test and hope to fix it today.

**Comment by mesqueeb** [comment]
@thokkane Sorry, I thought I found the bug, but the tests still pass.

I further looked into the code, it might be perhaps when you use hooks. Do you use hooks?
If you do, at the very bottom of the hook, can you try and `return` the `updateStore(doc)` function?

Let me know!

**Comment by thokkane** [comment]
@mesqueeb I have the following for hooks. Still getting undefined for the id.

```
const mediaModule = {
    firestorePath: 'accounts/{accountId}/brands/{brandId}/media',
    firestoreRefType: 'collection', 
    moduleName: 'media',
    statePropName: 'media',
    serverChange: {
        modifiedHook: function (updateStore, doc, id, store, source, change) { 
            updateStore(doc); 
        },
        addedHook: function (updateStore, doc, id, store, source, change) { 
            updateStore(doc); 
        },
        removedHook: function (updateStore, doc, id, store) { 
            updateStore(doc); 
        }
    },
    sync: {
        insertHook: function (updateStore, doc, store) { 
            updateStore(doc)
        },
        patchHook: function (updateStore, doc, store) { 
            updateStore(doc)
        },
        deleteHook: function (updateStore, id, store) { 
            updateStore(id) 
        },
    }
}
```

**Comment by mesqueeb** [comment]
@thokkane yes i see now, it's because you need to `return updateStore(doc)`.

But in your case, if you are not using the hooks you don't even need to include them at all...

```js
const mediaModule = {
    firestorePath: 'accounts/{accountId}/brands/{brandId}/media',
    firestoreRefType: 'collection', 
    moduleName: 'media',
    statePropName: 'media',
    serverChange: {
        modifiedHook: function (updateStore, doc, id, store, source, change) { 
            return updateStore(doc); 
        },
        addedHook: function (updateStore, doc, id, store, source, change) { 
            return updateStore(doc); 
        },
        removedHook: function (updateStore, doc, id, store) { 
            return updateStore(doc); 
        }
    },
    sync: {
        insertHook: function (updateStore, doc, store) { 
            return updateStore(doc)
        },
        patchHook: function (updateStore, doc, store) { 
            return updateStore(doc)
        },
        deleteHook: function (updateStore, id, store) { 
            return updateStore(id) 
        },
    }
}
```
### or even better:
```js
const mediaModule = {
    firestorePath: 'accounts/{accountId}/brands/{brandId}/media',
    firestoreRefType: 'collection', 
    moduleName: 'media',
    statePropName: 'media',
    // serverChange: {},
    // sync: {}
}
```

PS: I'm working hard on version 2.0 and working with events & hooks is way less confusing, so you won't have to worry about these things in the future. 😅 

<sub>--<br>Vuex Easy Firestore was made with ♥ by Luca Ban.<br>If you use this library in your projects, you can support the maintenance of this library by a small <a href="https://github.com/sponsors/mesqueeb">contribution via Github 💜</a>.<br>You can also reach out <a href="https://twitter.com/mesqueeb">on twitter</a> if you want a one-on-one coding review/lesson. 🦜</sub>
