### ISSUE TITLE
Where clause question

### ISSUE THREAD

**Issue by xorbis** [mesqueeb/vuex-easy-firestore#309]
Is this valid?
`await this.$store.dispatch("teams/fetchAndAdd", {
	where: [
		["roles.{userId}", "==", "o"]
	]
});
`

**Comment by xorbis** [comment]
Yes it is... I had an async problem which I solved.

**Comment by mesqueeb** [comment]
## 🎉 

<sub>--<br>Vuex Easy Firestore was made with ♥ by Luca Ban.<br>If you use this library in your projects, you can support the maintenance of this library by a small <a href="https://github.com/sponsors/mesqueeb">contribution via Github 💜</a>.<br>You can also reach out <a href="https://twitter.com/mesqueeb">on twitter</a> if you want a one-on-one coding review/lesson. 🦜</sub>
