### ISSUE TITLE
After a user logs out of firebase the state keeps data

### ISSUE THREAD

**Issue by xorbis** [mesqueeb/vuex-easy-firestore#310]
I am wondering how to cleanup the VueX state once a user logs out.
Is there something I am missing in the documentation or is it obvious?

The problem is that if I login a user and fetch some data and then logout, the data will still be present in the view from the previous user session.

**Comment by mesqueeb** [comment]
closeDBChannel with clearModule param?
I’m outside now but once i’m back i’ll link the proper docs!!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by xorbis** [comment]
Hi thanks for the reply.
I am currently using fetchAndAdd not openDBChannel.

**Comment by mesqueeb** [comment]
Hi @xorbis I only ever built this function for `openDBChannel`, however, if you look here, you'll see that the closeDBChannel just commits a mutation:
https://github.com/mesqueeb/vuex-easy-firestore/blob/master/src/module/actions.ts#L812

```js
commit('RESET_VUEX_EASY_FIRESTORE_STATE')
```
You can commit this mutation to reset the state. And if you want to know exactly what this mutation does, it's here:
https://github.com/mesqueeb/vuex-easy-firestore/blob/master/src/module/mutations.ts#L44

This will be handled differently in v2.0 which is now being developed. 😉

**Comment by xorbis** [comment]
Thanks, will try ASAP.
