### ISSUE TITLE
after every patch serverChange gets fired

### ISSUE THREAD

**Issue by mesqueeb** [mesqueeb/vuex-easy-firestore#312]
see #300

**Comment by mesqueeb** [comment]
@trevorgeise I will do some troubleshooting tomorrow and hope to push a fix (or your fix) soon.

@louisameline let me know if you have any thoughts on this fix Trevor suggested.

**Comment by louisameline** [comment]
I've read Trevor's code and it seems logical. I haven't actually run it or tested it though. Creating the dot notation array only to reparse it afterwards does not seem very efficient but it's better than nothing, and maybe still better than creating a whole new object. It could probably work for v1 but I'd say there's some deeper refactoring to do for next version.

**Comment by mesqueeb** [comment]
@trevorgeise fixed in `1.35.7` thanks again!
