### ISSUE TITLE
(Perf) Which is a right thing to do to set default values from localStorage ASAP?

### ISSUE THREAD

**Issue by l2aelba** [mesqueeb/vuex-easy-firestore#317]
I want to get data from **local storage** to render the list ASAP and get real/updated data after.

Any trick I can do?

PS: Using **local storage** does not require. If something better please tell me

```js
sync: {
    defaultValues: {}
}
```

Still does not fast enough.

**Comment by l2aelba** [comment]
I got a better solution, use **state** instead.

```
createEasyFirestore({
    firestorePath: 'items',
    firestoreRefType: 'collection',
    moduleName: 'items',
    state: state.storage.items // This is from JSON.parse(localStorage.getItem('myApp'))
})
```

But this is right way to do?

**Comment by louisameline** [comment]
Hi, I personnaly use vuex-persist to populate from localstorage, it works like a charm out of the box.

**Comment by louisameline** [comment]
And I think the `state` property that you mentioned should be reserved for the defaut state, and not used to populate with actual data retrieved from localstorage. Because when the whole store is reset (typically at logout), we need to know what a blank state is. So if you don't use vuex-persist, you should populate the state with regular vuex actions instead. @mesqueeb do you confirm?

**Comment by mesqueeb** [comment]
@l2aelba
`defaultValues` is only for "collections" where the document are "loaded" async any way, then the doc and default values are merged whenever a document is loaded.

I see nothing wrong with defining the state like you do directly from local storage. Vuex Easy Firestore is able to work with that state just like regular docs that are fetched, it won't even know the difference. Which is OK if this is what you want. ; )

<sub>--<br>Vuex Easy Firestore was made with ♥ by Luca Ban.<br>If you use this library in your projects, you can support the maintenance of this library by a small <a href="https://github.com/sponsors/mesqueeb">contribution via Github 💜</a>.<br>You can also reach out <a href="https://twitter.com/mesqueeb">on twitter</a> if you want a one-on-one coding review/lesson. 🦜</sub>

**Comment by l2aelba** [comment]
Thank you guys :D

**Comment by louisameline** [comment]
Right, `state` is for doc mode! So my warning about using it applies in doc mode of course, not collections.
