### ISSUE TITLE
Example of error page would be helpful

### ISSUE THREAD

**Issue by adamb** [mesqueeb/vuex-easy-firestore#334]
In the [setup](https://mesqueeb.github.io/vuex-easy-firestore/setup.html#setup) you mention:

>It's very important that we take the user to an error page when something went wrong with the Firestore initialisation.

But it's not clear how to open an error page from inside the init.  A hint or example would be helpful.

I tried making an error page but can't access the router from inside the `~store/index.js:initFirebase()` function.

**Comment by louisameline** [comment]
Hi, technically, only the persistence option of the store may fail:

```javascript
firebase.app.firestore().enablePersistence().catch(error => {})
```
After that, it's the requests to the store that fail, hang or succeed. It's up to you to display a spinner or something until you have the data, or an error message if your get request failed.
We can't tell you how to design your app, it depends on your needs.
I hope it makes things a bit clearer.
