### ISSUE TITLE
Jet Brains IDE's can't resolve Vuex modules 

### ISSUE THREAD

**Issue by fergusmeiklejohn** [mesqueeb/vuex-easy-firestore#343]
Webstorm cannot resolve any variable or function in a Vuex module I'm syncing with VuexEasyFirestore.

Modules not synced with VEF are fine.

I don't know if this is a VEF bug or a JetBrains bug. If it is a JB bug I'm not sure how to describe it to them? How is VEF passing the modules into the Vuex store?

**Comment by mesqueeb** [comment]
Hi @fergusmeiklejohn 
I hope you are doing great!
Sorry I overlooked this issue.

This has probably to do with the way that typescript is integrated via the Vuex plugins and my library.

My 1.0 library does a poor job to support typescript, as it was one of my first typescript projects, there is much left to desire.

In 2.0 there's much better typescript support with autocomplete and proper resolving on all the things.

I'm gonna close the issue for now, but let's continue the discussion down below! ;)

**Comment by fergusmeiklejohn** [comment]
Hi @mesqueeb okay maybe wait until 2.0 is out then see if it works and if not I'll raise it with them again. FYI, this is where they work on support for Vue libraries: https://github.com/JetBrains/intellij-plugins/tree/master/vuejs/src/org/jetbrains/vuejs/libraries
