### ISSUE TITLE
Sync problem- Uncaught (in promise) TypeError: n._sync.syncStack.debounceTimer.refresh is not a function

### ISSUE THREAD

**Issue by tusharthe** [mesqueeb/vuex-easy-firestore#348]
**Uncaught (in promise) TypeError: n._sync.syncStack.debounceTimer.refresh is not a function**

Mainly this error occurs specially user goes offline & try to perform insertion or deletion.
mutation data store in vuex persisted-state state but not able to perform write action to Firebase collection 
& further actions related to that collection always failed. 

![image](https://user-images.githubusercontent.com/20502003/88256883-0bbb9100-ccda-11ea-814a-b67f6c2fbf90.png)

**Comment by louisameline** [comment]
Hi, would you mind trying with the dev branch and tell us if the error still occurs? Thanks

**Comment by tusharthe** [comment]
I have try with dev branch still same error occurs 
it mainly happens when i try to insert new document at offline mode 


![image](https://user-images.githubusercontent.com/20502003/88280194-058dda80-cd03-11ea-9528-d2d31dce4721.png)

**Comment by tusharthe** [comment]
> Hi, would you mind trying with the dev branch and tell us if the error still occurs? Thanks

I have try with dev branch still same error occurs
