### ISSUE TITLE
How to openDBChannel in doc mode - where to put the id of the doc?

### ISSUE THREAD

**Issue by andersbc** [mesqueeb/vuex-easy-firestore#351]
Sorry to bother you with this simple question, I have looked but just can't find it in the docs.. :-(

I want to open a realtime listener for a specific doc ..but i can't figure out where to put the id of the doc:

```js 
// file: MyComponent.vue

beforeMount() {
// my naive attempt doesnt work: 
  this.$store.dispatch('client/openDBChannel', { where: [['id', '==', someUserId]] })
}
``` 
This is my setup:
```js
// vuex module / vuex-easy-firestore
const userModule = {
  firestorePath: 'users',
  firestoreRefType: 'doc',
  moduleName: 'user',
  statePropName: 'data',
  namespaced: true,

  state: {},
  getters: {
    get: (state) => state.data,
  },
}

export default userModule
```

Any help appreciated, thanx :-)

**Comment by mesqueeb** [comment]
@andersbc with doc mode you need the id in your `firestorePath`.
Eg. `firestorePath: 'users/{userId}',`

btw, `{userId}` is a custom path variable that automatically uses Firebase Auth userId of the authenticated user.

If you want to open the module for other users as well you need to do:
```
firestorePath: 'users/{id}'
```
and
```
this.$store.dispatch('user/openDBChannel', {pathVariables: {id: 'some-user-id'}})
```

More info on this feature here:
https://mesqueeb.github.io/vuex-easy-firestore/extra-features.html#variables-for-firestorepath-or-clauses

<sub>--<br>Vuex Easy Firestore was made with ♥ by Luca Ban.<br>If you use this library in your projects, you can support the maintenance of this library by a small <a href="https://github.com/sponsors/mesqueeb">contribution via Github 💜</a>.<br>You can also reach out <a href="https://twitter.com/mesqueeb">on twitter</a> if you want a one-on-one coding review/lesson. 🦜</sub>

**Comment by andersbc** [comment]
Thanx, @mesqueeb :-)

I went with using a collection, as you suggest in the link you provided.. to save a round trip to firestore. I already had a users collection set up. 

You probably know this, but in case other reads this, you can query a firestore _collection_ for a single doc, by it's id
...with this trick: 

```js
this.$store.dispatch('users/openDBChannel', {
  where: [['__name__', '==', props.clientId]],
})
``` 
apparently `'__name__'` works as a placeholder for the doc id in a firebase query (https://stackoverflow.com/questions/47876754/query-firestore-database-for-document-id)

So, in my component I first check if my particular user is included in my already fetched users collection (`getById` getter), and if not I issue the `openDBChannel`command above to populate the collection with the single user I need for that particular component.
