### ISSUE TITLE
Question: can we rely on the `signedIn` getter to check if the user is signed in?

### ISSUE THREAD

**Issue by fergusmeiklejohn** [mesqueeb/vuex-easy-firestore#356]
I was adding a loggedIn getter to the user module and noticed that there is a `signedIn` getter provided by VuexEasyFirestore. I can't find anything about it in the docs, can we rely on it to determine whether a user is signedIn?

**Comment by louisameline** [comment]
No, this is undocumented and should not be used, it might change in the future. Vuex-easy-firestore is meant to deal with the store, you shouldn't use it to interact with Firebase Auth.

**Comment by fergusmeiklejohn** [comment]
I wonder if there is a way to hide those getters in Vue dev tools? It's an invitation to make a mistake otherwise.

**Comment by louisameline** [comment]
I don't know, let us know if you find out!
