### ISSUE TITLE
Retrieve subcollections together with document

### ISSUE THREAD

**Issue by floetti** [mesqueeb/vuex-easy-firestore#359]
Hi,

I can't figure out how to retrieve subcollections from documents. I have a collections of teams and within each team I have a subcollection of documents representing members in the squad. Please point me in the right direction.

Screenshot of the setup:
![Screen Shot 2020-12-07 at 15 15 45](https://user-images.githubusercontent.com/145239/101368484-1c426180-389f-11eb-9b2f-8e4fb059c044.png)

**Comment by louisameline** [comment]
Hello, there is no built-in support for subcollections yet, you'll have to hack your way with the current architecture, or wait for a potential major update next year.

**Comment by floetti** [comment]
Hi again. Thank you for the reply
