### ISSUE TITLE
[docs] manually assigning IDs

### ISSUE THREAD

**Issue by mesqueeb** [mesqueeb/vuex-easy-firestore#37]
Add this to readme:

### Manually assigning IDs

When assigning ID's manually the recommended way to do so is:
`store.getters['yourModule/dbRef'].doc().id`

There is a getter called `dbRef` created on each vuex-easy-firestore module with the reference of your `firestorePath`. So with adding `.doc().id` to that you will "create" a new ID you can pass.

You could wrap it like so:
```js
function newId () {
  return store.getters['yourModule/dbRef'].doc().id
}
```
and just do `newId()` to get a new ID each time! (I'll have to clarify this in the docs)

**Comment by berendsmatt** [comment]
Hi mate! 
Great package.

firestorePath: 'store/{storeId}/item/{itemId}',

How might I handle an address like this?

**Comment by mesqueeb** [comment]
@berendsmatt 
I'm happy you got it solved! Exactly, I've explained how to use multiple variables in firestorePaths [here](https://mesqueeb.github.io/vuex-easy-firestore/extra-features.html#variables-for-firestorepath-or-filters).

Feel free to open an issue if you have any more questions!

**Comment by mesqueeb** [comment]
Resolved!
Please see the [release notes](https://github.com/mesqueeb/vuex-easy-firestore/releases/tag/v1.16.0).
