### ISSUE TITLE
Update library for firebase v9

### ISSUE THREAD

**Issue by bangdragon** [mesqueeb/vuex-easy-firestore#372]
Firebase v9 has been released. So please update this library for working with firebase v9. Thanks

**Comment by wifisher** [comment]
I have made the changes that I think are needed to support Firebase v9 using the compat libraries.

See https://github.com/mesqueeb/vuex-easy-firestore/pull/375

**Comment by mesqueeb** [comment]
@wifisher thank you very much, I will review and release somewhere this week.

**Comment by mesqueeb** [comment]
released
