### ISSUE TITLE
Error: Data type: Reference in doc causes `Maximum call stack size exceeded` 

### ISSUE THREAD

**Issue by jgiovanni** [mesqueeb/vuex-easy-firestore#55]
When using a reference data type in a document, `Maximum call stack size exceeded` error is thrown during retrieval. If I use a different data type for that field `author` it works fine. Am i doing something wrong here?

### Snapshot of document structure:
![image](https://user-images.githubusercontent.com/1894949/46768437-26b04300-ccb6-11e8-8fc2-719476375f94.png)

### Module configuration code
```
const newsFeedModule = {
  firestorePath: "newsFeed",
  firestoreRefType: "collection",
  statePropName: "items"
};
```

### Error in console
![image](https://user-images.githubusercontent.com/1894949/46768614-deddeb80-ccb6-11e8-94d5-9a913e6c14dd.png)

**Comment by mesqueeb** [comment]
@jgiovanni you are not doing anything wrong. 
I know where the bug is and will fix Asap.

**Comment by mesqueeb** [comment]
@jgiovanni The latest version should fix this issue. Please try `npm i vuex-easy-firestore` and let me know if it's fixed or not.

**Comment by jgiovanni** [comment]
It's been fixed thank you!
