### ISSUE TITLE
Trouble referencing docs

### ISSUE THREAD

**Issue by berendsmatt** [mesqueeb/vuex-easy-firestore#59]
Not had a problem with collections.
But not sure why I can't reference a document correctly.
In my store...
`const gameData = {
  firestorePath: "games/{gameId}",
  firestoreRefType: "doc",
  moduleName: "gameData",
  statePropName: "game"
};`
In my view
`this.$store
        .dispatch("gameData/openDBChannel", { gameId: "game1" }) //this.$route.params`

This creates a document with the id {gameId} in my firestore DB 
I want "games/game1" not "games/{gameId}"

**Comment by mesqueeb** [comment]
@berendsmatt
Thanks for this. I have just updated the library with a bug fix.
Please do
`npm i vuex-easy-firestore@latest`
or
`yarn add vuex-easy-firestore@latest`
and let me know if it fixes!

**Comment by berendsmatt** [comment]
Thanks Luca, it's working.
