### ISSUE TITLE
Adding orderBy to sync returns no results

### ISSUE THREAD

**Issue by BenAHammond** [mesqueeb/vuex-easy-firestore#61]
I've run into some strange behavior I think may be a bug?

This code:

```
export default {
  firestorePath: 'groups',
  firestoreRefType: 'collection',
  moduleName: 'groups',
  statePropName: 'collection',
  sync: {
    orderBy: ['created_date']
  }
}
```

Only returns results when the `orderBy` field has been commented out. With the `orderBy` line as it is above, I get no results. If I remove that line, the results of my query appear. I've verified the automatic `created_date` is present so I'm not sure why its not returning data.

**Comment by mesqueeb** [comment]
Thank you Ben. I'm looking into this issue right now.

**Comment by BenAHammond** [comment]
Let me know if I can help, and thank you.

**Comment by mesqueeb** [comment]
@BenAHammond 
I just tested myself and got no results as well.
But then I checked my database and realised, it's not `created_date` but `created_at`!!

These are the [auto-generated fields](https://mesqueeb.github.io/vuex-easy-firestore/guide.html#collection-mode) by vuex-easy-firestore.

It works with `created_at` for me : )

**Comment by BenAHammond** [comment]
Ohhhh, man, that's annoying. Thank you for burning time on that.

I wonder if we could get some kind of development/debugging output for the sync functionality. As it is it just queries in the background and its very hard to figure out what is happening.

**Comment by mesqueeb** [comment]
@BenAHammond I understand what you mean, but openDBChannel only executes Firestore's [onSnapshot](https://mesqueeb.github.io/vuex-easy-firestore/setup.html#open-db-channel) function. Then it will feed the `orderBy` and `where` just like you would do when executing onSnapshot directly.

There is not much I can do in between those and I do not want to bloat the code with unnecessary code for in those rare cases someone writes a typo. : D

> the default functionality should be when an item is missing a field to orderBy

This also, I can't change Firestore's behaviour...

Anyway, I do understand your pain and I have had similar experiences in my past where I'd debug something for a whole day to find out I'm referencing the wrong property name... But I digress.

I have added some info on openDBChannel and what happens under the hood in the [documentation](https://mesqueeb.github.io/vuex-easy-firestore/setup.html#open-db-channel).

**Comment by BenAHammond** [comment]
Good to know! I will go take it up with them.

 Thanks again.

**Comment by mesqueeb** [comment]
@BenAHammond Please note that orderBy might also behave different, because this library stores the results in an object with the document id as key.

That means you'll need to write a client-side orderBy function inside a vuex-getter to show your collection in your wished order.

So I mean: setting orderBy in this library will retrieve the docs in that order, but are saved inside an object so will loose its order!

**Comment by BenAHammond** [comment]
That's good to know, thank you for updating this.

This makes me wonder if there's an opportunity to provide a sorted/filtered/paged "View" into a collection with its own API.

**Comment by mesqueeb** [comment]
Yeah you’ve asked me for paging support. What kind of app you have that needs paging though? I never needed it before so have difficulties imagining a good way to implement this. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by BenAHammond** [comment]
Well, mine for starters, so I'll likely be building some form of this for myself in the near future.

How are you handling large collections of data without some way to provide subsets of that data? If I can only pull 50 rows at a time (and my collection happens to be very large), then I need those 50 rows to be the right 50 rows, or as close as I can get.

Otherwise I'm going to be pulling X rows so I can filter out the Y that I need, etc.

All of that is totally "doable" with the current API, its just going to be something I build for myself.

**Comment by mesqueeb** [comment]
What kind of app are you building?
FetchAndAdd has an automatic limit of 50 docs. 
You can continue to call fetchAndAdd which will retrieve the next set of 50 docs each time.
Does this not satisfy your needs?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
