### ISSUE TITLE
Has anyone worked with VuexFire ?

### ISSUE THREAD

**Issue by mesqueeb** [mesqueeb/vuex-easy-firestore#64]
I have seen [VuexFire](https://github.com/posva/vuexfire) before, but I don't have much experience with it.

If anyone has worked with VuexFire before, please let me know down below what you thought of it compared to vuex-easy-firestore!

I'd love to know any differences you have noticed or if there are any features on VuexFire we could implement in here as well!

I believe vuex-easy-firestore's strong points are:
- great documentation
- simple setup
- easy to use
- very powerful customisation possible

I believe vuex-easy-firestore's weak points are:
- slight size overhead: I want to make it as lightweight as possible going forward!
- documentation is only in English
  - **please let me know (open an issue) if you want to contribute in another language!**
  - I would love Chinese, Spanish & French asap!

<sub>Vuex Easy Firestore was made with ♥ by Luca Ban.<br>If this library helped you in any way you can support me by buying me <a href="https://www.buymeacoffee.com/mesqueeb">a cup of coffee</a>.</sub>

**Comment by BenAHammond** [comment]
I've played with VuexFire but never built anything in production with it and not since it started supporting Firestore.

I'll say that I very much prefer the way `vuex-easy-firestore` ships with a clean mutation API OOB without needing to manually write it all. It saves me a lot of time while still keeping my code clean.

I do think this tool could use some improvements to the `sync` functionality/API. If I have a large collection of data that is all "syncable" I would like a better way to specify what it pulled and when.

**Comment by mesqueeb** [comment]
Hi @BenAHammond Thanks for the feedback.

Firestore makes it really easy to fetch docs with just `firebase.firestore().doc(path).get()`.
Is there something you can think of that I could implement in vuex-easy-firestore that could make it even easier for you? I try to think about it, but I never had an app that required several different paths that needed to be pulled at different times.

Please give me some more information or what kind of improvement you can think of! : D

**Comment by BenAHammond** [comment]
Personally I'd love to see a Paging API for the `sync` portion of the Collection API.

Specifically it would be nice to have the user's session automatically track the current paging details somehow for reuse on reload without having to program that all in manually.

Maybe as a plugin if not core functionality?

**Comment by BenAHammond** [comment]
Another thought: It would be nice to have a quick and simple way to query for a single `id` inside of a Collection. Preferably in a way that returns the in-memory version quickly or fetches the remote version if its not found.

Its a very, very common procedure to lookup an object by its id and iterating through all the time is inefficient.

**Comment by louisameline** [comment]
Pros: made by people from the Vuex team, inspires trust.
Cons: 1-way sync only, and lets you do all the calls to Firestore yourself, yuk.
Conclusion: will be deprecated in a few months ;)

**Comment by mesqueeb** [comment]
@louisameline what I mainly felt about about Vuex Fire is that it isn't made with love... :D
I felt no love at all.
I put a looot of love into vuex-easy-firestore. 💜
