### ISSUE TITLE
 dbRef.onSnapshot is not a function

### ISSUE THREAD

**Issue by torstah** [mesqueeb/vuex-easy-firestore#67]
Hey, 

would love to get this working. 

When trying this setup: 

```javascript
const userDataModule = {
  firestorePath: 'users/{userId}/displayName',
  firestoreRefType: 'collection', // or 'doc'
  moduleName: 'userData',
  statePropName: 'userDocs',
}
```

I keep getting: ` dbRef.onSnapshot is not a function`

Also, how to use this module with mapGetters?

**Comment by torstah** [comment]
Also using @latest @mesqueeb

**Comment by mesqueeb** [comment]
@torstah that's strange. I never had that error. Can you share your repo? Or can you show me the order in which you initialise firebase and the Vuex store. 

Map getters should be usable just as always. You can add getters to your module and map them like you normally would. 


<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by torstah** [comment]
Nevermind, I got things working now. 

Another question, how to deal with sorting directions? Ie `{orderBy: ['created_at']}` desc, and asc? 

Thanks!

**Comment by mesqueeb** [comment]
@torstah I'm eager to know what the error was. Maybe I can add some clarification to the documentation to prevent other users from making the same mistake.

For `orderBy` you can just set it in your vuex-easy-firestore module under `sync.orderBy` like so:
```js
const userDataModule = {
  firestorePath: 'users/{userId}/displayName',
  firestoreRefType: 'collection',
  moduleName: 'userData',
  statePropName: 'userDocs',
  sync: {
    orderBy: ['created_at', 'desc']
  }
}
```
See the documentation here: [Filters](https://mesqueeb.github.io/vuex-easy-firestore/extra-features.html#filters)

**Comment by torstah** [comment]
I think I just messed up my firestorePath, so maybe clarify the docs around that?

**Comment by mesqueeb** [comment]
I'm making some improvements to the firestorePath handling in next update. Thanks!

**Comment by torstah** [comment]
Hey, 

another thing. 
I'm using `dispatch("pahtToData/set"` to add a new documentation, and want it to be added to the top of the underlying list.  That list is rendered used using `dispatch('pahtToData/fetchAndAdd', {orderBy: ['created_at', 'desc']}` 

But the new doc is getting added to the end of that list, until I do another "fetchAndAdd". 
I have also tried to do a sync with default ordering and `dispatch('pahtToData/openDBChannel'` with the same results. 

Any hints?

**Comment by mesqueeb** [comment]
@torstah Your docs actually get saved in a JavaScript object, so I'm not sure how the order is reflected in your app.

First of all, just to be clear on your setup:
```js
  moduleName: 'userData',
  statePropName: 'userDocs',
```
Makes it so you do 
`dispatch('userData/fetchAndAdd', {orderBy: ['created_at', 'desc']}` right?

But how do you show the data?
It's saved in `store.state.userData.userDocs`, but this is a JavaScript object so has no specific order.

You could create a getter in your vuex-easy-firestore module with some sort option.

```js
const userDataModule = {
  firestorePath: 'users/{userId}/displayName',
  firestoreRefType: 'collection', // or 'doc'
  moduleName: 'userData',
  statePropName: 'userDocs',
  getters: {
    sortedUserDocs: (state, getters) => {
      return Object.values(state.userDocs).sort() // some sort function
    }
  }
}
```

**Comment by torstah** [comment]
Ah, of course. Thanks!

**Comment by mesqueeb** [comment]
I'm not sure what you mean? 
The difference between openDBChannel and fetchAndAdd is 
- openDBChannel is an open channel listening for changes from the Firestore server as well. 
- fetchAndAdd is a single time fetch.

Please clarify your question and I will explain even more. These questions are important for me to know where to improve my docs. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by torstah** [comment]
Hey again, 

still having issues here. 
When constructing a getter like this: 
`getters: {
    sortedIdeas: (state, getters) => {
      return Object.values(state.ideas).sort(function (a, b) { 
       return b.created_at.toMillis() - a.created_at.toMillis()
      }) 
    }
  },`

I get the error `vue.esm.js?efeb:591 [Vue warn]: Error in render: "TypeError: Cannot read property 'toMillis' of undefined"`

Seems like the timestamp object is not created yet? 

Any hints on how to sort a getter by created_at?

**Comment by mesqueeb** [comment]
@torstah 
You once told me you are not sure when to use sync (openDBChannel) and when to use fetch (fetchAndAdd).

Well I just rewrote the documentation on how to know which one to choose!
Check it here: [Query data](https://mesqueeb.github.io/vuex-easy-firestore/query-data.html)
