### ISSUE TITLE
[documentation] clarify the "doc order" of a collection

### ISSUE THREAD

**Issue by poornan** [mesqueeb/vuex-easy-firestore#69]
Below is my config. I have a collection that is synced by desc. but after server hook run, latest document get appended to the bottom.

```
const billsDataModule = {
  firestorePath: 'companies/{companyId}/bills',
  firestoreRefType: 'collection',
  moduleName: 'billsData',
  statePropName: 'bills',
  sync: {
    orderBy: ['timestamp', 'desc'],
    where: [['type', '==', process.env.NODE_ENV]]
  },
  serverChange: {
    addedHook: function (updateStore, doc, id, store, source, change) {
      updateStore(doc)
    },
    modifiedHook: function (updateStore, doc, id, store, source, change) {
      updateStore(doc)
    },
    removedHook: function (updateStore, doc, id, store, source, change) { updateStore(doc) }
  },
  getters: {
    getBillById: (state) => (id) => {
      return state.bills[id]
    }
  }
}
```

**Comment by mesqueeb** [comment]
The "order" depends on how you show the items in your Vue components.
Please provide me with the template part where you do your `v-for` and which state prop you point to.

**Comment by poornan** [comment]
Thank you very much. I've just understood how to use them.

**Comment by mesqueeb** [comment]
@joshua1 it’s just like the original poster’s example. 
```
orderBy: ['someField', 'asc']
```

Please note however that it might behave different, because this library stores the results in an object with the document id as key.

That means you'll need to write a client-side orderBy function inside a vuex-getter to show your collection in your wished order.

So I mean: setting orderBy in this library will retrieve the docs in that order, but are saved inside an object so will loose its order!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mesqueeb** [comment]
Clarified the doc order in the [new documentation](https://mesqueeb.github.io/vuex-easy-firestore/query-data.html#where-orderby-filters) on Querying data.

**Comment by mesqueeb** [comment]
---
After about two years of open source, I finally got accepted for Github Sponsors!

#### 💜 [github.com/sponsors/mesqueeb](https://github.com/sponsors/mesqueeb) 💜 

A little about me:
- I love open-source
- 6 months ago I got a son, and am trying to be an awesome father 😅
- I'm doing freelance work here and there as my main job

#### If anyone was helped with vuex-easy-firestore, **I'd greatly appreciate any support**!

> BTW, donations get's paid DOUBLE by GitHub! (they're alchemists... 🦾)

Going forward 👨🏼‍💻
- I got great plans for the future of vuex-easy-firestore going above and beyond!! Look forward to it!!
- On to many more years of open-sourcing! 🎉
