### ISSUE TITLE
Fetch single document

### ISSUE THREAD

**Issue by torstah** [mesqueeb/vuex-easy-firestore#70]
Hey again, 

how to best fetch a single document, for example in a route?
Do I need to do a `fetchAndAdd` with a filter for the doc id?
or could i use a the 'doc' mode?

Thanks

**Comment by mesqueeb** [comment]
depends on what you need.

- Do you want to create a vuex-easy-firestore module for that document? to make it easier to access in a lot of different components etc.
  → add the vuex-easy-firestore module and then choose between openDBChannel and fetchAndAdd
- do you just need it just once?
  → if you do have the vuex-easy-firestore module setup, but don't want to add it to the module's state, you can use [regular fetch](https://mesqueeb.github.io/vuex-easy-firestore/guide.html#fetching-docs-with-different-filters).
- do not want to make a vuex-easy-firestore module for it
  → Just manually access firestore and do it in the traditional way: `firebase.firestore().doc(path).get()` Nothing wrong with this!

#### does this answer your question?
it all depends a lot on what you want to do, what you think is a good fit for your app.

The main purpose of vuex-easy-firestore is to have a vuex-module automatically loaded up with firestore documents, and easily keep the two in sync by using my pre-made actions. lot's of edge-cases I haven't thought about that I'd love to hear more about! Then I can think where I can improve the library.

**Comment by torstah** [comment]
Ah ok, so mix them both. 

I thought this also could be used for fetching single docs, for example in deep links /site/doc/docId....

Thanks

**Comment by mesqueeb** [comment]
@torstah I've closed the issue, but we can continue the discussion. What do you mean with
> I thought this also could be used for fetching single docs, for example in deep links /site/doc/docId....

How do you feel that vuex-easy-firestore could add value over the regular `firebase.firestore().doc(path).get()` method to retrieve a single doc?

I'm not seeing it... o(≧▽≦)o

**Comment by mesqueeb** [comment]
---
After about two years of open source, I finally got accepted for Github Sponsors!

#### 💜 [github.com/sponsors/mesqueeb](https://github.com/sponsors/mesqueeb) 💜 

A little about me:
- I love open-source
- 6 months ago I got a son, and am trying to be an awesome father 😅
- I'm doing freelance work here and there as my main job

#### If anyone was helped with vuex-easy-firestore, **I'd greatly appreciate any support**!

> BTW, donations get's paid DOUBLE by GitHub! (they're alchemists... 🦾)

Going forward 👨🏼‍💻
- I got great plans for the future of vuex-easy-firestore going above and beyond!! Look forward to it!!
- On to many more years of open-sourcing! 🎉

**Comment by makeitTim** [comment]
**So, how do you fetch a single document?**

I have a User document, it contains a `currentCompany` with an id for a company.

I have a Company document. The core functionality of the app will be changing the data of that single document. It will definitely have maps, likely sub-collections, but pretty much everything is there.

(Multiple users will have permissions to edit a Company, and a user cna switch between Company they have access too, but the main functionality will be editing just one Company.)

I've been playing with lots of stuff, like `firestorePath: 'users/{id}',`, but nothing works and that even creates "{id}" items in my firestore!

What would the modules look like? Or am I missing the point here, and this vuex-easy-firestore library (which looks awesome by the way) is not much use for me?

**Comment by mesqueeb** [comment]
> I've been playing with lots of stuff, like firestorePath: 'users/{id}',, but nothing works and that even creates "{id}" items in my firestore!
 
@makeitTim if you are seeing `{id}` in firestore, that means you are not passing the path variable when reading the data.

did you read the documentation on path variables?
https://mesqueeb.github.io/vuex-easy-firestore/extra-features.html#variables-for-firestorepath-or-clauses

Let me know if you're stuck, and feel free to open a new issue!

<sub>--<br>Vuex Easy Firestore was made with ♥ by Luca Ban.<br>If you use this library in your projects, you can support the maintenance of this library by a small <a href="https://github.com/sponsors/mesqueeb">contribution via Github 💜</a>.<br>You can also reach out <a href="https://twitter.com/mesqueeb">on twitter</a> if you want a one-on-one coding review/lesson. 🦜</sub>

**Comment by makeitTim** [comment]
No, I hadn't read that part of the documentation. Although I'd gone through "Read data" a dozen times.

Thanks, I think I'm getting this working!

**Comment by makeitTim** [comment]
I'm still having trouble with something I feel would be a quick answer.

When a user logs in, I go to connect their User state with firebase. That User has a current Company id that I also want to load. I can't seem to figure out how to do it, one then the other. Right now I am trying to do it in my own store index action:

```
    signInUser({ dispatch, commit }, userId: string) {
      dispatch('User/openDBChannel', { pathVariables: { id: userId} } )
      dispatch('Company/openDBChannel', { pathVariables: { id: state.user.currentCompany} } )
    },
```

But obviously state.user isn't anything (I just copied code over from the login component, but wasn't working there either). I don't know if it should be a watcher, or some async trick? dispatch() seems to resolve before user data exists fully.

**Comment by mesqueeb** [comment]
@makeitTim
is `User` a document?

try logging `state.User.data.currentCompany` after the `await dispatch('User/openDBChannel...`

the snippet you have is the same as the example here:
https://mesqueeb.github.io/vuex-easy-firestore/extra-features.html#variables-for-firestorepath-or-clauses

not 100% sure why it won't work. Perhaps try waiting for an extra `ms`?

**Comment by makeitTim** [comment]
Thanks.... TypeScript wasn't understanding the state without the right decoration? I got it working by just defining what the module state sort of looked like. I feel there might be a better way, but this seems to work:

```
  state: {
    isLoading: false,
    User: { data: {} as User },
    Company: { data: {} as Company }
  },
 ...
  actions: {
    async signInUser ({ dispatch, getters }, userId: string) {
      await dispatch('User/openDBChannel', { pathVariables: { id: userId } })
      dispatch('Company/openDBChannel', { pathVariables: { id: getters.user.currentCompany } })
    },
    ...
  },
  getters: {
    user (state) {
      return state.User.data
    },
    company (state) {
      return state.Company.data
    }
  }
```

**Comment by mesqueeb** [comment]
@makeitTim Yeah, I see. Happy you solved it.

BTW, I'm working on a complete rewrite for version 2.0 and it's going to have much better typescript support.

<sub>--<br>Vuex Easy Firestore was made with ♥ by Luca Ban.<br>If you use this library in your projects, you can support the maintenance of this library by a small <a href="https://github.com/sponsors/mesqueeb">contribution via Github 💜</a>.<br>You can also reach out <a href="https://twitter.com/mesqueeb">on twitter</a> if you want a one-on-one coding review/lesson. 🦜</sub>

**Comment by makeitTim** [comment]
Sounds awesome.

My method there does create these errors. Presumably it's not the correct way to access the module state.
```
vuex.esm.js?2f62:625 [vuex] state field "User" was overridden by a module with the same name at "User"
eval @ vuex.esm.js?2f62:625
...
vuex.esm.js?2f62:625 [vuex] state field "Company" was overridden by a module with the same name at "Company"
``

**Comment by mesqueeb** [comment]
@makeitTim yes, that error is because of your implementation. You could improve your implementation by defining only the type of your store state without actually setting those default props in your javascript. But it's hardly worth the hassle.
I'm working on version 2.0 now and it'll be much better and a bit different anyway. 😉
