### ISSUE TITLE
make sure openDBChannel cannot be opened twice with the same path & conditions

### ISSUE THREAD

**Issue by eneskaya** [mesqueeb/vuex-easy-firestore#71]
First and foremost, great package. I have a question about the `openDBChannel` action: When I use `openDBChannel` multiple times for the same path, e.g. `users/{userId}` does it really register a new `onSnapshot` listener every time? So, let's say 5 components are interested in real-time updates (but not rendered at the same time) and in there `created` method they call the `openDBChannel` method, do I have 5 listeners now? And if so, what's the performance impact, if any?

**Comment by mesqueeb** [comment]
Hi, if you have 5 separate modules, then yes, five listeners are open.

If you open the same listener (with same firestore path) in five different components I think there will only be one listener, but this is more related to the firebase library. 

openDBChannel uses the firebase `onSnapshot` under the hood. If your components get destroyed later and you want to stop listening (for performance reasons) you can do `closeDBChannel` which will call firestore `unsubscribe` event under the hood. 

For the rest i guess it’s just a matter if the firebase `onSnapshot` is performant or not... the only thing vuex-easy-firestore does is add the docs that come in to the vuex module, so no performance issues there I think!

I will close this issue for now but feel free to continue the discussion! :D

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by eneskaya** [comment]
Thank you for your answer, makes sense. I was just wondering if the plugin handles subscriptions to the same `onSnapshot` query (maybe this could be a consideration for future versions 😄)

**Comment by mesqueeb** [comment]
It’s kinda out of my hands though. 😖 firestore handles their listeners internally in some magical way. 😄

I have no control over if they are using a single query/subscription or not...

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by eneskaya** [comment]
Is Firebase optimizing it really? I'm not sure if they're doing it on the frontend-side. I know they do it server-side.

What one has control over is to remember if there are `onSnapshot` listeners registered for one module, say you call `openDBChannel` for a module with the firestorePath `/users/{userId}` with `userId = ABC`. What could be done internally is to keep the listener for this path somewhere in the state, let's say `listeners: { [PATH] : [LISTENER] }` (or some other way, doesn't really matter). Now when another `openDBChannel` happens with the same `userId` we could check if this specific listener is already in memory, and don't call `onSnapshot` again.

Just a thought here, I'm really not sure if this is necessary.

**Comment by mesqueeb** [comment]
Actually i think i can easily test this by executing firestore’s native onSnapshot listener on the same path twice but with different console.logs in the promise. Then see if two listeners are open or not. 

I’ll test it and let you know. 

But honestly, I don’t think this is optimisation my library should be responsible for. Executing openDBChannel isn't the intended use case either way, and I think it's not good to bloat my code base for the few cases that someone makes such a mistake. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mesqueeb** [comment]
@eneskaya Trying out some things with setting up native `onSnapshot` listeners, it seems to me that not only does Firebase *not* optimise performance by preventing the same listener to be opened twice, I'm even seeing all documents being re-triggered after adding just one to the collection on the server side...

I'm not sure what's causing this latter problem, but the first one should definitely be prevented by my library I guess...

I'm still not a fan of having open too many listeners, as I'm unsure just how heavy this is for the front-end client to handle... In most cases [fetchAndAdd](https://mesqueeb.github.io/vuex-easy-firestore/guide.html#fetching-docs-with-different-filters) is the better way to go. But I just now realised that custom path variables are not set when openDBChannel is not executed once.

I'm planning some improvements for fetchAndAdd explained here: #100

**Comment by mesqueeb** [comment]
@eneskaya @coolhand79

When `openDBChannel` is called there's currently only a single reference to that saved to be able to unsubscribe again.
The current logic can be found here:
https://github.com/mesqueeb/vuex-easy-firestore/blob/master/src/module/actions.ts#L437
```js
state._sync.unsubscribe = unsubscribe
```
it would overwrite previous openDBChannels, making it unable to close them again when having open 2 channels.

So I just need to change `state._sync.unsubscribe` to an object and save each channel with an identifier. Then I can also check if there already is a channel open at that certain identifier.

Any ideas on what kind of identifiers to use?
Do you guys have a manual work-around in place?

**Comment by eneskaya** [comment]
@mesqueeb Sorry for late reply.

The way we do it now (which I don't like) is having a class which hashes the path with the [btoa](https://www.w3schools.com/jsref/met_win_btoa.asp) method, so let's say we want the `onSnapshot` listener for the *users* collection and the document ID 1. Then I would convert the path to an array like this: `['users', 1]` and use `btoa(['users', 1])` as and identifier. But we also need to take into account the `where` and `orderBy` params, as they could require different listeners to be registered. So, we could just add those to the first array: `['users', 1, ...where, ...orderBy]`, which would result in a unique identifier for this very path. 

Makes sense? Really not sure if this is best practice though 😅

**Comment by mesqueeb** [comment]
Hi @eneskaya 
I have just pushed version `1.30` where I have made it so `openDBChannel` cannot be executed twice.

Please open your DBChannel like so:
```js
  try {
    await store.dispatch('multipleOpenDBChannels/openDBChannel')
  } catch (e) {
    console.error(e)
  }
```
If something was already open with the same where / orderBy or pathVariables, you'll get an error.

If it is ok for you, please close this issue! ♡

<sub>--<br>Vuex Easy Firestore was made with ♥ by Luca Ban.<br>If this library helped you in any way you can support me by buying me <a href="https://www.buymeacoffee.com/mesqueeb">a cup of coffee</a>.</sub>

**Comment by eneskaya** [comment]
Great!

**Comment by mesqueeb** [comment]
FYI
https://github.com/mesqueeb/vuex-easy-firestore/issues/152#issuecomment-474613839

**Comment by mesqueeb** [comment]
@eneskaya Do you use this with `openDBChannel` ?
```js
 catch (e) {
    console.error(e)
  }
```
or do you refrain from catching the error entirely?

**Comment by eneskaya** [comment]
I use it with the catch block, yes.

**Comment by mesqueeb** [comment]
@eneskaya If a channel is already open on openDBChannel, it no longer throw an error in the latest version. The promise just resolves right away. I don't believe this will cause any issue, but let me know if it does!
