### ISSUE TITLE
patch operations revert

### ISSUE THREAD

**Issue by zabaat** [mesqueeb/vuex-easy-firestore#72]
this is probably going to be hard to explain, sorry. Please let me know what else I should send?

I've uploaded a short video for your reference
http://www.youtube.com/watch?v=-KZ5UvPyGVM

```
patchHook(updateStore, doc, store) {
                const temp = {}
                // lodash.set(temp, doc.key, doc.val)
                temp[doc.key] = doc.val
                temp.id = doc.id
                console.log('updating item before patch!', temp)
                return updateStore(temp)
            }
```

that console prints
```"{
"id":"wXtIWV2ACo7HtAkDkYNn",
  "allergy": {
    "dairy": false,
    "dairy_o": true,
    "egg": true,
    "egg_o": false,
    "fish": false,
    "fish_o": true,
    "gluten": true,
    "gluten_o": false,
    "peanuts": true,
    "peanuts_o": true,
    "shellfish": false,
    "shellfish_o": false,
    "soy": true,
    "soy_o": true,
    "tree_nut": false,
    "tree_nut_o": false,
    "wheat": true,
    "wheat_o": true
  }
}"
```

my dispatch is inside a components method:
```
        vendorUpdateItem({ key }) {
            console.log('updating item!', this.item.id, key, lodash.get(this.item, key))
            this.$store.dispatch(`item/patch`, { id: this.item.id, key, val: lodash.get(this.item, key) })
        },
```

**Comment by mesqueeb** [comment]
Hi Zabaat 
Easiest is sharing your repo. (Can also be per email if you delete node_modules folder.) 

I think it might be a problem with the single source of truth especially with check boxes. 

Can you post your whole vue component for these check boxes? I need to see the change or click event and what actions you take there. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by zabaat** [comment]
If I can start with this, that would be probably be faster, it's not very portable at the moment.
i'll work on a minimum viable repo for reporting if this doesn't work. 

I am migrating from RTDB and vuexfire, which did work with all this for some reason.
Thanks!

I am using the quasar-framework for my components v17.12
```
                            <q-checkbox v-for="(val, key) in item.allergy"
                                        :key="key"
                                        class="checkboxes-list--item"
                                        v-model="item.allergy[key]"
                                        @input="val => { item.allergy[key] = val; vendorUpdateItem({key:`allergy.${key}`}) }"
                                        :label="daClean(key)" />```

here is the update function:
```
        vendorUpdateItem({ key }) {
            console.log('updating item!', this.item.id, key, lodash.get(this.item, key))
            this.$store.dispatch(`item/patch`, { id: this.item.id, key, val: lodash.get(this.item, key) })
            // this.$store.dispatch(`entries/updateItem`, { itemId: this.item.id, key, val: lodash.get(this.item, key) })
        },
```


and my itemModule file
```

export default {
    item: {
        firestorePath: 'item/',
        // The path to a collection or doc in firestore. You can use `{userId}` which will be replaced with the user Id.
        firestoreRefType: 'collection',
        // `'collection'` or `'doc'`. Depending on your `firestorePath`.
        moduleName: 'item',
        // The module name. Can be nested, eg. `'user/items'`
        statePropName: 'itemList',
        // The name of the property where the docs or doc will be synced to. If left blank it will be synced on the state of the module.

        // Related to the 2-way sync:
        sync: {
            // where: [],
            // orderBy: [],
            // fillables: [],
            // guard: [],
            // HOOKS for local changes:
            // eslint-disable-next-line
            insertHook(updateStore, doc, store) {
                const defaultItem = {
                    id: doc.id,
                    category: doc.category,
                    desc: 'Infinite Pancakes',
                    name: 'Pancake Tower',
                    price: '10000',
                    showInStock: false,
                    pub: false,
                    optionConfig: {
                        customizations: true,
                    },
                    allergy: {
                        dairy: false,
                        dairy_o: false,
                        egg: false,
                        egg_o: false,
                        fish: false,
                        fish_o: false,
                        gluten: true,
                        gluten_o: true,
                        peanuts: false,
                        peanuts_o: false,
                        shellfish: false,
                        shellfish_o: false,
                        soy: false,
                        soy_o: false,
                        tree_nut: false,
                        tree_nut_o: false,
                        wheat: false,
                        wheat_o: false,
                    },
                    diet: {
                        halal: false,
                        kosher: false,
                        veg: false,
                        veg_o: false,
                        halal_o: false,
                        kosher_o: false,
                        vegan_o: false,
                        vegan: false,
                    },
                    vendorId: doc.vendorId,
                }
                return updateStore(defaultItem)
            },
            // eslint-disable-next-line
            patchHook(updateStore, doc, store) {
                const temp = {}
                // lodash.set(temp, doc.key, doc.val)
                temp[doc.key] = doc.val
                temp.id = doc.id
                console.log('updating item before patch!', temp)
                console.dir(temp)
                console.log(JSON.stringify(temp, null, 2))
                return updateStore(temp)
            },
            // eslint-disable-next-line
            deleteHook(updateStore, id, store) {
                return updateStore(id)
            },
            // for batches
            // eslint-disable-next-line
            insertBatchHook(updateStore, docs, store) {
                return updateStore(docs)
            },
            // eslint-disable-next-line
            patchBatchHook(updateStore, doc, ids, store) {
                return updateStore(doc, ids)
            },
            // eslint-disable-next-line
            deleteBatchHook(updateStore, ids, store) {
                return updateStore(ids)
            },
        },

        // // When items on the server side are changed:
        // serverChange: {
        //     defaultValues: {},
        //     // HOOKS for changes on SERVER:
        //     // eslint-disable-next-line
        //     addedHook(updateStore, doc, id, store, source, change) {
        //         return updateStore(doc)
        //     },
        //     // eslint-disable-next-line
        //     modifiedHook(updateStore, doc, id, store, source, change) {
        //         return updateStore(doc)
        //     },
        //     // eslint-disable-next-line
        //     removedHook(updateStore, doc, id, store, source, change) {
        //         return updateStore(doc)
        //     },
        // },

        // // When items are fetched through `dispatch('module/fetch', filters)`.
        // fetch: {
        //     // The max amount of documents to be fetched. Defaults to 50.
        //     docLimit: 50,
        // },

        // You can also add custom state/getters/mutations/actions. These will be added to your module.
        // state: {},
        // getters: {},
        // mutations: {},
        // actions: {},
    },
}
```

**Comment by mesqueeb** [comment]
Can you please add tripple ``` in front and behind the code block?
I think you forgot to close your blocks and **the formatting is off** making it difficult to read.

**Comment by zabaat** [comment]
Thank you for telling me how to do that!!! I never got around to figuring that out. I will fix, also I might have found the problem, checking now.

**Comment by mesqueeb** [comment]
I see a lot of problems with your code.
I already know your main problem and will 
```js
<q-checkbox v-for="(val, key) in item.allergy" 
```
Do not use `v-for` with q-checkbox! I have used Quasar a lot. You'd want to wrap each checkbox inside a `div` like so:
```js
<div v-for="(val, key) in item.allergy" :key="key">
   <q-checkbox 
    v-model="...
```

There's more I can tell you, especially on how to sync this model with vuex-easy-firestore. Please give me some time, I will follow up with an extra comment.

**Comment by zabaat** [comment]
I am very relieved you are a fellow Quasar user!
And wow, I had no idea about the q-checkbox for loop issue, I will try immediately!
What madness necessitates that? I wonder if I am missing things like that on more of their components?

Thank you for your time!!

**Comment by mesqueeb** [comment]
> And wow, I had no idea about the q-checkbox for loop issue, I will try immediately!
What madness necessitates that? I wonder if I am missing things like that on more of their components?

Quasar says when you want to use checkboxes in a group, to use [q-option-group](https://quasar-framework.org/components/option-group.html#Basic-Usage), don't use v-for with q-checkbox, as there are even no examples showing this behaviour.

Even though it was possible UI wise in your case, it will mess up the **source of truth** for the data of those checkboxes. That's where your problems come from.

### solution:
There are a couple of possibilities, but I suggested `v-for` with a `div`, and a `q-checkbox inside`, **to make sure we have control over which elements are synced.**

As you said, we want to avoid having to sync the whole `allergy` object every time and want to limit our api call to sync just the relevant checkbox.

See here my solution as GIF:

![2018-11-13 16 47 25](https://user-images.githubusercontent.com/3253920/48398479-3105a700-e764-11e8-961b-3e15f7ae5c52.gif)

And the code:
```js
<div v-for="key in Object.keys(item.allergy).sort()" :key="key">
  <q-checkbox
    v-model="item.allergy[key]"
    :label="key"
    @input="val => { $store.dispatch('user/menulist/patch', {id: item.id, allergy: {[key]: val}}) }"
  />
</div>
```
You see, it's a very simple and beautiful solution.

Please close the issue if this resolves your problem!

**Comment by mesqueeb** [comment]
Several things you should avoid is:

`return this.$store.dispatch('item/patch', this.item)` this will do a full patch of all fields and thus is heavy for bandwidth

in your `insertHook` you have a huge `defaultItem` that you sync to the server.
It's imo better to set these as "[default values set after server retrieval](https://mesqueeb.github.io/vuex-easy-firestore/extra-features.html#defaultvalues-set-after-server-retrieval)" and only sync to the server if a value is updated. That way you don't clutter your server with useless default data and again you use less bandwidth on the initial insert.

**Comment by zabaat** [comment]
I deeply appreciate your extra work here, please enjoy your coffee!
I'll implement these fixes soon and let you know.

**Comment by mesqueeb** [comment]
@zabaat thanks for the coffee!!

PS, also avoid wrapper functions that add no value:
```js
vendorUpdateItem({ key }) {
    return this.$store.dispatch(`item/patch`, this.item)
},
```
and you can delete any vuex-easy-firestore config you are not using to keep your codebase clean:
```js
patchHook(updateStore, doc, store) {
    return updateStore(doc)
},
```

**Comment by mesqueeb** [comment]
@zabaat Did it work?

**Comment by zabaat** [comment]
Sorry, I'm just getting back to this tonight. It's my passion project, so I'll be sure to let you know :)

**Comment by zabaat** [comment]
@mesqueeb thank you! everything worked great and I appreciate your code review as well. I'm out of practice. 
I will give the lazy sync a shot as well soon.

**Comment by mesqueeb** [comment]
For anyone working with HOOKS, there has been a small (non-breaking) change to their behaviour.

Please read about it in the [latest release](https://github.com/mesqueeb/vuex-easy-firestore/releases/tag/v1.26.0).
