### ISSUE TITLE
Setting empty object doesn't sync properly

### ISSUE THREAD

**Issue by Miguel-Herrero** [mesqueeb/vuex-easy-firestore#73]
Hi! First of all, thanks for this great library @mesqueeb 

I'm trying to build a kind of restaurant management system with Vuex and Firestore. But when I update the shipping basket/_checkout_, although correctly updated in Vuex, it's not updated rightly in Firestore and it returns the old items.

### Sample of Checkouts Firestore collection
```
checkouts = {
    "vlVVfyVtXFRmpIqVqNPV": {
        id: "vlVVfyVtXFRmpIqVqNPV",
        table: 2,
        totalPrice: 23,
        items: {
            "87jHxITagtdioYowShp2": {
                id: "87jHxITagtdioYowShp2",
                name: "Cake",
                units: 2,
                price: 2.5,
                totalPrice: 5
            },
            "A7k23pIRr4VqWJLbFHcb": {
                id: "A7k23pIRr4VqWJLbFHcb",
                name: "Orange Juice",
                units: 1,
                price: 3,
                totalPrice: 3
            }
        }
    }
}
```

### Expected behaviour
When I remove an item (because I added by mistake), I do:
```
// Remove the product because it has only 1 unit
// Either do `delete updatedCheckout.items["A7k23pIRr4VqWJLbFHcb"]`
// or Vue.delete(updatedCheckout.items,"A7k23pIRr4VqWJLbFHcb" )
// so I end up with:
checkout = {
    id: "vlVVfyVtXFRmpIqVqNPV",
    table: 2,
    totalPrice: 23,
    items: {
        "87jHxITagtdioYowShp2": {
            id: "87jHxITagtdioYowShp2",
            name: "Cake",
            units: 2,
            price: 2.5,
            totalPrice: 5
        }
    }
}

this.$store.dispatch('chargeData/patch', checkout)
```

`checkoutsData/PATCH_DOC` is executed twice, one with the document with one item, but the second (that comes from the server) has the two items, so I end with not being able to remove an item!

I think that it's because Firestore doesn't get along with empty objects (it happens the same if I want to delete all items by dispatching `items: {}`). I've read something about a `merge`param mentioned [here](https://github.com/firebase/firebase-js-sdk/issues/1371) that maybe could help.

I would appreciate any help on how could I set empty objects and being properly sync'ed with Firestore.

Thank you very much @mesqueeb

**Comment by mesqueeb** [comment]
Yes exactly. This is intended behaviour. Firestore makes you use [a special class](https://firebase.google.com/docs/firestore/manage-data/delete-data#fields) to delete data from fields inside a document.

I have made it so that you can do this in vuex-easy-firestore by using the `delete` action with a nested path. See the [documentation here](https://mesqueeb.github.io/vuex-easy-firestore/guide.html#collection-mode).

In your case this would be:
```js
const checkoutId = 'vlVVfyVtXFRmpIqVqNPV '
const itemId = 'A7k23pIRr4VqWJLbFHcb'
this.$store.dispatch('chargeData/patch', `${checkoutId}.items.${itemId}`)
```

This action will actually take care of deleting the prop from the vue store with Vue.delete and also properly sync to firestore! 😄 

Check it out, and let me know how it goes!

**Comment by Miguel-Herrero** [comment]
Dear @mesqueeb Thank you very much! It worked like a charm!! You made my day 😄 

I must confess that I read that part of your documentation, but I didn't fully understand it or its Firestore consequences. Besides I tried the Firestore special class, but it didn't work (it changed the type of the field)

Keep the great work of this library!

**Comment by mesqueeb** [comment]
@Miguel-Herrero thank you so much!!!! 
And now that you mention it, I will update this part in the documentation a little bit to clarify 😉

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
