### ISSUE TITLE
Quasar Support

### ISSUE THREAD

**Issue by Theorian** [mesqueeb/vuex-easy-firestore#75]
I’ve installed and configured but cannot seem to call dispatch from my modules in quasar. Any ideas

**Comment by mesqueeb** [comment]
Dear Theorian. Did you solve the issue? 
I might be because of the order Quasar instantiates Firestore and Vuex.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by zabaat** [comment]
@Theorian I am currently using this with Quasar 0.17.18 and vuex with no problems, it was only a few minutes to install. That said, it was absolute hell to get vuexfire working so I had experience with it previously.

If you are having the same problems I did, make a .js plugin file (see quasar documentation) where you store your firebase config and start the connection to firebase. Then export the initialized app in that file.

Then import that file into your index.js vuex store, this will cause some heartache, and is why my partner currently hates quasar but it works around the issue okay.

I am sure the below could be cleaned up quite a bit but here are some examples

shrimp.js
```js
import firebase from 'firebase/app'
import 'firebase/auth'
import 'firebase/database'
import 'firebase/firestore'
import 'firebase/storage'

const fbConfig = {
        apiKey: 'xxx,
        authDomain: 'xxx,
        databaseURL: 'xxx',
        projectId: 'xxxx',
    }
const fbAppz = firebase.initializeApp(fbConfig)

export const fbApp = fbAppz
export const FirebaseLib = firebase
```

vuex index.js
```js
import Vue from 'vue'
import Vuex from 'vuex'
import { FirebaseLib } from '../plugins/shrimp'

import item from './modules/firestore/item'
import mod from './modules/firestore/mod'

const firestore = FirebaseLib.firestore()
firestore.settings({ timestampsInSnapshots: true })

const firestoreModules = createEasyFirestore(
    [ ingredient.ingredient, mod.mod],
    { logging: true, FirebaseDependency: FirebaseLib } // pass Firebase like this. Mind the Capital F!
)
Vue.use(Vuex)

const store = new Vuex.Store({ modules, mutations: firebaseMutations, plugins: [firestoreModules] })

export default store

```

**Comment by mesqueeb** [comment]
@zabaat Why are you giving advice on how to use `vuexFire` in the repo of `vuex-easy-firestore`? I feel this is a bit off-topic. (´▽｀*)
