### ISSUE TITLE
[Feature] Support for 'arrayUnion'

### ISSUE THREAD

**Issue by zabaat** [mesqueeb/vuex-easy-firestore#77]
https://firebase.google.com/docs/firestore/manage-data/add-data#update_elements_in_an_array

Specifically 'arrayUnion' would be useful.

**Comment by mesqueeb** [comment]
Agreed. I will work on implementing this ASAP.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mesqueeb** [comment]
@zabaat Since it's already implemented I'll close this issue. Feel free to re-open and continue the discussion if it's not what you wanted!
