### ISSUE TITLE
[documentation] clarify deletion of sub-props

### ISSUE THREAD

**Issue by mesqueeb** [mesqueeb/vuex-easy-firestore#78]
#73

**Comment by mesqueeb** [comment]
@Miguel-Herrero
I clarified the [documentation on deleting fields](https://mesqueeb.github.io/vuex-easy-firestore/firestore-fields-and-functions.html#delete-fields).

Is this more clear to you now? : )

**Comment by Miguel-Herrero** [comment]
Superb @mesqueeb Much more clear now!
Thanks for your work!
