### ISSUE TITLE
Serverchange hooks

### ISSUE THREAD

**Issue by thokkane** [mesqueeb/vuex-easy-firestore#80]
When making changes to data in firestore (updating a data attribute via the database view in firebase), i dont see the serverChange.modifiedHook firing. Here's the module code. Is this misconfigured?

```javascript
const module = {
    firestorePath: 'items',
    firestoreRefType: 'collection', 
    moduleName: 'items',
    statePropName: 'docs',
    serverChange: {
        modifiedHook: function (updateStore, doc, id, store, source, change) { console.log("modified");  }
    }
}
```

**Comment by mesqueeb** [comment]
@thokkane should be alright! 
I don't have a good test environment for hooks because of the Firestore mock i'm using. So it's possible there's a bug!!! 

I'll have time to check tomorrow and will post back here. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by thokkane** [comment]
@mesqueeb thanks for taking a look at this! 
Btw, the library is awesome.

**Comment by mesqueeb** [comment]
I did find a bug with "doc" mode (as opposed to "collection" mode) which I'm gonna fix asap. But no bugs found on "collection" mode, so I'm confused why your console is not logging!

**Comment by mesqueeb** [comment]
@thokkane Could you let me know if you still have problems? I think there are no hook-related bugs, so i'll close it for now.

Feel free to open again and continue the discussion!

**Comment by thokkane** [comment]
@mesqueeb thanks! It works fine. User error: I had disabled the openDBChannel call.

**Comment by mesqueeb** [comment]
Ok i’m glad!!!
Check out the release notes for latest info as well! 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mesqueeb** [comment]
For anyone working with HOOKS, there has been a small (non-breaking) change to their behaviour.

Please read about it in the [latest release](https://github.com/mesqueeb/vuex-easy-firestore/releases/tag/v1.26.0).
