### ISSUE TITLE
How to disable auto-generated fields "id" // "updated_at" // "updated_by"

### ISSUE THREAD

**Issue by l2aelba** [mesqueeb/vuex-easy-firestore#83]
Some reason I have to make some **anonymous** database :)

I don't think I can do:

``` js
sync: {
   fillables: ['id', 'updated_at', 'updated_by'],
   guard: ['id', 'updated_at', 'updated_by']
}
```

**Comment by mesqueeb** [comment]
Hi. The functionality to disable these is not implemented yet.. 

That being said it's not difficult to do so, so just give me 1 hour and i'll update the library. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by l2aelba** [comment]
@mesqueeb Let do it please and good job so far !

**Comment by mesqueeb** [comment]
Sorry I was trying to do it smart. Then started c/o factoring the code base for this. Then stumbled upon some bugs. Eventually cost me the whole day haha. I'm almost done. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mesqueeb** [comment]
I updated the library so you can now do 
```js
sync: {
   guard: ['id', 'updated_at', 'updated_by']
}
```
and it will work as expected.

Please try `npm i vuex-easy-firestore@latest` and let me know how it goes.
If it solves your issue please close!

Please note you don't need to add it as a fillable in case you add it as a guard:

### a short overview:
- 0 fillables = sync everything
- 1 or more fillables = sync only those props
- guard = no matter 0 or more fillables, guard fields will not by synced either way

**Comment by l2aelba** [comment]
Tested and its work!
So fast you are, thanks so much!

**Comment by l2aelba** [comment]
@mesqueeb 

I think I found a bug (or not sure)

When I guarding the `id` for prevent auto-generated

```js
createEasyFirestore({
  firestorePath: 'users/{userId}',
  firestoreRefType: 'doc',
  moduleName: 'user',
  sync: {
    guard: ['id']
  },
  serverChange: {
    modifiedHook: (updateStore, doc, id, store, source, change) => {
      console.log('modifiedHook')
      return updateStore(doc)
    }
  }
})
```

Then when I do
```
dispatch('user/set', data)
````

so its can not hook the `serverChange.modifiedHook` 

But when I removed `id` from `sync.guard` it is ok

**Comment by mesqueeb** [comment]
@l2aelba it was not a bug, it seems this is firestore's behaviour.
I have explained [here in this issue](https://github.com/mesqueeb/vuex-easy-firestore/issues/95).
