### ISSUE TITLE
[Bug] where filter on fetchAndAdd

### ISSUE THREAD

**Issue by mesqueeb** [mesqueeb/vuex-easy-firestore#85]
https://github.com/mesqueeb/vuex-easy-firestore/issues/79#issuecomment-442263976

**Comment by mesqueeb** [comment]
@coolhand79
I'm having troubling finding where the error is.

If you look at the source code here, I'm just passing the where filter on to the firebase api:
https://github.com/mesqueeb/vuex-easy-firestore/blob/master/src/module/actions.ts#L170

Can you confirm that the bug does not occur on a regular `get()` call?
Please try something like `collectionRef().where().get().then(querySnapshot => {`

**Comment by coolhand79** [comment]
Sure... 

this works:
```javascript
db.collection("cities")
    .where(
       "regionRefs",
       "array-contains",
       db.doc(`/regions/${to.params.regionId}`)
    )
    .get()
    .then(querySnapshot => {
    querySnapshot.docs.forEach(doc => {
        console.log(doc.get("name"));
    });
});
````

whereas, this:
```javascript
store
.dispatch("cities/fetchAndAdd", {
whereFilters: [
    [
    "regionRefs",
    "array-contains",
    db.doc(`/regions/${to.params.regionId}`)
    ]
]
})
```

results in `TypeError: Converting circular structure to JSON`

**Comment by coolhand79** [comment]
It appears to be line 163 where it is failing. See here: https://cl.ly/80d1a7d95518

**Comment by mesqueeb** [comment]
@coolhand79 oh ok, I got it! I can't use that as an identifier because I can't JSON.stringify it I see now. 

Ok let me push a bug fix real quick. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mesqueeb** [comment]
@coolhand79 Should be fixed in latest version.

Please try `npm i vuex-easy-firestore@latest`
and let me know!

If it is fixed, please close the issue! ♡

**Comment by coolhand79** [comment]
Looks good! But I don't seem to have permission to close issues.

**Comment by mesqueeb** [comment]
Hehehe, I forgot I was the one who opened this!! XD

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
