### ISSUE TITLE
Does it possible to use where : ['users.{uid}.permission', '==', true] ?

### ISSUE THREAD

**Issue by l2aelba** [mesqueeb/vuex-easy-firestore#86]
I am not sure about we can do something like this in **first param** ?

```js
// dispatch('hello/openDBChannel', { uid: user.uid })
sync: {
   where: [
       ['users.{uid}.permission', '==', true]
   ]
}
```

Because when I try with normal string `['users.abc123.permission', '==', true]` and its work.

**Comment by l2aelba** [comment]
@mesqueeb Thanks so much, I hope this would be implemented ASAP. Cheer!

**Comment by mesqueeb** [comment]
Hi, it's possible now in latest version!
Please try `npm i vuex-easy-firestore@latest`

**Comment by coolhand79** [comment]
I think this fix may be causing a new bug where I get `TypeError: pathPiece.match is not a function` when I have a filter like so: `["isActive", "==", true]`

https://cl.ly/a03df6d5f1cc

**Comment by mesqueeb** [comment]
@coolhand79 I'm so sorry. Fixed it now!

Please try `npm i vuex-easy-firestore@latest`
and let me know!

If it is fixed, please close the issue! ♡

**Comment by coolhand79** [comment]
Works for me!

**Comment by l2aelba** [comment]
@mesqueeb You are rock!
But {userId} is undefined right? (Just ask)

**Comment by mesqueeb** [comment]
@l2aelba yes you can!!! 
I made it super flexible. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by l2aelba** [comment]
@mesqueeb , I'm not sure `{userId}` is defined. Hard to debug with that :)

**Comment by mesqueeb** [comment]
@l2aelba You can pass `uid` like you are doing.
`userId` is available when your user is signed in. It will be the same as the `uid` of `firebase.auth()`.
