### ISSUE TITLE
[Bug] Filters are not updated when re-opening a DBChannel

### ISSUE THREAD

**Issue by coolhand79** [mesqueeb/vuex-easy-firestore#87]
_Originally posted by @coolhand79 in https://github.com/mesqueeb/vuex-easy-firestore/issues/65#issuecomment-442271670_

**Comment by coolhand79** [comment]
When re-opening a DBChannel with an updated filter, the new filter is not applied.

Example:
```javascript
const citiesModule = {
    firestorePath: "cities/",
    firestoreRefType: "collection",
    moduleName: "cities",
    statePropName: "docs",

    sync: {
        where: [
            ["state", "array-contains", "{state}"]
        ]
    }

store.dispatch('cities/openDBChannel', { state: 'CA' })
// Correct data is retrieved
// store.state.cities.docs === ['San Francisco', 'Los Angeles']

store.dispatch('cities/closeDBChannel', { clearModule: true })
store.dispatch('cities/openDBChannel', { state: 'OR' })
// Wrong data is retrieved - still using the old filter
// store.state.cities.docs === ['San Francisco', 'Los Angeles']

```

The only way I've been able to get this to work is by hacking around it:
```javascript

          store.state.cities._conf.sync.where[0][2] = 'OR';
         store.dispatch('cities/openDBChannel', { state: 'OR' })
```

**Comment by mesqueeb** [comment]
@coolhand79 Sorry it took me so long, but I fixed this in the latest version!

please try `npm i vuex-easy-firestore@latest` and if it works let me know and close this issue!

**Comment by mesqueeb** [comment]
That should be possible as well! 
I refactored the whole library to make sure that was possible. ^^ 

Try and let me know!! 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by coolhand79** [comment]
Unfortunately, it doesn't seem to work. 

When I call it like so: 
```javascript
store.dispatch('cities/openDBChannel', { state:db.doc(`/regions/east-bay-ca` })
store.dispatch('cities/closeDBChannel', { clearModule: true })
store.dispatch('cities/openDBChannel', { state: db.doc(`/regions/central-oregon` })
```
The re-opened channel never even goes back to the server and still contains the old data. Seems clearModule didn't execute and it still thinks the previous is valid and has been executed.  

Taking a look at the modules using the Vue Devtools:
First time opening DB channel: https://cl.ly/934a9c0e0c53
When reopening: https://cl.ly/3eb591bf2c61

Hope that helps

**Comment by mesqueeb** [comment]
Hi. I’m improving my test structure so i can make sure this won’t happen again. So sorry. 

I’ll need another couple of hours before i can upload a fix. Hold on!!!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mesqueeb** [comment]
Sorry for the hold up!
Fixed everything now.

What was happening is, even though the where filters were rewritten as a "getter", that getter was overwriting the state.... lol.

Please try `npm i vuex-easy-firestore@latest`
and let me know!

If it is fixed, please close the issue! ♡

**Comment by coolhand79** [comment]
Fixed!
