### ISSUE TITLE
use with typescript

### ISSUE THREAD

**Issue by andreav** [mesqueeb/vuex-easy-firestore#88]
Hello,
congratulations for this very interesting module.

Is it possible to use it with Vuex and Typescript?

I already have a code base using Vuex+Typescript, but decided to test vuex-easy-firestore for a new store module.

I'm getting 2 errors:
1. When importing module.js into index.ts i get:

` 
Could not find a declaration file for module './events/index.js'. '/home/andreav/Workspace/sosfilomena/src/store/events/index.js' implicitly has an 'any' type
`

I changed the import from:
`
import EventModule from './events/index.js'
`
to
`
let EventModule = require('./events/index')
`

2. Now when I start the site, I get this error:

```
Uncaught TypeError: plugin is not a function
 at eval (vuex.esm.js?2f62:351)
    at Array.forEach (<anonymous>)
    at new Store (vuex.esm.js?2f62:351)
    at eval (index.ts?0613:23)
    at Module../src/store/index.ts (main.js:8875)
    at __webpack_require__ (main.js:768)
    at fn (main.js:131)
    at eval (auth-guard.js?cfc9:1)
    at Module../src/router/auth-guard.js (main.js:8839)
    at __webpack_require__ (main.js:768)
```

My versions:
```
    "vue": "^2.5.17",
    "vuex": "^3.0.1",
    "vuex-easy-firestore": "^1.17.0"
```

My index.ts

```
import Vue from 'vue';
import Vuex, { StoreOptions } from 'vuex';
import { RootState } from './types';
import { user } from './user/index';
let EventModule = require('./events/index')

Vue.use(Vuex);

const store: StoreOptions<RootState> = {
    state: {
        version: '1.0.0' // a simple property
    },
    modules: {
        user,
    },
    plugins: [EventModule]
};

export default new Vuex.Store<RootState>(store);
```

Thank you!

**Comment by mesqueeb** [comment]
Hi, i'm not sure what the problem is since you import the library somewhere else than index.ts 

Can you try updating to the latest version and importing like so: 
```js
import {vuexEasyFirestore} from 'vuex-easy-firestore'

const pluginForVuex = vuexEasyFirestore(myModule)
```

Also remember to update to the lastest version. 

If this doesn't work can you have a look at the source code how I export the library? 

https://github.com/mesqueeb/vuex-easy-firestore/blob/master/src/index.ts 

It's written in TS but I never have used this inside a TS project. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by andreav** [comment]
Thank you, it looks like it works!
I renamed my index.js into index.ts, I think this was the problem.

Now, I'm so exited to use vuex-easy-firestore!
