### ISSUE TITLE
How to do forEach/multiple channels?

### ISSUE THREAD

**Issue by l2aelba** [mesqueeb/vuex-easy-firestore#93]
I'm not sure about I'm missing something or not. 

How to **multiple channels**? like..

```js
// forEach
dispatch('users/openDBChannel', { uid: 'ABC' })
dispatch('users/openDBChannel', { uid: 'XYZ' })
```

And right now I'm doing something like... (and it's work)

```js
createEasyFirestore({
  firestorePath: 'users/{uid}',
  firestoreRefType: 'doc',
  moduleName: 'users',
  serverChange: {
    modifiedHook: (updateStore, doc, id, store, source, change) => {
      store.state.users[doc.uid] = doc
    },
    addedHook: (updateStore, doc, id, store, source, change) => {
      store.state.users[doc.uid] = doc
    }
  }
})
```

**But does it not easier if we could do something like...?**

```js
createEasyFirestore({
  firestorePath: 'users/{uid}',
  firestoreRefType: 'doc',
  // moduleName: 'users/{uid}', ???
  // statePropName: '{uid}' ???
})
```

Expected result:

```js
state : {
   users: {
      'ABC' : 'data',
      'XYZ' : 'data',
      // _conf: (...)
      // _sync: (...)
   }
}
```
**I'm missing something?**

**Cheers!** vuex-easy-firestore 🍺

**Comment by mesqueeb** [comment]
I'm very confused by your setup.
Is there a reason you need to use `firestoreRefType: 'doc'` as opposed to `collection`?

**Comment by l2aelba** [comment]
@mesqueeb Tried with `collection` but how to get multiple like that? Its just replaced their old object

**Comment by mesqueeb** [comment]
The example I gave above. It will save all users like you want:
```js
state : {
   users: {
      'ABC' : 'data',
      'XYZ' : 'data',
      // _conf: (...)
      // _sync: (...)
   }
}
```

**Comment by l2aelba** [comment]
```
// sync: { where: [ ['users.{uid}.permission', '==', true] ] }
dispatch('users/openDBChannel', { uid: 'ABC' })
state : {
   users: {
      'ABC' : 'data'
      // _conf: (...)
      // _sync: (...)
   }
}
dispatch('users/openDBChannel', { uid: 'XYZ' })
state : {
   users: {
      'XYZ' : 'data'
      // _conf: (...)
      // _sync: (...)
   }
}

T
```

**Comment by mesqueeb** [comment]
@l2aelba I understand what's happening now. The other user document is being removed.

- a 'collection' is usually for multiple documents grouped in a single vuex module
- a 'doc' for a single doc also saved in a single vuex module

In your case I want to understand:
- How many ID's you need to filter on?
- Why do you need to filter on those IDs?
This is important to understand if you could maybe set up your firestore DB design differently.

**Comment by l2aelba** [comment]
@mesqueeb 
Filter ? This we will get the whole users from DB and filter it by client-side?

**Comment by mesqueeb** [comment]
No not fillables, I'm talking about `where`
I mean: you want to only get user's `{ uid: 'ABC' }` and `{ uid: 'XYZ' }`.

Is it always those two? Is it more? Is there a reason you need to filter on specific UID's?

**Comment by mesqueeb** [comment]
@l2aelba Yes, today I have rewrote the library so it's possible to pass new `where` filters on each `openDBChannel`.

But, I still want to know why you need to do this.

There's a possibility in your case it's better to use `fetchAndAdd` instead of `openDBChannel`. But I don't understand what your app is, or why you want to filter on single ID's.

It's also usually better to just add an extra field to the users you want to retrieve to filter on.
Eg. if you add a field like `thisIsTheOne: true` to all users you need (eg. 'ABC' and 'XYZ') then you can just do 
`dispatch('openDBChannel', {where: [['thisIsTheOne', '==', true]]})`

Why do you need to filter each time on a specific ID?

**Comment by l2aelba** [comment]
@mesqueeb I making a chat app
I don't want user to watch all changes from all users ([Firebase Reading is cost money](https://firebase.google.com/docs/firestore/pricing))

I just want that user to watch changes just their friends :)

**Comment by mesqueeb** [comment]
Hi,
I found a bug in openDBChannel that I fixed in the latest version.

Can you do `npm i vuex-easy-firestore@latest` and confirm for me?

### instead of this:
`dispatch('users/openDBChannel', {where: [['uid', '==', 'XYZ']]}))`

### please try this again:
```js
yourModule = {
  sync: {
    where: [
      ['uid', '==', '{uid}']
    ]
  }
}
// and just do this:
dispatch('users/openDBChannel', { uid: 'XYZ' })
```

I found a bug that prevented that bottom one from working, but should now be fixed.

Please try it for me and confirm you get this:

```js
createEasyFirestore({
  firestorePath: 'users/',
  firestoreRefType: 'collection',
  moduleName: 'users',
  sync: {
    where: [
      ['uid', '==', '{uid}']
    ]
  }
})

// Run
dispatch('users/openDBChannel', { uid: 'ABC' })
state : { // Result after dispatch('users/openDBChannel', { uid: 'ABC' })
   users: {
      'ABC' : data
   }
}
dispatch('users/openDBChannel', { uid: 'XYZ' })
state : { // Result after dispatch('users/openDBChannel', { uid: 'ABC' })
   users: {
      'ABC' : data
      'XYZ' : data // XYZ is added instead of overwriting
   }
}
```

**Comment by mesqueeb** [comment]
---
After about two years of open source, I finally got accepted for Github Sponsors!

#### 💜 [github.com/sponsors/mesqueeb](https://github.com/sponsors/mesqueeb) 💜 

A little about me:
- I love open-source
- 6 months ago I got a son, and am trying to be an awesome father 😅
- I'm doing freelance work here and there as my main job

#### If anyone was helped with vuex-easy-firestore, **I'd greatly appreciate any support**!

> BTW, donations get's paid DOUBLE by GitHub! (they're alchemists... 🦾)

Going forward 👨🏼‍💻
- I got great plans for the future of vuex-easy-firestore going above and beyond!! Look forward to it!!
- On to many more years of open-sourcing! 🎉
