### ISSUE TITLE
[documentation] modifiedHook execution timing

### ISSUE THREAD

**Issue by mesqueeb** [mesqueeb/vuex-easy-firestore#95]
https://github.com/mesqueeb/vuex-easy-firestore/issues/83#issuecomment-442887026

**Comment by mesqueeb** [comment]
@l2aelba 
I have tried to understand this behaviour, and I found out why.
every modification only launches `serverChange.modifiedHook` when a `firebase.firestore.FieldValue.serverTimestamp()` is used.

And this library uses that for `created_at` and `updated_at`.

So if you add those to `guard` then an insert won't execute `addedHook` and a modification won't execute `modifiedHook`.

However, if you want a hook on a local change, you can still use the `sync.insertHook` and `sync.patchHook` instead!

I'm gonna update the documentation now and close this thread when I've updated it.

**Comment by l2aelba** [comment]
@mesqueeb Thanks for info!

If just `updated_at` have to be used, its ok for me :)

**Comment by mesqueeb** [comment]
@l2aelba
Yeah, and I found out there was a bug with the addedHook, so just pushed another update to npm.

Please update to latest version and check the new detailed documentation on [Execution timings of hooks](https://mesqueeb.github.io/vuex-easy-firestore/extra-features.html#execution-timings-of-hooks).

**Comment by mesqueeb** [comment]
For anyone working with HOOKS, there has been a small (non-breaking) change to their behaviour.

Please read about it in the [latest release](https://github.com/mesqueeb/vuex-easy-firestore/releases/tag/v1.26.0).
