### ISSUE TITLE
Collections inception

### ISSUE THREAD

**Issue by arjendejong12** [mesqueeb/vuex-easy-firestore#97]
Hey there! 

I was wondering how to handle collections where documents have a subcollection and where those documents also have subcollections. For example: `countries/{countryId}/cities/{cityId]/streets`.
Is there a way to load all the data in one object, and still be able to add to these documents?
Another example, say I'd like to add the cities Amsterdam and The Hague into 'The Netherlands' document, and add 'Kalverstraat' to the city 'Amsterdam'. Is this possible, or is my DB flawed by design? I'd have views where I'd like to show all countries, all cities in a specific country, and all streets in a specific city in a specific country.

**Comment by mesqueeb** [comment]
@arjendejong12 you mean to load all streets from multiple countries into one module, but when you do a patch or insert have it synced to the path with the correct pathVariable?

I haven’t thought about this use case yet. 

I’d need to know more about your app first though. Like in the UI, is it like a map app where you gradually load other cities if they come into view? 

I guess the main point first is for me to understand: how do you currently use Vuex in your app and can we enhance your current Vuex setup with this library without big design changes. 

Could you go more into depth? 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by arjendejong12** [comment]
Something like that yes. Let's say I want to add 'Kalverstraat', I would need to have a path like this: countries/{id of The Netherlands}/cities/{id of Amsterdam}/streets. My actual project has different terms (districts, measure points, and measurements) but it has the same principle but the example is easier to understand.

Like I said I have three views, and all of them show a map. The first view with countries would show markers on each country in my database. The second view would show a map with markers on each city that is defined in the collection of the country document. The same for streets. However, not every country has cities, or every city has streets.

The user is able to add new cities to a country by selecting a country in a dropdown and is also able to add streets to a city. This city dropdown is dynamic and based on the country selected. The user is able to add extra data (let's say population) to a city/street document.

I'm currently using FieryVuex, which has the option to load subcollections in a collection (regardless of the depth) in one object. However, there's no way to check when the last street in the last city in the last country has been loaded (after which I'd hide a loading spinner). And I'd still have to write all the create/update/delete code myself, whereas your package already has that and that interests me a lot.

I hope this clarifies things a bit.

**Comment by arjendejong12** [comment]
![image](https://user-images.githubusercontent.com/10572554/49322128-c3e86480-f50c-11e8-8654-e75291e955a9.png)

**Comment by mesqueeb** [comment]
@arjendejong12 why is your Firestore nested? 
Imo it's much easier to work with Firestore that has all streets and all cities into big documents. 
Eg: 
Data: {countries, cities, streets}

And then you can lead only the relevant documents with setting up a where filter, and each time refill the Vuex module with more docs from the same path but a different where filter. 

Is there a reason you didn't take this approach? 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by arjendejong12** [comment]
This is actually my first project with Firestore, so I'm not sure what the best practices are. If I put them into seperate collections, should I store a reference? How would I use your library to actually connect them?

**Comment by mesqueeb** [comment]
I don't think that's necessary, just a field with a city ID on each street to filter on should be enough? 
And a field with a country ID on each city. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mesqueeb** [comment]
Do you know what I mean? 😀
Then you can just do [fetchAndAdd](https://mesqueeb.github.io/vuex-easy-firestore/guide.html#fetching-docs-with-different-filters) with all where-filters you require, based on the user input:

Eg. this flow:
1. open country "Belgium" and get all cities
`dispatch('citiesModule/fetchAndAdd', {whereFilters: [['country', '==', 'belgium']]})`
2. get streets for Antwerp (ik ben van Antwerpen 😀)
`dispatch('streetsModule/fetchAndAdd', {whereFilters: [['city', '==', 'antwerp']]})`
3. open another country "The Netherlands" and get all cities
`dispatch('citiesModule/fetchAndAdd', {whereFilters: [['country', '==', 'the-netherlands']]})`

etc. etc.

You'd just need to set up your `countriesModule`, `citiesModule` and `streetsModule` once.

**Comment by arjendejong12** [comment]
Yeah, I get what you mean, but I'm not sure how and where to fetch data dynamically. In my application, at the first view (Rayons), I also load the last added measurement.
![image](https://user-images.githubusercontent.com/10572554/49327923-07bc8780-f568-11e8-8d6b-5c0dfcf2e6da.png)
How would I achieve this?

**Comment by arjendejong12** [comment]
I'm doing this in the created() hook:
```
        this.$store.dispatch('rayon/fetchAndAdd').then(_ => {
            for (let [key, value] of Object.entries(this.$store.state.rayon.docs)) {
                console.log('r', key, value.name)
                this.$store.dispatch('measuring_point/fetchAndAdd', {
                    whereFilters: [['rayon', '==', value.name]],
                }).then(_ => {
                    for (let [keyy, valuee] of Object.entries(this.$store.state.measuring_point.docs)) {
                        console.log('mp', keyy, valuee)
                        this.$store.dispatch('measurements/fetchAndAdd', {
                            whereFilters: [['measuring_point', '==', valuee.name]],
                        }).then(_ => {
                            console.log(this.$store.state.measurements.docs)
                            for (let [keyyy, valueee] of Object.entries(this.$store.state.measurements.docs)) {
                                console.log('m', keyyy, valueee)
                            }
                        })
                    }
                })
            }
        })
```
I have two rayons, two measuring points for one rayon and one measurement for one measuring point. However, the one measurement gets console logged twice.

**Comment by mesqueeb** [comment]
Sorry i dont understand what you mean. Load the data dynamically?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by arjendejong12** [comment]
Well, I would need to first get the list of rayons in a dropdown, so I would need to fetch them first. Thinking about this, I feel like I know how to do this. I'm not sure if I've seen this in de documentation, but is there a way to view the store data in Vue Devtools?

**Comment by mesqueeb** [comment]
I have the feeling this is not really related to this library anymore. It’s unclear where your design can benefit from additional features to this library so i’ll close this for now. But feel free to continue the conversation. 

I’m not sure what the part is you are stuck with. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
